### ISSUE TITLE
Shall  `cd` builtin support `@` command line option ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1011]
`cd` builtin supports `@` command line option that can be used to open files under `/dev/file/xattr` path. This option was not present in `ksh93u+` release. This issue tracks investigating if it is worth keeping this option in next release.

**Comment by krader1961** [comment]
On my system that path doesn't exist:

```
$ ls /dev/file
ls: /dev/file: No such file or directory
```

In fact it doesn't exist on any of the my VMs that I use to test things on UNIX like OS's. If this feature is part of 3DFS support, or something similar, then it should be excised.
