### ISSUE TITLE
Random memory corruption due to out of bounds write in xec.c:iousepipe

### ISSUE THREAD

**Issue by pcpa** [att/ast#106]
In this sequence:
```
	fcntl(subpipe[0],F_SETFD,FD_CLOEXEC);
	subpipe[2] = fcntl(1,F_DUPFD,10);
	fcntl(subpipe[2],F_SETFD,FD_CLOEXEC);
	shp->fdstatus[subpipe[2]] = shp->fdstatus[1];
```
it may writes to random memory if `subpipe[2]` happens to become >= than `sh.gd.lim.open_max`.

**Comment by siteshwar** [comment]
For the reference the explanation and fix of this bug is provided in [rhbz 1506344](https://bugzilla.redhat.com/show_bug.cgi?id=1506344).

**Comment by pcpa** [comment]
There is also another related issue of unchecked -1 file descriptors that corrupt memory.
Related to https://github.com/siteshwar/ast/commit/e3b430462b20c81bfa760c24c086661ef4b0fd91
The above patch leaves an empty slot for unchecked writes to -1 offsets.

**Comment by siteshwar** [comment]
https://github.com/att/ast/pull/115

**Comment by krader1961** [comment]
@pcpa, Can you provide a way to reproduce this problem? I just merged a bunch of changes from the Solaris OS team (see issue #122). One of those changes should fix this issue. That change is a superset of PR #115 from the Redhat team.

**Comment by krader1961** [comment]
I'm going to assume the Solaris patch I merged (which was a superset of the Redhat change) fixes this. Still, it would be nice if someone could explain how to reproduce the problem so that we could write a regression unit test.
