### ISSUE TITLE
[FOSDEM 2019] Squeezing Water from Stone - KornShell in 2019

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1095]
Sharing this on GitHub as we don't have a mailing list.

My proposal for lightning talk at FOSDEM 2019 was accepted. You can find details of my talk [here](https://fosdem.org/2019/schedule/event/kornshell/).  This will be a brief status update about state of ksh93. If you are going to be at FOSDEM this year and would like to meet me in person, feel free to ping `situ` on freenode/oftc, or drop me an e-mail. Thanks!

EDIT: Fixed link.

**Comment by etscrivner** [comment]
Nice! Congrats on getting the talk accepted. I think getting this project a bit more publicity would be great :)

**Comment by DavidMorano** [comment]
@siteshwar 
> My proposal for lightning talk at FOSDEM 2019 was accepted.

Yes, total kudos!

**Comment by krader1961** [comment]
I wish I could be there to support you. I hope it goes well and your talk encourages more participation in keeping ksh alive.

**Comment by siteshwar** [comment]
Done with the talk today morning. Closing this issue. Video will be available later.
