### ISSUE TITLE
Compilation fails on NetBSD -current aarch64 (evbarm) 

### ISSUE THREAD

**Issue by DoktorCranium** [att/ast#1096]
Trying to build the ksh93 on NetBSD aarch64 since the pkgsrc/shells/ast-ksh is broken. Getting the following error during ninja build 

[root@arm64 ast]# ninja -C build
ninja: Entering directory `build'
[2/3] Linking target src/cmd/ksh93/shcomp.
FAILED: src/cmd/ksh93/shcomp 
clang  -o src/cmd/ksh93/shcomp 'src/cmd/ksh93/src@cmd@ksh93@@shcomp@exe/sh_shcomp.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/cmd/ksh93/libksh.a src/lib/libast/libast.a src/lib/libcmd/libcmd.a src/lib/libdll/libdll.a -lm -lexecinfo -lm -lexecinfo -lm -lexecinfo -Wl,--end-group  
src/cmd/ksh93/libksh.a(bltins_math.c.o): In function `local_nexttoward':
/mnt/usb/ast/build/../src/cmd/ksh93/bltins/math.c:109: undefined reference to `nexttowardl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x190): undefined reference to `expm1l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x478): undefined reference to `lgammal'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4c0): undefined reference to `log1pl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4d8): undefined reference to `log2l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x568): undefined reference to `remainderl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): undefined reference to `tgammal'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
[3/3] Linking target src/cmd/ksh93/ksh.
FAILED: src/cmd/ksh93/ksh 
clang  -o src/cmd/ksh93/ksh 'src/cmd/ksh93/src@cmd@ksh93@@ksh@exe/sh_pmain.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/cmd/ksh93/libksh.a src/lib/libast/libast.a src/lib/libcmd/libcmd.a src/lib/libdll/libdll.a -lm -lexecinfo -lm -lexecinfo -lm -lexecinfo -Wl,--end-group  
src/cmd/ksh93/libksh.a(bltins_math.c.o): In function `local_nexttoward':
/mnt/usb/ast/build/../src/cmd/ksh93/bltins/math.c:109: undefined reference to `nexttowardl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x190): undefined reference to `expm1l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x478): undefined reference to `lgammal'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4c0): undefined reference to `log1pl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4d8): undefined reference to `log2l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x568): undefined reference to `remainderl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): undefined reference to `tgammal'
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
[root@arm64 ast]# uname -a
NetBSD arm64 8.99.25 NetBSD 8.99.25 (GENERIC64) #0: Mon Nov 12 09:25:42 UTC 2018  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/evbarm/compile/GENERIC64 evbarm
[root@arm64 ast]# clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: aarch64-unknown-netbsd8.99
Thread model: posix
InstalledDir: /usr/pkg/bin

**Comment by siteshwar** [comment]
`meson` is not able to find library that contains math functions. Looks like [this](https://github.com/att/ast/blob/c5dac0e6a8f907c888f2f7e2e885b8396474013b/features/meson.build#L34) check is failing on NetBSD.

@DoktorCranium Are you missing `libm` on your system ?

**Comment by siteshwar** [comment]
Actually in the logs I see `-lm` is already present, so this check is successful. But linker is not able to find some math functions.

@DoktorCranium Do you see this error only on `aarch64` or other architectures too ?

**Comment by DoktorCranium** [comment]
Just checked this on NetBSD 8.0 amd64   - same failure 

[489/490] Linking target src/cmd/ksh93/shcomp.
FAILED: src/cmd/ksh93/shcomp 
cc  -o src/cmd/ksh93/shcomp 'src/cmd/ksh93/src@cmd@ksh93@@shcomp@exe/sh_shcomp.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/cmd/ksh93/libksh.a src/lib/libast/libast.a src/lib/libcmd/libcmd.a src/lib/libdll/libdll.a -lm -lexecinfo -lm -lexecinfo -lm -lexecinfo -Wl,--end-group  
src/cmd/ksh93/libksh.a(bltins_math.c.o): In function `local_nexttoward':
/home/user/BUILD/ast/build/../src/cmd/ksh93/bltins/math.c:109: undefined reference to `nexttowardl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x190): undefined reference to `expm1l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x478): undefined reference to `lgammal'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4c0): undefined reference to `log1pl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4d8): undefined reference to `log2l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x568): undefined reference to `remainderl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): undefined reference to `tgammal'
[490/490] Linking target src/cmd/ksh93/ksh.
FAILED: src/cmd/ksh93/ksh 
cc  -o src/cmd/ksh93/ksh 'src/cmd/ksh93/src@cmd@ksh93@@ksh@exe/sh_pmain.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/cmd/ksh93/libksh.a src/lib/libast/libast.a src/lib/libcmd/libcmd.a src/lib/libdll/libdll.a -lm -lexecinfo -lm -lexecinfo -lm -lexecinfo -Wl,--end-group  
src/cmd/ksh93/libksh.a(bltins_math.c.o): In function `local_nexttoward':
/home/user/BUILD/ast/build/../src/cmd/ksh93/bltins/math.c:109: undefined reference to `nexttowardl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x190): undefined reference to `expm1l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x478): undefined reference to `lgammal'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4c0): undefined reference to `log1pl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4d8): undefined reference to `log2l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x568): undefined reference to `remainderl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): undefined reference to `tgammal'
ninja: build stopped: subcommand failed.
netbsd# uname -a
NetBSD netbsd 8.0 NetBSD 8.0 (GENERIC) #0: Tue Jul 17 14:59:51 UTC 2018  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
netbsd# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/lto-wrapper
Target: x86_64--netbsd
Configured with: /usr/src/tools/gcc/../../external/gpl3/gcc.old/dist/configure --target=x86_64--netbsd --enable-long-long --enable-threads --with-bugurl=http://www.NetBSD.org/Misc/send-pr.html --with-pkgversion='NetBSD nb1 20171112' --with-system-zlib --disable-libstdcxx-dual-abi --enable-__cxa_atexit --enable-libstdcxx-time=rt --enable-libstdcxx-threads --with-tune=nocona --with-diagnostics-color=auto-if-env --with-mpc-lib=/var/obj/mknative/amd64-x86_64/usr/src/external/lgpl3/mpc/lib/libmpc --with-mpfr-lib=/var/obj/mknative/amd64-x86_64/usr/src/external/lgpl3/mpfr/lib/libmpfr --with-gmp-lib=/var/obj/mknative/amd64-x86_64/usr/src/external/lgpl3/gmp/lib/libgmp --with-mpc-include=/usr/src/external/lgpl3/mpc/dist/src --with-mpfr-include=/usr/src/external/lgpl3/mpfr/dist/src --with-gmp-include=/usr/src/external/lgpl3/gmp/lib/libgmp/arch/x86_64 --enable-tls --disable-multilib --disable-symvers --disable-libstdcxx-pch --disable-libstdcxx-dual-abi --build=x86_64-unknown-netbsd7.1 --host=x86_64--netbsd --with-sysroot=/var/obj/mknative/amd64-x86_64/usr/src/destdir.amd64
Thread model: posix
gcc version 5.5.0 (nb2 20180327)

**Comment by DoktorCranium** [comment]
I was able to build the ast-ksh with no problem on Debian Linux 8 (32bit mips) last year from pkgsrc, and Im pretty sure it was possible to do so on earlier NetBSD versions too (see ftp://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/shells/static-ast-ksh/README.html )

**Comment by DoktorCranium** [comment]
Im trying the following branch to see if that builds https://github.com/att/ast/tree/2012-08-01-master

**Comment by krader1961** [comment]
@DoktorCranium That branch is just the last stable release: ksh93u+. Which is what I would expect to already be part of NetBSD. The legacy code that used Nmake+IFFE tested each individual math function to see if the platform provided it. When we switched to Meson we deliberately chose to simplify the build by simply assuming each platform provided all the legacy functions found in libm. At the time I argued, and still believe, that functions like `tgammal` have no place in ksh. We could introduce feature tests for each individual math function but my preference is to just remove most of them as they have no business being exposed to the ksh language.

**Comment by DoktorCranium** [comment]
@krader1961  Yes it is, but there seems to be some problems with it since at least NetBSD 7 .. that is something NetBSD only related, however I was hoping to get a fresh build via master branch from ast-ksh on the evbarm aarch64

**Comment by siteshwar** [comment]
@DoktorCranium Please try out my changes from https://github.com/att/ast/pull/1097 and let us know if it fixes this issue.

**Comment by DoktorCranium** [comment]
Still getting the following (amd64) 
/home/user/BUILD/ast/build/../src/cmd/ksh93/bltins/math.c:109: undefined reference to `nexttowardl'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x478): undefined reference to `lgammal'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x4d8): undefined reference to `log2l'
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): undefined reference to `tgammal'

**Comment by siteshwar** [comment]
@DoktorCranium Give me couple of days. I need to setup a NetBSD machine. I will get back to you with a proper fix.

**Comment by krader1961** [comment]
@DoktorCranium For the moment if you want to move past this problem edit *src/cmd/ksh93/bltins/math.c* and simply comment out each function your platform doesn't provide.

**Comment by DoktorCranium** [comment]
Will do, and thank you for your efforts on this, highly appreciated

**Comment by DoktorCranium** [comment]
I can confirm that removing the non-existing math functions from src/cmd/ksh93/bltins/math.c
works on NetBSD

[root@netbsd ast]# ninja -C build
ninja: Entering directory `build'
[5/5] Linking target src/cmd/ksh93/ksh.
[root@netbsd ast]# ninja -C build install
ninja: Entering directory `build'
[1/2] Installing files.
Installing src/cmd/ksh93/ksh to /usr/local/bin
Installing src/cmd/ksh93/shcomp to /usr/local/bin
Installing /home/user/BUILD/ast/src/cmd/ksh93/ksh.1 to /usr/local/share/man/man1
[root@netbsd ast]# cd /usr/local/bin/
[root@netbsd bin]# ls -alstr
total 16744
8384 -rwxr-xr-x  1 root  wheel  4268792 Jan  2 21:02 shcomp
8352 -rwxr-xr-x  1 root  wheel  4257200 Jan  2 21:02 ksh
   4 drwxr-xr-x  2 root  wheel      512 Jan  2 21:02 .
   4 drwxr-xr-x  4 root  wheel      512 Jan  2 21:02 ..
[root@netbsd bin]# ./ksh 
#

**Comment by krader1961** [comment]
@siteshwar If I can't convince you to just remove the functions that have no business being included in ksh I'd like to propose something simpler than a bunch of feature tests for the presence of each function. Instead add a boolean option to *meson_options.txt* that controls whether those obscure, and possibly missing, functions are exposed. Then predicate the relevant code in *math.c* on that build option. It can default to true (enable the functions) or false (don't enable them) although I favor the latter. Then a particular distro like Fedora can set it to true to maximize compatibility with ksh93u.

**Comment by krader1961** [comment]
Note also that on FreeBSD these compilation warnings are emitted as a consequence of including math functions that have no business being included in ksh:

```
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x550): warning: powl has lower than advertised precision
src/cmd/ksh93/libksh.a(bltins_math.c.o):(.data.rel.ro+0x658): warning: tgammal has lower than advertised precision
```

**Comment by krader1961** [comment]
Another data point is that neither zsh nor bash support these math functions. Which is not a reason for ksh to not support them. But it does suggest that the ksh support was done solely because someone thought "hey, I can detect at build time whether the function is available and expose it if it is available." Without regard to whether the math function makes sense in the context of a ksh script/program.

**Comment by krader1961** [comment]
See also issue #88 and issue #344. I have yet to see anyone justify why ksh should expose these libm functions. Other than "someone might be using them in a legacy ksh script." And, as discussed in those issues, a ksh script cannot expect those functions to be available.

**Comment by siteshwar** [comment]
> @siteshwar If I can't convince you to just remove the functions that have no business being included in ksh I'd like to propose something simpler than a bunch of feature tests for the presence of each function. Instead add a boolean option to _meson_options.txt_ that controls whether those obscure, and possibly missing, functions are exposed. Then predicate the relevant code in _math.c_ on that build option. It can default to true (enable the functions) or false (don't enable them) although I favor the latter. Then a particular distro like Fedora can set it to true to maximize compatibility with ksh93u.

I checked math feature test from `ksh-20050202-0.3E.2` that was shipped with RHEL-3 and it has test for these math functions:

```
lib	absl,acosl,acoshl,asinl,asinhl,atanl,atan2l,expl,cosl,coshl	math.h
lib	fabsl,powl,hypotl,fmodl,logl,sinl,sqrtl,tanl,tanhl,strtold	math.h
npt	absl,acosl,acoshl,asinl,asinhl,atanl,atan2l,expl,cosl,coshl	math.h
npt	fabsl,powl,hypotl,fmodl,logl,sinl,sqrtl,tanl,tanhl,strtold	math.h
```

And rest of the math function were added later. Related entry for [this change](https://github.com/att/ast/blob/3e661e6c45463461817785dd3d3da8760b4a7937/src/cmd/ksh93/RELEASE#L2343-L2344):

```
1714 06-10-15 +The remaining math functions from C99 were added for any system
1715       that supports them.
```

Now the question is, have people started using these functions in last 10 years ? We have no data about it.

If we are not able to make math functions work reliably on some platforms, we can disable these functions on such platforms. However we should avoid proactively removing them on platforms where they work. We can keep these functions under low maintenance, but let's not remove them from platforms where they are working.

**Comment by krader1961** [comment]
I have never argued for removing the basic trigonometric (e.g., `cos`, `sin`, `tan`) and basic non-trigonometric math functions (e.g., `sqrt`, `abs`). While only a few of those (e.g., `abs`) are likely to see any significant use the others are available on every platform we care about and generally trivial to implement using fallback implementations if we needed to do so.  My argument has been about functions like `gamma`, `j0,` `y0` and `erf`.

Having said that it appears from the original problem description, and looking at documentation, that NetBSD supports all of those functions but only the `double`, not `long double`, variants. What is odd is that it does provide `long double` variants for the others; e.g., `fmodl`. So all that should be needed is to provide wrappers that cast between `Sfdouble_t` (aka `long double`) and `double`.

**Comment by siteshwar** [comment]
@DoktorCranium It should work now. Ideally NetBSD should start shipping `ksh` from current upstream. I see there was [some discussion](https://mail-index.netbsd.org/pkgsrc-users/2018/09/02/msg027383.html) around it. But no one cared to package it yet.

**Comment by DoktorCranium** [comment]
[490/490] Linking target src/cmd/ksh93/ksh.
[root@netbsd ksh]# ninja -C build install
ninja: Entering directory `build'
[1/2] Installing files.
Installing src/cmd/ksh93/ksh to /usr/local/bin
Installing src/cmd/ksh93/shcomp to /usr/local/bin
Installing /home/user/ksh/src/cmd/ksh93/ksh.1 to /usr/local/share/man/man1
[root@netbsd ksh]# /usr/pkg/bin/ksh93 --version
  version         sh (AT&T Research) 93u+ 2012-08-01
[root@netbsd ksh]#
