### ISSUE TITLE
ksh regression: with FIGNORE, . and .. are no longer automatically excluded from glob expansions

### ISSUE THREAD

**Issue by stephane-chazelas** [att/ast#11]
From the manual:

> If FIGNORE  is set, then each file name component that matches the pattern defined by the value of FIGNORE is ignored when generating the matching filenames.   **The  names .  and ..  are also ignored.**

That used to be true. As in, that works as documented in ksh93k+ for instance, but in modern versions (and also in ksh93m, I couldn't find ksh93l to test) that doesn't:

```
$ FIGNORE=x ksh93v- -c 'echo *'
. .. a .a
$ FIGNORE=x ksh93k+ -c 'echo *'
a .a
```

**Comment by siteshwar** [comment]
I would like to see how it worked in `ksh93k+`. Are the older sources for ksh available to download from somewhere ? The oldest I could find from our repositories is `ksh93q` in RHEL-3.

**Comment by dannyweldon** [comment]
I found some old archives here for ksh93o+ (ast-ksh.2003-07-24.tgz):

http://ftp.vim.org/ftp/ftp/pub/ibiblio/distributions/slack390/slack390-9.1/source/ap/ksh93/

I'm not sure when the source was originally available publicly.

**Comment by krader1961** [comment]
This "feature" is an example of the sort of enhancement to zsh that caused me to abandon it as my primary shell. That is, a feature that was added even though it isn't a good fit for the language and is all but guaranteed to cause problems out of proportion to any benefit it provides solely because someone thought it was a "cool idea". But if we're going to retain it I would prefer that we not revert to the documented behavior that hasn't existed for 16 years. It would be better to document the feature more clearly. In particular showing how the user can exclude the `.` and `..` directory entries via patterns like `FIGNORE='+(.|..|x*)'`.

Please note that if you don't define `FIGNORE` then something like `echo *` does not include file names that begin with a `.`. So why in the world should defining that variable only exclude `.` and `..` but not other names that begin with a `.`?

**Comment by siteshwar** [comment]
Ignoring `.` and `..` seems to  be for sanity purpose. For e.g. consider the case when you have set `FIGNORE="*.swp"` and execute `rm -rf *` in a directory. That would end up deleting parent directory too.

**Comment by krader1961** [comment]
> Ignoring . and .. seems to be for sanity purpose....

Without a `FIGNORE` var all "dot" file names are ignored by the expansion of `*`. The problem as I see it is that this only special cases `.` and `..` while otherwise passing through other paths that begin with a `.`.

**Comment by siteshwar** [comment]
> he problem as I see it is that this only special cases . and .. while otherwise passing through other paths that begin with a ..

I am not sure if I understood. Can you give me an example ?

**Comment by stephane-chazelas** [comment]
See https://mirrors.slackware.com/slackware/slackware-8.0/source/ap/ksh93/ for instance for the ksh93k+ source (slackware is a good source for old source). AFAIK, that was the first publicly release version of ksh93.

To me, the best thing to do is for globs never to return `.` and `..` like pdksh and derivatives, zsh or fish do. That is **never** wanted. `.` and `..` should not even be returned by `readdir()` IMO (as is done on some systems and allowed by POSIX (while `.` and `..` in paths are required to be supported, they should be seen as tree navigation tools, not directory entries)).

Note that as far as _inspiration_ goes, it usually goes from ksh93 to bash, not the other way round. `GLOBIGNORE` (added in 2.0 in 1996) in `bash` (which is also severely broken to the point it's hardly usable) was clearly inspired from ksh's FIGNORE, and also does that ignoring of `.` and `..` (but not properly, see https://unix.stackexchange.com/questions/40662/what-is-the-setting-in-bash-for-globbing-to-control-whether-matches-dot-files/279448?r=SearchResults#279448 for instance).

The point is, when you do `FIGNORE='*~'`, you do not want `.` and `..` to suddenly be matched by every `*` or `*.*` or `??*`... glob

**Comment by siteshwar** [comment]
> Without a FIGNORE var all "dot" file names are ignored by the expansion of *. The problem as I see it is that this only special cases . and .. while otherwise passing through other paths that begin with a ..

I misread last single dot as a double dot. Sorry for the confusion.

I believe `.` and `..` are special cased because they have special meaning. If you have `FIGNORE` set, you are explicitly setting which names you want to ignore, so rest of the files that start with a `.` are included.

@krader1961 Are you proposing that we should ignore all files that start with a `.` even if `FIGNORE` is set ?

**Comment by krader1961** [comment]
Okay, I agree that the magic `.` and `..` file names should be excluded. But it seems to me for consistency that should be true regardless of whether or not `FIGNORE` is set. Why is it acceptable for `echo .*` to include those file names but not when `FIGNORE` is set? Having said that my main objection to the `FIGNORE` behavior is that it turns `echo *` into `echo .* *`. Yes, the man page obliquely (i.e., in a very unclear manner) documents that behavior. Which means we can't change it in a bug fix release. But it still bugs me greatly. :smile:

**Comment by siteshwar** [comment]
@stephane-chazelas Thanks for your insights.

**Comment by stephane-chazelas** [comment]
> Okay, I agree that the magic `.` and `..` file names should be excluded. But it seems to me for consistency that should be true regardless of whether or not `FIGNORE` is set.

Yes, that's my opinion as well.

Note that files whose name starts with `.` are ignored because of somebody making a typo in the 70s when trying to exclude `.` and `..` from the list of entries in a directory (for `ls` or `/etc/glob` I can't remember). And that stuck as a way to have hidden files.

The point is it was the Unix authors intention to exclude `.` and `..` from the list of entries in a directory.

That was discussed on the austin-group (POSIX) mailing list, and it looks like they would not be opposed to allowing shell globs not including `.` and `..` on systems when `readdir()` includes them (see https://www.mail-archive.com/austin-group-l@opengroup.org/msg01176.html).

So I think it should be relatively safe to make the move right now (especially considering several other shells do that already, including some called `ksh`), which could help in getting POSIX to not only allow it but also recommand it (in a first instance, and maybe require it in a future version), as `.*` including `.` and `..` has been a plague for far too long (see how `rm -r` had to be modified so it refuses to remove `.` and `..` to work around that for instance https://unix.stackexchange.com/a/90075).

Another thing we may  want to do is ignore `FIGNORE` from the environment (like we do for `IFS`). Until this fix, having `FIGNORE='!(.|..)'` could cause serious havoc.
