### ISSUE TITLE
`sh_pipe()` versus `sh_rpipe()` and use of `socketpair()`

### ISSUE THREAD

**Issue by krader1961** [att/ast#1120]
The `sh_pipe()` function in *src/cmd/ksh93/sh/io.c* has this block of code:

```
#if _pipe_socketpair && !_stream_peek
    if (pv[0] > 2) (void)fcntl(pv[0], F_SETFD, FD_CLOEXEC);
    if (pv[1] > 2) (void)fcntl(pv[1], F_SETFD, FD_CLOEXEC);
#endif
```

This appears to be bogus in as much as it should not matter whether `pipe()` or `socketpair()` was used to establish the "pipe". Either the file descriptors should be marked "close on exec" or they shouldn't. The callers of `sh_pipe()` certainly don't care how the pipe was established.

Those statements should either be executed unconditionally of those preprocessor symbols or they should be removed.

**Comment by siteshwar** [comment]
This change was made after last stable release:

```
586 12-09-05  Modified pipe and socketpair creating to create file descriptors
587       with close-on-exec set.
```

I think we should retain it.

**Comment by krader1961** [comment]
> I think we should retain it.

@siteshwar If you mean those file descriptors should be marked "close on exec" regardless of how they were established I agree. That is, whether the native `pipe()` syscall or `socketpair()` was used it should not matter whether they are closed on exec. The problem is the current code only does so if `socketpair()` is used to establish the pipe.

**Comment by krader1961** [comment]
> The problem is the current code only does so if socketpair() is used to establish the pipe.

Unless we're on a [SVR4](https://en.wikipedia.org/wiki/UNIX_System_V) based system like Dynix/ptx or Solaris where `_stream_peak` would be true. But since we do not, at this time, have a feature test for that symbol it is always false.

**Comment by krader1961** [comment]
And, of course, it should not matter if the preprocessor symbol `_stream_peak` is defined. Whether a file descriptor created by this function is inherited by an `exec()`'d program should not depend on how the file descriptor was created. It looks like the preprocessor predicate is "cargo cult" programming. If it isn't then there should have been a comment describing why those file descriptors needed to be modified only if `#if _pipe_socketpair && !_stream_peek` was true.
