### ISSUE TITLE
`getconf -c` should show an error on invalid parameter

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1169]
**Description of problem:**
`getconf -c` should show an error on invalid parameter. According to man page only these parameters should be accepted.

```
 -c, --call=RE   Display variables with call prefix that matches RE. The call prefixes are:
                    CS    confstr(2)
                    PC    pathconf(2)
                    PC    fpathconf(2)
                    SC    sysconf(2)
                    SI    sysinfo(2)
                    XX    Constant value.
```

**Ksh version:**
2017.0.0-devel-2380-gc0aaf51f

**How reproducible:**
Always

**Steps to reproduce:**
```
builtin getconf
getconf -c=foo RELEASE
```
**Actual results:**
`ksh` shows value of `RELEASE` parameter

**Expected results:**
`ksh` should show an error.

**Additional info:**
This bug is present in both `ksh93v-` and `ksh93u+` releases.

**Comment by krader1961** [comment]
See #1174 and #1118. I don't think we should expend any effort to fix this bug.

**Comment by krader1961** [comment]
Closing since we've removed the `getconf` builtin making this issue moot.
