### ISSUE TITLE
`getconf -l` does not lowercase some variables

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1171]
**Description of problem:**

From `getconf` man page:

```
-l, --lowercase List variable names in lower case.
```

**Ksh version:**
2017.0.0-devel-2380-gc0aaf51f

**How reproducible:**
Always

**Steps to reproduce:**
```
builtin getconf
getconf -l
```

**Actual results:**
Some variables in output are not lowercased. For e.g.

```
LEVEL1_ICACHE_SIZE=32768
LEVEL1_ICACHE_ASSOC=8
```

**Expected results:**
All variable names should be lowercased.

**Additional info:**
This bug is present in `ksh93v-` release, but not `ksh93u+`.

**Comment by krader1961** [comment]
See #1174 and #1118. I don't think we should expend any effort to fix this bug.

**Comment by krader1961** [comment]
Closing since we've removed the `getconf` builtin making this issue moot.
