### ISSUE TITLE
`getconf -n` does not match variable name

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1172]
**Description of problem:**

From `getconf` man page:

```
  -n, --name=RE   Display variables with name that match RE.
```

**Ksh version:**
2017.0.0-devel-2380-gc0aaf51f

**How reproducible:**
Always

**Steps to reproduce:**

```
builtin getconf
getconf -n=RELEASE
```

**Actual results:**
```
_XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
XBS5_WIDTH_RESTRICTED_ENVS=XBS5_LP64_OFF64
_POSIX_C_LANG_SUPPORT=
_POSIX_C_LANG_SUPPORT_R=
```

**Expected results:**
It should show name and value of matching name only.

**Additional info:**
This bug is present in both `ksh93u+` and `ksh93v-` releases.

**Comment by krader1961** [comment]
See #1174 and #1118. I don't think we should expend any effort to fix this bug.

**Comment by krader1961** [comment]
Closing since we've removed the `getconf` builtin making this issue moot.
