### ISSUE TITLE
`getconf -q` does not quote values

### ISSUE THREAD

**Issue by siteshwar** [att/ast#1173]
**Description of problem:**
According to `getconf` man page:

```
-q, --quote     "..." quote values.
```

**Ksh version:**
2017.0.0-devel-2380-gc0aaf51f

**How reproducible:**
Always

**Steps to reproduce:**
```
builtin getconf
getconf -q
```

**Actual results:**
Values are not quoted.

**Expected results:**
Values should be quoted.

**Additional info:**
This bug is present in both `ksh93u+` and `ksh93v-` releases.

**Comment by krader1961** [comment]
See #1174 and #1118. I don't think we should expend any effort to fix this bug.

**Comment by krader1961** [comment]
Closing since we've removed the `getconf` builtin making this issue moot.
