### ISSUE TITLE
The sfsetbuf() function has one use case that is FUBAR

### ISSUE THREAD

**Issue by krader1961** [att/ast#1194]
The `sfsetbuf()` API is used like this in at least one place: `sfsetbuf(wm, (void *)1, 0)`. Notice the cast to ensure the `buf` parameter is not NULL. The point of that call is to do nothing other than return a pointer to the stream buffer. This caught my eye because I've been working today on eliminating pointless casts. And casting to void* is almost always pointless. In this case there should be a `sfgetbuf()` function that does the same thing without requiring silly casts.

**Comment by kdudka** [comment]
On Tuesday, March 5, 2019 6:23:29 AM CET Kurtis Rader wrote:
> The `sfsetbuf()` API is used like this in at least one place: `sfsetbuf(wm,
> (void *)1, 0)`. Notice the cast to ensure the `buf` parameter is not NULL.
> The point of that call is to do nothing other than return a pointer to the
> stream buffer.

Yes, there is a comment documenting it in the implementation of sfsetbuf():

    if (size == 0 && buf) { /* special case to get buffer info */

> This caught my eye because I've been working today on
> eliminating pointless casts.

What do you mean by pointless?  Does it cause undefined behavior or something?
Or do you just mean that it does not match your taste?

> And casting to void* is almost always pointless.

Not really.  Casting to (void *) is very common in C APIs.  For example,
NULL is usually defined as ((void *) 0), shmat() returns ((void *) -1)
on error, etc.

> In this case there should be a `sfgetbuf()` function that does
> the same thing without requiring silly casts.

While I admit that the proposed API would look more modern, I do not think
it is worth the troubles.  You would either need to keep both APIs for 
compatibility, which would be even more messy, or update all users of the
API, which comes with a risk that something will break for no real benefit.

**Comment by krader1961** [comment]
Yes, there are a few legitimate uses of a `(void *)` cast. I have yet to see one in this project. What I have seen are lots of pointless casts of this form: `memset((void *)a_ptr, 0, sizeof(*a_ptr));`. And at least one instance of this pattern:

```
Type_A *ap;
Type_B *bp = (void *)ap;
```

Which is a great way to mask bugs that the compiler or static analysis tools would otherwise warn about.

As for `sfsetbuf(ptr, (void *)1, 0)` that API can be retained but the code clarified by introducing a macro or wrapper function name `sfgetbuf()` which hides the perplexing cast.
