### ISSUE TITLE
`struct Shell_s` member `jmplist` should be a `struct checkpt*` not `sigjmp_buf*`

### ISSUE THREAD

**Issue by krader1961** [att/ast#1287]
The `struct Shell_s` member `jmplist` should be a `struct checkpt*` not `sigjmp_buf*`. That it is type `sigjump_buf*` is either because the structure of the code made it impossible to include header *fault.h* before `struct Shell_s` is defined or the authors were just being lazy. The result is that most of the places that use that structure member require an explicit `struct checkpt*` cast solely to correctly reflect the type of the object actually pointed to. This is an anti-pattern seen throughout the code that tends to cause bugs or at least make it less likely the compiler and lint tools will identify a problem.

This came to my attention while resolving issue #1284.

**Comment by dannyweldon** [comment]
I must say that that code is much cleaner now.
