### ISSUE TITLE
Eliminate _more_void_int and _more_long_int

### ISSUE THREAD

**Issue by krader1961** [att/ast#1308]
Building ksh as a 64 bit binary on Solaris results in these warnings:

```
../src/lib/libast/sfio/sfvscanf.c: In function 'sfvscanf':
../src/lib/libast/sfio/sfvscanf.c:893:41: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                     *((void **)value) = (void *)((uint)argv.lu);
                                         ^

../src/lib/libast/sfio/sfvprintf.c: In function 'sfvprintf':
../src/lib/libast/sfio/sfvprintf.c:943:23: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
             v = (int)((uint)argv.vp);
                       ^
```

The `_more_void_int` preprocessor symbol is only used in three places and not defined anywhere. Not even in the ksh93v- source before we started updating everything. Similarly `_more_long_int` is used one place and not defined anywhere. Possibly the intent was for a distro, like Solaris, to define those symbols via `CCFLAGS` but since they aren't documented it's difficult to see how a distro would know they need to do that.

**Comment by krader1961** [comment]
FWIW, the two warnings in my opening comment only appeared after I modified the build to use the `-m64` flag (via Meson's `add_global_arguments()` method) when building libast and ksh. However, those arguments (and thus the `-m64` flag) are not automatically used when calling methods like  `long_size = cc.sizeof('long')`. Which means that on Solaris when building without `-m64` we end up with

```
#define _ast_sizeof_int 4
#define _ast_sizeof_long 4
#define _ast_sizeof_off_t 8
#define _ast_sizeof_pointer 4
#define _ast_sizeof_size_t 4
#define _ast_sizeof_int32_t 4
#define _ast_sizeof_wchar_t 4
```

But with `-m64` we get this:

```
#define _ast_sizeof_int 4
#define _ast_sizeof_long 8
#define _ast_sizeof_off_t 8
#define _ast_sizeof_pointer 8
#define _ast_sizeof_size_t 8
#define _ast_sizeof_int32_t 4
#define _ast_sizeof_wchar_t 4
```

TBD is how best to handle this situation since there doesn't seem to be a clean way of telling meson to do everything in 64 bit mode on Solaris short of `env CFLAGS=-m64 meson`. Which I'm not sure is the best way to resolve this issue.

P.S., The `meson` build configuration stage reports this warning:

```
WARNING: Unknown CPU family 'i86pc', please report this at https://github.com/mesonbuild/meson/issues/new with theoutput of `uname -a` and `cat /proc/cpuinfo`
```

**Comment by krader1961** [comment]
BTW, We're down to five unit test failures on Solaris. One is in the `vi.exp` unit test. The other four are timeouts in the `basic` and `signal` unit tests (including their `shcomp` variants). I'd love to know if the ksh93u+ release passes these unit tests on Solaris.

**Comment by sneyx1234** [comment]
Howto invoke unit tests and specify the IUT (item under test)?
```
# /usr/bin/ksh -c "print -v .sh.version"
Version AJM 93u+ 2012-08-01
```

**Comment by sneyx1234** [comment]
```
# uname -p
sparc
# uname -v
11.4.6.4.0
# uname -s
SunOS

# cp /usr/bin/ksh build/src/cmd/ksh93/ksh
# cd build
# meson test --setup=malloc

...

Ok:                  185
Expected Fail:         0
Fail:                 89
Unexpected Pass:       0
Skipped:               0
Timeout:               2

```

**Comment by krader1961** [comment]
@sneyx1234 What does the version reported by */usr/bin/ksh* have to do with anything? That program won't be used, or tested, by `meson test`. Beyond that obvious issue we don't know how you are building the code. And reporting that you observe 89 test failures doesn't help us fix whatever is causing those failures on your system.

On my OpenIndiana virtual machine, using build steps I haven't yet documented, I am seeing one test failure and four timeouts.

I'm partially at fault for saying "on Solaris" in my previous comment since I am actually using OpenIndiana. But if that alone is the reason for such a dramatic difference in behavior then I would recommend we officially stop supporting the "official" Solaris distro. However, I doubt that is the reason for the disparity. It is more likely that you simply haven't yet figured out the magic build sequence on Solaris that I am slowly figuring out and using.

**Comment by sneyx1234** [comment]
If "ksh93u+" != "93u+" ... 93u+ is AT&T version without meson+ninja ... with "package" build system from research.att.com downloaded before it appear in git at all. 
e.g.:
INIT.2013-05-24.tgz
INIT.2014-12-24.tgz

**Comment by sneyx1234** [comment]
So whats the reference of the unit tests?

**Comment by krader1961** [comment]
> How to invoke unit tests and specify the IUT (item under test)?

By specifying the unit test name; e.g. `meson test basic`.

> If "ksh93u+" != "93u+" ... 93u+ is AT&T version without meson+ninja ...

I don't understand your question. When AT&T moved this project to Github the version they were working on was "ksh93v-". We chose to use that code base for our efforts to keep ksh relevant. We could have chosen to use the "ksh93u+" source for this work. For good or bad we chose the "ksh93v-" source code as the basis for this project.

> So whats the reference of the unit tests?

It is the ksh program built from the source in this project. That is, `src/cmd/ksh93/ksh`. The unit tests are intended to ensure a new ksh release is backward compatible with old releases. As well as to verify that new behavior is correct.

**Comment by sneyx1234** [comment]
Which of "ksh93v-" is the refrerence:
```
14-12-24  --- Release ksh93v- ---
13-10-08  --- Release ksh93v- ---
12-06-28  --- Release ksh93u+ ---
12-08-01  --- Release ksh93u+ ---
12-02-29  --- Release ksh93u+ ---
11-02-08  --- Release ksh93u  ---
10-03-05  --- Release ksh93t+  ---
08-10-31  --- Release ksh93t  ---
```

**Comment by krader1961** [comment]
@sneyx1234 The answer to your question is in the Git change history. You seem to have done `grep 'Release ksh93' *`. Which tells you almost nothing about the basis for the current code. See commit 2f2b1b8be31 from the AT&T AST team that formed the basis for the current code.

**Comment by krader1961** [comment]
Closing without actually doing the cleanup because it only affects two SFIO modules. The risk of doing anything to the SFIO code other than bug fixes cannot be justified.
