### ISSUE TITLE
OpenBSD: execinfo.h found, but build does not link with "-lexecinfo"

### ISSUE THREAD

**Issue by kusalananda** [att/ast#1321]
**Description of problem:**

On OpenBSD, if the 3rd party package `libexecinfo` (`devel/libexecinfo`) happens to be installed, the `execinfo.h` header is picked up from `/usr/local/include`, but the `libexecinfo` library is not used in the linking steps of the build, giving rise to errors like these:

```
[1/10] ccache cc  -o src/lib/libast/tests/cdt/tvthread 'src/lib/libast/tests/cdt/062a450@@tvthread@exe/tvthread.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/lib/libast/libast.a src/lib/libast/libenv.a -lpthread -lm /usr/local/lib/libiconv.so.6.0 -Wl,--end-group -Wl,-z,origin '-Wl,-rpath,$ORIGIN/../..' -Wl,-rpath-link,/home/kk/local/build/ast/build/src/lib/libast
FAILED: src/lib/libast/tests/cdt/tvthread
ccache cc  -o src/lib/libast/tests/cdt/tvthread 'src/lib/libast/tests/cdt/062a450@@tvthread@exe/tvthread.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/lib/libast/libast.a src/lib/libast/libenv.a -lpthread -lm /usr/local/lib/libiconv.so.6.0 -Wl,--end-group -Wl,-z,origin '-Wl,-rpath,$ORIGIN/../..' -Wl,-rpath-link,/home/kk/local/build/ast/build/src/lib/libast
ld: error: undefined symbol: backtrace
>>> referenced by debug.c:315 (../src/lib/libast/misc/debug.c:315)
>>>               misc_debug.c.o:(dump_backtrace) in archive src/lib/libast/libast.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Ksh version:**

Current GitHub master (2145422449996d056758bcc3b8acb8a494457603).

**How reproducible:**

Always.

**Steps to reproduce:**
1. Build project using plain Meson configuration (no additional tweaks on command line) on OpenBSD (I'm using OpenBSD-current on amd64) with `libexecinfo` installed from ports.
2.
3.

**Actual results:**

Errors when linking (see above).

**Expected results:**

Successful build.

**Additional info:**

From Meson's configure log output:

```
Library execinfo found: NO
Has header "execinfo.h" : YES
```

The latter of these two triggers the use of the `backtrace()` function at `src/lib/libast/misc/debug.c:315`, which is the one causing the linking issues.

**Comment by kusalananda** [comment]
It's a bit of a mystery to me why it finds and correctly uses `libiconv` but not `libexecinfo`...

**Comment by kusalananda** [comment]
It seems to be related to the Clang compiler.  The default compiler is Clang 7.0.1 (`cc`).  The GCC 4.2.1 C compiler in the base OpenBSD system also has the same issue. However, compiling with the GCC 8.3.0 C compiler from ports (the executable is called `egcc`) seems to work.

**Comment by kusalananda** [comment]
Suggestion: Require that the `execinfo.h` header _and_ the `libexecinfo` library both can be found before trying to use either.

**Comment by sneyx1234** [comment]
There is a mystery related to "gcc" and "libiconv" ... very important is the libiconv used when the compiler stages are producted ... native iconv or bundled iconv ... i think it is independent from BSD ... I can only confirm solaris here. So thats not really a ksh issue?

**Comment by krader1961** [comment]
> Require that the execinfo.h header and the libexecinfo library both can be found before trying to use either.

That certainly seems reasonable but I'm worried there may be systems where the header exists but the functions are in libc (or equivalent) rather than a distinct library. Consider a header like *socket.h*. Some systems have the functions declared in that header in libc. On other systems they are in libsocket. So I'll modify the configure step to handle the execinfo situation the same way.

**Comment by krader1961** [comment]
Hold on! We do test for the existence of libexecinfo and use it if found:

https://github.com/att/ast/blob/2145422449996d056758bcc3b8acb8a494457603/features/meson.build#L51-L53

Which I realize after rereading your original problem statement, @kusalananda. Also, I have libexecinfo installed via the package found [here](https://ftp.openbsd.org/pub/OpenBSD/6.2/packages/amd64/) and Meson correctly detects it. So as you noted the question is why Meson isn't finding it on your system. On mine it is at */usr/local/lib/libexecinfo.so.2.0* and */usr/local/lib/libexecinfo.a*. Do those files not exist on your system? And is it really the case you can legitimately configure a OpenBSD system such that it includes *execinfo.h* without including the associated library?

**Comment by kusalananda** [comment]
The `libexecinfo` port, which is installed on my system as a dependency for other software (which I installed recently, which is why I did not have an issue building `ksh` previously), contains

```
/usr/local/bin/backtrace_test
/usr/local/include/execinfo.h
/usr/local/lib/libexecinfo.a
/usr/local/lib/libexecinfo.so.2.0
/usr/local/lib/libexecinfo_p.a
/usr/local/man/man3/backtrace.3
```
 
A short test program based on the `backtrace(3)` manual works with the default `cc` (Clang) compiler when using the correct flags:

```
$ CPPFLAGS=-I/usr/local/include LDFLAGS='-L/usr/local/lib -lexecinfo -Wl,--export-dynamic' make prog
cc -O2 -pipe  -I/usr/local/include -L/usr/local/lib -lexecinfo -Wl,--export-dynamic  -o prog prog.c
```
```
$ ./prog
0x6812aeca369 <print_backtrace+41> at ./prog
0x6812aeca407 <main+23> at ./prog
0x6812aeca148 <_start+328> at ./prog
```

What may be interesting to note is that when Meson performs its test for for the `libexecinfo` library, it does _not_ use `-L/usr/local/lib`:

```
Running compile:
Working directory:  /tmp/tmpw51n4847
Command line:  ccache cc /tmp/tmpw51n4847/testfile.c -pipe -D_FILE_OFFSET_BITS=64 -o /tmp/tmpw51n4847/output.exe -O0 -Wl,--start-group -lexecinfo -Wl,--end-group -Wl,--allow-shlib-undefined

Code:
 int main(int argc, char **argv) { return 0; }
Compiler stdout:

Compiler stderr:
 ld: error: unable to find library -lexecinfo
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Library execinfo found: NO
```

Since the `meson-logs/meson-log.txt` file (which the above is taken from) does not have the corresponding level of detail for libraries that it _does_ find, I don't know how it invokes `cc` to locate `libiconv` (which it finds).

By the way, the way it links in `libiconv` is not by setting `-L/usr/local/lib` and then using `-liconv`. Instead it mentions `/usr/local/lib/libiconv.so.6.0` directly on the command line:

```
[51/184] Linking target src/lib/libast/tests/cdt/trehash.
FAILED: src/lib/libast/tests/cdt/trehash
ccache cc  -o src/lib/libast/tests/cdt/trehash 'src/lib/libast/tests/cdt/062a450@@trehash@exe/trehash.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/lib/libast/libast.a src/lib/libast/libenv.a -lpthread -lm /usr/local/lib/libiconv.so.6.0 -Wl,--end-group -Wl,-z,origin '-Wl,-rpath,$ORIGIN/../..' -Wl,-rpath-link,/home/kk/local/build/ast/build/src/lib/libast
ld: error: undefined symbol: backtrace
>>> referenced by debug.c:315 (../src/lib/libast/misc/debug.c:315)
>>>               misc_debug.c.o:(dump_backtrace) in archive src/lib/libast/libast.a
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[53/184] Generating version.h with a custom command.
ninja: build stopped: subcommand failed.
```

I'm inclined to point the finger as Meson for doing something odd here.  I'm using Meson 0.50.1.

For what it's worth, here's how Meson writes the corresponding linking step for `egcc` (GCC 8.3.0), which works:

```
[1/8] /usr/local/bin/egcc  -o src/lib/libast/tests/cdt/trehash 'src/lib/libast/tests/cdt/062a450@@trehash@exe/trehash.c.o' -Wl,--as-needed -Wl,--export-dynamic -Wl,--start-group src/lib/libast/libast.a src/lib/libast/libenv.a -lpthread -lm /usr/local/lib/libiconv.so.6.0 -lexecinfo -Wl,--end-group -Wl,-z,origin '-Wl,-rpath,$ORIGIN/../..' -Wl,-rpath-link,/home/kk/local/build/ast/build/src/lib/libast
```

See how it's using `-lexecinfo` (with no `-L/usr/local/lib` no less, maybe a default linker path?), but how it's _not_ using `-liconv`. It would be good to know what the difference in handling is between these two libraries.

**Comment by krader1961** [comment]
@kusalananda I've been building and running unit tests on OpenBSD 6.2 with the same packages for several months. It builds fine for me using either clang or gcc (e.g., `env CC=gcc meson`). And we're most definitely passing `-L/usr/local/lib`. See here

https://github.com/att/ast/blob/f8fe1d5ef5147f168ecf55aef2385028521bef17/features/meson.build#L51-L53

and

https://github.com/att/ast/blob/f8fe1d5ef5147f168ecf55aef2385028521bef17/features/meson.build#L30-L36

I had to add that to get ksh to build on OpenBSD 6.2. Something is weird about your system. I see in your log entries you're using `ccache`. I'm not; i.e., I do not have the ccache package installed. Perhaps that is relevant. What happens if you disable ccache?

**Comment by kusalananda** [comment]
`ccache` (the compiler cache) is being picked up by Mason by default because I happened to have it installed (I did not explicitly choose to run with this).  Disabling `ccache` changes nothing.

Yes, I know and I see that `/usr/local/lib` is being added in `features/meson.build`, and I can only tell you that it does _not_ translate into a `-L/usr/local/lib` compiler command line option for me. The line is in effect, because commenting it out makes it not detect `libiconv` (you get the same issue with `iconv` in this case where it detects the header but not the library, and you start getting linker errors for _that_ instead).

OpenBSD 6.2 was released in October 2017 and has is no longer receiving security updates, you should upgrade to 6.5.  I believe that the default linker changed to Clang's `lld` in 6.5, for example, which may possibly affect this.

I will install vanilla OpenBSD systems in VMs over the day (or in the next few days) with OpenBSD 6.2 trough to 6.5, to see when the building of `ksh` starts to fail.  This is easier for me to do than trying to figure out how to get Meson to use alternate bits of toolchains (`/usr/bin/ld.bfd` (the GNU linker), for example, instead of `/usr/bin/ld.lld` (the default Clang linker)).

**Comment by krader1961** [comment]
> I believe that the default linker changed to Clang's lld in 6.5, for example, which may possibly affect this.

That is a reasonable and good (i.e., likely to be true) hypothesis. But since I've never used OpenBSD outside of a VM for testing this project I don't know how to advise you regarding how to proceed on that hypothesis.

@kusalananda We are dependent on someone like you to figure this out. The sole reason I setup a OpenBSD 6.2 instance was to test ksh builds on that platform. If I could reproduce your problem on that platform I would be happy to figure out what is wrong and how to fix it. But there are only so many hours in a day and I'm not about to spend more time setting up a VM running OpenBSD 6.5. @siteshwar and myself are happy to answer questions and look at logs.

**Comment by krader1961** [comment]
Also, with respect to building ksh using alternate build tools I agree. There is no documentation how to do so, and there is no reason to expect someone like yourself to figure it out. But until recently the two primary contributors have haven't needed to figure out such matters. Which means doing nothing more than `env CC=alt_cc meson` resulted in a successful build. It was only after I setup an OpenIndiana (a Solaris clone) VM did I start to grapple with the need to alter the default Meson/Ninja behaviors via env vars and Meson flags.

**Comment by kusalananda** [comment]
I'm happy do do some testing and light tweaking of Meson build files to at least try to figure out whether it's me running a weird system, or whether Meson is acting up, or whether there's something up with the `ksh` build files, no worries. I'll do so over the next few days I hope. I'll use default settings for everything to start with (including the available releases of Meson and libraries on the various OpenBSD-stable branches).

**Comment by kusalananda** [comment]
You'll be happy to know that I successfully built the project in an OpenBSD 6.5-stable VM with both `libiconv` and `libexecinfo` installed.  I'm happy about this too as it means I don't have to go on to try the same thing for 6.4, 6.3 and 6.2, and it means I can concentrate on figuring out what else it is (on my side) that is interfering with the build on my OpenBSD 6.5-current system.  I'll report back when I find out what it is.

**Comment by kusalananda** [comment]
Right. This is a Meson issue. In particular, it's an issue with Meson 0.50.1 (not Meson 0.50.0). I will open an issue with them.

The bug is right here: https://github.com/mesonbuild/meson/commit/97dc00dc92d9309a473f60388d11b08882008da1#r33722380

**Comment by krader1961** [comment]
That makes sense. When I setup my OpenBSD 6.2 VM I installed Meson from the then current master. The last time I updated it was from commit a15a8b7e made on 4/29. The change which breaks things occurred two weeks later.

**Comment by krader1961** [comment]
I added a [comment](https://github.com/mesonbuild/meson/issues/5432#issuecomment-497224102) to the Meson issue @kusalananda opened. It's not clear what we can do to workaround that bug. I'm leaving this open since we may need to formally document how to deal with this problem depending on what the Meson team says in response.

**Comment by kusalananda** [comment]
I don't think there's much else to do here. The issue is Meson's from now on. I have also submitted a patch for the OpenBSD port of Meson to circumvent the issue on OpenBSD systems specifically (a patch that would possibly not be appropriate for other BSD systems). It's not a `ksh` issue.

**Comment by krader1961** [comment]
> I don't think there's much else to do here.

Yes, that's probably true. I was pondering whether we should formally document this type of issue in the directions for building ksh. But that becomes its own maintenance burden as we then need to track different Meson versions, etc. This issue is probably sufficient for anyone else who has trouble building on OpenBSD.

**Comment by kusalananda** [comment]
(Sigh)

This exact issue returns with the recent OpenBSD update of Meson to 0.52.0.  I will try to investigate why this breaks again, and then (later) possibly update the issue on Meson's side of things as the issue that I opened there in May (https://github.com/mesonbuild/meson/issues/5432) hasn't been closed yet.
