### ISSUE TITLE
Suggested improvements to the published test coverage report 

### ISSUE THREAD

**Issue by krader1961** [att/ast#1345]
First, I think `lcov` produces better HTML output and seems to be more accurate; at least with respect to branch coverage stats. See https://www.skepticism.us/ast/coveragereport/. So please consider switching from gcov to lcov.

Second, you're already excluding the AST API unit tests from the report but **not** excluding the ksh API unit tests; e.g., *cmd/ksh93/tests/api/debug.c*. I recommend replacing your current exclusion pattern with something like `*/tests/*`. Alternatively, explicitly exclude the ksh API test path.

Note that to exclude the unit test directories when using `lcov` a wrapper script is needed. This is the script I use on my system. It is in *~/bin* which I have in `PATH` before */usr/local/bin*. TBD is how to do this in a more generic manner. Sadly, `lcov` doesn't support a config file option that allows for this type of per-project filtering and neither does `meson`.

```
#!/bin/sh
#
# This wraps the real lcov command so that I can exclude API tests from the
# results.

# echo WTF: "$@" >/dev/tty
if [ "$1" = "--remove" ]
then
    /usr/local/bin/lcov "$@" '*/tests/*'
else
    /usr/local/bin/lcov "$@"
fi
```

**Comment by krader1961** [comment]
Consider line 57 in the [gcov report](http://situ.im/ast/coveragereport/index..._src_lib_libast_string_chresc.c.html) created by @siteshwar. That statement obviously has to be executed if the loop condition is ever true yet the gcov report says it wasn't while the [lcov report](https://www.skepticism.us/ast/coveragereport/src/lib/libast/string/chresc.c.gcov.html) correctly shows that it was executed. It's also possible this isn't a gcov vs lcov issue. It may be a difference between the coverage data provided by clang/LLVM vs gcc.

**Comment by siteshwar** [comment]
@krader1961 Done!

**Comment by siteshwar** [comment]
I have made suggested improvements in the [report](http://situ.im/ast/coveragereport/). I used `--exclude` flag to remove `*/tests/*` pattern. @krader1961 Feel free to close this bug if you are happy with layout of the report.

**Comment by krader1961** [comment]
LGTM. There are other changes I'd like to make such as changing the deep red low coverage color. Also, if the code is compiled by clang/LLVM then a workaround is needed to fix the line coverage for the function definition line. I have fixes for both but they're not yet in a form suitable for committing.
