### ISSUE TITLE
Remove `fpclassify()` math function

### ISSUE THREAD

**Issue by krader1961** [att/ast#1346]
I was adding some unit tests to improve test coverage of *src/cmd/ksh93/bltins/math.c* and noticed the `fpclassify()` function. That math function is completely unusable, at least in any portable fashion, because it returns small ints that correspond to symbols like `FP_NAN` in the *math.h* system header and those symbols are not available to a ksh script. So, for example, `print $(( fpclassify(1.0) ))` outputs `4` which, on my system, corresponds to `FP_NORMAL`. This is an even better example than those I documented in issue #88 as to why so many of the libc math functions should not be automatically exposed to ksh scripts just because doing so is trivial.

Cleaning this up by eliminating the truly useless math functions should be done after the next stable release. By "truly useless" I mean in the context of a ksh script not that these functions aren't useful to a high performance numeric computation app written in C/C++.

**Comment by krader1961** [comment]
Too, the `nextafter()` and `nexttoward()` functions which can't really be used in any meaningful manner in a ksh script.

**Comment by krader1961** [comment]
Note that the calls of the `local_nextafter()` and `local_nexttoward()` functions have a garbage value for the `type_2` argument. Yes, it is unused by those functions but I would still expect it to be initialized to something such as zero or -1. Also, the `type_1` argument is always `3` regardless of whether the arg was a var was created by `typeset -F`, `typeset -lF`, `typeset -sF`, or was a literal number. Which means the code always calls the "long double" variant of those functions. Which means the result is likely to be incorrect if a "float" or "double" var type was passed in since you can't simply cast a "long double" to a "double" or "float" to simulate the behavior of those two variants.

I'm going to remove `nextafter()` and `nexttoward()` because they are broken. The probability any script is using them is zero or so close to zero that it doesn't matter. If there is a script using those functions it is relying on broken behavior so tough luck.

**Comment by krader1961** [comment]
I just noticed, as a consequence of trying to improve math function test coverage, that Linux has `ilogb()` and related math functions that are in the same class of functions as `fpclassify()`, `j0`, etcetera. Further cementing my belief the existing set of math functions was not based on usefulness to a ksh script but solely because the libc/libm functions at that time had those public functions. Which is a bad reason to expose that functionality to the ksh language.

**Comment by krader1961** [comment]
Unsurprisingly the values returned by `fpclassify()` are different between BSD/macOS and Linux systems for identical inputs. Which is another reason for eliminating this function since ksh provides no way to portably deal with such differences.

**Comment by melbit-dannyw** [comment]
> I'm going to remove nextafter() and nexttoward() because they are broken.

Please fix them rather than remove them.  You have done a great job fixing lots of other bugs.

As for `fpclassify()` returning unspecified values, how is that handled in other scripting languages?  It might be time to start defining some math constants.  I'm wondering if they could be defined under .sh.math like this:

`.sh.math.FP_NAN`
`.sh.math.FP_NORMAL`

Or perhaps like this to avoid clashes with user-defined functions:

`.sh.math.const.FP_NAN`
`.sh.math.const.FP_NORMAL`

So that they could be used in arithmetic expressions like so:

```sh
(( fpclassify(n) == FP_NORMAL )) && echo Normal
```

BTW, here are some old examples using `dtksh` that rely heavily on arithmetical expressions, albeit only integer arithmetic, but you get the idea and they could just as easily use advanced math functions:

http://www.brendangregg.com/dtkshdemos.html

**Comment by krader1961** [comment]
@melbit-dannyw Note that we already have `isnan()` and `isinf()`. Those are almost certainly the only two cases any ksh program will care about. The other cases such as `FP_SUBNORMAL` aren't going to arise. Too, given how freely ksh converts between float, double, and long double, and in ways the ksh programmer has no control over, those other cases can't be meaningful handled. Also, how many ksh programs have you ever seen that use even `isnan()` or `ininf()`?

The blog post you linked to is interesting in the same way it's interesting that people have written [assemblers](https://news.ycombinator.com/item?id=7882066) using just the POSIX shell spec or tools like awk It's cool that such things are possible but there are better tools for the job. If all you know is a hammer everything looks like a nail. :smile:

**Comment by krader1961** [comment]
Gah! The code includes math functions `issubnormal()`, `isnormal()`, and `iszero()` for the other, not particularly interesting `fpclassify()` return values. So there is zero justification for `fpclassify()` unless it was used for non-standard float representations such as `FP_SUPERNORMAL`.

I would argue those math functions should also be removed since the math functions in question always work with a `Sfdouble_t` type (i.e., `long double`). Which means that if you define your ksh var using `typeset -F` or `typeset -sF` the result of `issubnormal()` (and possibly the other two) might be garbage since you can't arbitrarily convert the representation and expect the classification to be the same. And it certainly isn't going to be performant enough for anyone to bother to write a high performance and high quality program in the ksh language.

**Comment by krader1961** [comment]
See https://marc.info/?l=ast-users&m=120978599416025&w=2 from 2006-12-06 (a mere 12.5 years ago). It seems like Glen Fowler, a core contributor before the project was killed within AT&T, recognized the problem with the half-baked implementation of all the corner-case or obscure math functions:

> a lot of the <math.h> edge case api support has the feel of
> "standardized before used in the real world"

That was from a Google search for "ksh isnan".

**Comment by krader1961** [comment]
Sigh. I spent a few minutes reviewing Google "ksh fpclassify" results and could not find a single example where it was used or documented as being useful.
