### ISSUE TITLE
2020.0.0-alpha2

### ISSUE THREAD

**Issue by cschuber** [att/ast#1385]
**Description of problem:**
gcc 9 fails to build

**Ksh version:**
2020.0.0-alpha1

**How reproducible:**
gcc 9

**Steps to reproduce:**
1. 63e9edcb6084d4b164439065e2d71f3e900ec3c7 resolves this issue.
2.
3.

**Actual results:**

**Expected results:**

**Additional info:**
Would it be possible to tag 2020.0.0-alpha2 based on 63e9edcb6084d4b164439065e2d71f3e900ec3c7 ?

**Comment by siteshwar** [comment]
@cschuber Thanks for the heads up! 

As @krader1961 mentioned, we agreed to do a beta release this week. I will keep you cc'ed in the release announcement.

**Comment by siteshwar** [comment]
https://github.com/att/ast/commit/32d8131bf18b602128857a5870a9e90b0b18f383
