### ISSUE TITLE
ksh reading big lines allocate much more memory than needed

### ISSUE THREAD

**Issue by freedge** [att/ast#1401]
**Description of problem:**

ksh memory usage seems to increase exponentially when reading lines of increasing bigger size

**Ksh version:**

```sh (AT&T Research) 93u+ 2012-08-01``` from opensuse package ksh-v93vu-lp151.2.24.x86_64.

**How reproducible:**

systematically

**Steps to reproduce:**

```
for i in `seq 200`; do SFIO_OPTIONS="SF_MAXR=${i}00000"  ksh -c 'read line < /dev/zero; grep VmPeak /proc/$$/status ; echo "." '; done
```

Alternative reproducer:

```
~) dd if=/dev/zero of=zeroes count=4096 bs=10000  
4096+0 records in
4096+0 records out
40960000 bytes (41 MB) copied, 0.178398 s, 230 MB/s
~)  ksh -c 'read line < zeroes; grep VmPeak /proc/$$/status ; echo "." '  
VmPeak: 12561432 kB
.
```
12GB to read a 41MB file...

**Actual results:**

ksh requires over 200MB to read a line of 5MB.

it requires over 700MB to read a line of 10MB.

it requires over 1.5GB to read a line of 15MB.

**Expected results:**

A more linear, and much less reduced, memory consumption.

**Comment by krader1961** [comment]
@freedge, Thank you for taking the time to open a problem report. Please note that this is the official AT&T ksh source code. We have no control over whether OpenSuse upgrades their ksh version to the version provided by this project.

More importantly is that I can't reproduce your problem. First, your reproduction script has a typo: *dev/zero* should be */dev/zero*. However, even correcting that I get this error on every execution of the loop body:

```
/usr/bin/ksh: read: line length: limit exceeded
```

Also, support for the `SF_MAXR` env var was removed after the ksh93u+ release by the AT&T AST team. If you can reproduce the problem using a ksh binary built from the github master branch of this project (which was based on the ksh93v- work in progress release) please update this issue or open a new issue.

**Comment by krader1961** [comment]
Also, I am curious why you are using `SF_MAXR` in your test since it is not documented. Did you test without setting that option?

**Comment by freedge** [comment]
Thanks for your reply! My set-up is a bit broken, sorry for the typo. I included another reproducer that will work and that does not use the SF_MAXR thing.

I found that SF_MAXR through reading the code, and it makes it a little simpler to have ksh read the given number of characters from /dev/zero (instead of creating a file every time as I did in the second reproducer). My intent was to plot the amount of memory used by progressively increasing the number of bytes read from /dev/zero.

In any case, I have tried with the latest ksh package available for opensuse (and ksh --version does not show the version btw) and it works perfectly, the memory used grows linearly with the amount of characters read in the line.

I am not convinced I will be able to convince SUSE to upgrade that ksh version though. I will probably have to fix my scripts instead :)

**Comment by KeithBierman** [comment]
Note that if/when --version doesn't work, you aren't actually running KSH.
SUSE's default is to provide mksh (which isn't really ksh at all, it's the
old pdksh under continued BSD development). On SUSE you have to
intentionally reinstall ksh ... which gets ksh93 (I forget which version
precisely).

I've been unhappy about this particular SUSEism for quite some time; but
their customers have come to rely on it ... so I'm sure it's too late for
them to change. But you might be able to persuade them to replace ksh93
(optional install) with a newer version ... but unless we're bug for bug
compatible that might be a stretch as well. From my limited interactions
with SUSE folks over the years, I conjecture they'd simply provide a
*third* ksh (all invoked the same way) as an optional install ... but I'd
like to be wrong.

Keith Bierman
khbkhb@gmail.com
303 997 2749

**Comment by freedge** [comment]
thanks for your reply Keith

keeping SUSE apart of the discussion, the issue is easily reproducible with the branch 2012-08-01-master:

```
> ./arch/linux.i386-64/bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01

> dd if=/dev/zero of=zeroes count=4096 bs=10000
4096+0 records in
4096+0 records out
40960000 bytes (41 MB, 39 MiB) copied, 0.0848546 s, 483 MB/s

> ./arch/linux.i386-64/bin/ksh -c "read line < zeroes"
./arch/linux.i386-64/bin/ksh: read: storage allocator out of space on 22249472 byte request ( region 3765993472 segments 341 busy 121:22353424:22152224 free 341:3743605376:22118304 ) [Cannot allocate memory]
```
