### ISSUE TITLE
Segfault on invalid character class

### ISSUE THREAD

**Issue by McDutchie** [att/ast#1409]
**Description of problem:**
ksh segfaults when a pattern has an invalid character class.

**Ksh version:**
Version A 2020.0.0-beta1-91-g857b0587

**How reproducible:**
Always

**Steps to reproduce:**
1. `ksh -c 'case x in [x[:bogus:]]) echo x ;; esac'`

**Actual results:**
```
### 90210 Function backtrace:
1   handle_sigsegv (in ksh) (fault.c:72)
2   _sigtramp (in libsystem_platform.dylib) + 29
3   0x00007fff9839a140 (in libobjc.A.dylib)
4   regcomp_seq (in ksh) (regcomp.c:2570)
5   regcomp_con (in ksh) (regcomp.c:2649)
6   regcomp_alt (in ksh) (regcomp.c:2672)
7   regcomp (in ksh) (regcomp.c:3060)
8   regcache (in ksh) (regcache.c:172)
9   strngrpmatch (in ksh) (strmatch.c:122)
10  strmatch (in ksh) (strmatch.c:162)
11  sh_exec (in ksh) (xec.c:2080)
12  exfile (in ksh) (main.c:517)
13  sh_main (in ksh) (main.c:315)
14  main (in ksh) (pmain.c:39)
15  start (in libdyld.dylib) + 1
16  0x00000003 (in ksh)
Abort trap: 6
```

**Expected results:**
no output

**Additional info:**
n/a

**Comment by krader1961** [comment]
Thx, @McDutchie. This is a regression from commit e2370e8a. The bug is that my cleanup doesn't correctly handle not finding the named char class after removing support for custom char classes. Fix is trivial (a single line) and I'll add a regression test.
