### ISSUE TITLE
lchmod feature test leaves temporary files around

### ISSUE THREAD

**Issue by kusalananda** [att/ast#1414]
**Description of problem:**
When reconfiguring the project, the temporary files created by `features/lchmod_fallback.c` are left in the current directory. These should ideally be removed automatically.

**Ksh version:**
Version A 2020.0.0-beta1-121-gb18d4aeb

**How reproducible:**
Always reproducible on systems where the `features/lchmod_fallback.c` code gets used and where that code terminates successfully. I'm using OpenBSD-current (pre-6.6).

**Steps to reproduce:**
1. `ninja reconfigure`
2. `ls lchmod_fallback_*`
3.

**Actual results:**
```
$ ninja reconfigure
```
```
$ ls -l lchmod_fallback_*
----------  1 kk  kk   0 Oct  9 11:47 lchmod_fallback_hlink.79217
----------  1 kk  kk   0 Oct  9 11:47 lchmod_fallback_hlink.96912
lrwxr-x--x  1 kk  kk  27 Oct  9 11:47 lchmod_fallback_slink.79217@ -> lchmod_fallback_hlink.79217
lrwxr-x--x  1 kk  kk  27 Oct  9 11:47 lchmod_fallback_slink.96912@ -> lchmod_fallback_hlink.96912
```

**Expected results:**

The `lchmod_fallback_*` files should not be left behind (additionally, they should maybe be created under `$TMPDIR`?).

**Additional info:**

Patch that unlinks the files before terminating successfully (the files are already removed upon unsuccessful termination):
```
diff --git a/features/lchmod_fallback.c b/features/lchmod_fallback.c
index afbbc1ef..88a5b54b 100644
--- a/features/lchmod_fallback.c
+++ b/features/lchmod_fallback.c
@@ -66,6 +66,9 @@ int main() {
         goto err_exit;
     }

+    if (*fname_hlink) unlink(fname_hlink);
+    if (*fname_slink) unlink(fname_slink);
+
     return 0;

 err_exit:
```

**Comment by krader1961** [comment]
Good catch, @kusalananda. Configuring, building, and running unit tests should never leave artifacts in random locations that is not the build tree or a unique temp dir. That the pre-Meson version of the project did so was one of the things that made me grind my teeth.

**Comment by krader1961** [comment]
Also, in this case I'm not inclined to complicate the feature test by adding the equivalent of the `get_pathtemp_dir()` function since there are just four file names and they are already unique enough that dropping them in the CWD shouldn't be a problem. So just clean up after ourselves.
