### ISSUE TITLE
Include more info in the version string and eliminate `fallback-version-number`

### ISSUE THREAD

**Issue by krader1961** [att/ast#1417]
I've never been very happy about the need for the `fallback-version-number` option defined in *meson_options.txt* and used in *src/cmd/ksh93/include/meson.build*. That exists solely to facilitate builds when the `git` command isn't available. And if that is true the resulting version string is, at best, misleading if not an outright lie. It would be far better to use an alternative means of creating the version string based on the actual state of the repo. This also means we can include more info that can help us understand the state of the repo that was used to create a particular *ksh* binary.

Thanks to the relatively simple design of the Git meta database, and the fact almost all the info is stored as plain text in files it is straightforward to write a program that extracts the info we need. Since python is already a dependency we can write a small python program to emit the version string. That makes it easier to include additional info such as the actual commit ID and branch name. Regardless of whether there is a tag for the current commit.

P.S., Note that we could also construct the version string using a relatively straightforward C program if we didn't want to depend on python. But it's considerably easier to do this in python.

**Comment by kdudka** [comment]
I think that `git` command is usually available when you build out of a git repo.  What needs to be covered is builds from distribution tarballs where you have no `.git` directory.  In this case it does not matter whether the `git` command is available or not.

**Comment by krader1961** [comment]
Good point, @kdudka. I don't recall that reason being mentioned by @siteshwar way back when this was implemented but clearly we need to accommodate that case. Still, there isn't any reason to make it a value that can be set when running `meson` to configure the build. I'd also prefer a mechanism that makes it harder for someone to do a build from an arbitrary commit, and without git metadata, that then uses an incorrect fallback value. Sadly, handling that situation robustly is likely to be far more costly than can be justified but I'll ponder it for a few days before throwing in the towel.

**Comment by krader1961** [comment]
I meant to close this last year. Clearly, we need something like `fallback-version-number`. I only wish we had named it `version-string` and always used its value if the option was used rather than only if `git describe` failed. Oh well.
