### ISSUE TITLE
Google Group for Korn Shell set to private rather than public

### ISSUE THREAD

**Issue by kshfan** [att/ast#1430]
The google group listed in README.md:
https://groups.google.com/d/forum/korn-shell
is set to be private.  It is not publicly viewable without logging in.  (I haven't made sure, but this seems to imply having a Google account is mandatory)
I know public google groups are possible:
https://groups.google.com/forum/#!forum/osg-puppet
https://groups.google.com/forum/#!forum/ansible-project
These are just examples.  I can view them while not logged into a google account.

Why is the Korn shell Google group set private?  Can it be set public?

Better yet, why not use a mailing list instead?  This is very effective and the most open way for people to communicate and contribute.
With stuff like GNU Mailman 3.x or Apache Pony Mail you can even have a web interface, if desired.
But even if the Google group was just set public, that'd be an improvement.

**Comment by siteshwar** [comment]
I fixed the permissions now.

**Comment by kshfan** [comment]
> I fixed the permissions now.

Thanks!
:D

**Comment by kdudka** [comment]
> Better yet, why not use a mailing list instead?

This option was also discussed but the problem was that nobody found a freely available mailing-list service with acceptable terms of use.
