### ISSUE TITLE
history mechanism not working: " hist: 0-0: invalid range"

### ISSUE THREAD

**Issue by jghub** [att/ast#1432]
**Description of problem:**

command history not working. previous commands cannot be navigated/retrieved via arrow keys. 'hist' command throws errorrs like "hist: 0-0: invalid range". this is seen in OSX with the ksh installed via the MacPorts package management system. .sh_history file is in place and contains command history from an older (≈ 2012)  ksh instance running also on that machine.

**Ksh version:**

 Version A 2020.0.0-beta1

**How reproducible:**

always.

**Comment by krader1961** [comment]
Does this happen with ksh93u+? I can't reproduce this problem. Even after

1. removing my *~/.sh_history*, 
2. starting a ksh93u+ interactive shell, 
3. typing a few commands,
4. starting a ksh 2020.0.0 interactive shell,
5. typing `hist`.

So either this is a corner case that triggers a bug or your *~/.sh_history* is corrupt. Note that both ksh93u+ and the current version incorrectly handle `hist` when there is no *~/.sh_history` when the shell was started. I see `<81>^Ahist` in my editor. So clearly there are bugs in this code.

@jghub Are you able and willing to build ksh from source? This requires having Meson, Ninja, and a C compiler installed but little else. If so I can provide a patch that adds diagnostic `DPRINTF()` statements that should help identify the source of the bug.

**Comment by jghub** [comment]
> Does this happen with ksh93u+? I can't reproduce this problem.

 no. Version AJM 93u+ 2012-08-01 works perfectly normal with the history file (which it generated itself in the first place of course).

but I now moved .sh_history(ksh93u+) to the side and only _then_ started ksh 2020.0.0 and in this case the latter works fine, generates the (now not yet existent) .sh_history(ksh2020) and recognizes its own history as it should.  quiting ksh(2020), moving  .sh_history(ksh93u+) back in place, restarting ksh(2020) leads again to the reported behaviour with dysfunctional hist. 

so empirically the situation is that ksh2020 does not work with a ksh93u+ generated .sh_history which ksh93u+ itself handles just fine. question would be: what has changed in the history handling code?

> So either this is a corner case that triggers a bug or your ~/.sh_history is corrupt. Note that both ksh93u+ and the current version incorrectly handle hist when there is no ~/.sh_history when the shell was started. I see <81>^Ahist in my editor. So clearly there are bugs in this code.

my .sh_history seems to be just fine since it is handled correctly by ksh93u+. but I can confirm that .sh_history is always created with a leading <81>^A sequence in both versions. I did not realise that this is a bug (is it, really, or is there a reason for this sequence in the old code?).

> @jghub Are you able and willing to build ksh from source? This requires having Meson, Ninja, and a C compiler installed but little else. If so I can provide a patch that adds diagnostic DPRINTF() statements that should help identify the source of the bug.

will do if necessary and helpful. just let me know. a q&d test showed also the following: putting a copy of the original .sh_history in place and deleting either first half or second half of entries [2, N-1] -- i.e. keeping first and last line in place -- both(!) yield a .sh_history which is recognized by ksh(2020) correctly.  this seems to prove that none of the entries is "corrupt". the only remaining explanation seems the total number of entries (~ 1500 lines) in the original .sh_history.  but that sure should not trigger some limit in ksh(2020), no?

**Comment by krader1961** [comment]
I have reproduced this problem. There is nothing special about either the number of commands in the history or the size of the file. Removing a single character "fixes" the problem; e.g., `echo 23` to `echo 2`. In my case the problematic *~/.sh_history* file has a total of 1712 lines and 1704 commands and a total size of 20483 bytes. Running `hist -l` produces the error `ksh: hist: 1-0: invalid range`.

**Comment by jghub** [comment]
just for completeness: my .sh_history is at about 1500 lines and 27000 bytes. furthermore, in my case it definitely is *not* sufficient to delete a single character to "fix" the problem. rather, as I wrote earlier, I only could make it work by removing quite some lines: cutting down to 1177 lines and 20471 bytes did not suffice while cutting down to 1176 lines and 20445 bytes made it work. the number of bytes looks at least conspicuously similar to your figure. whether it matters -- I can't say.

**Comment by krader1961** [comment]
The reason for this bug is a stupid mistake on my part. It was introduced by the fix for issue #1271. The fix is trivial. Sadly this bug was included in the 2020.0.0 release so I've created a 2020.0.1 branch that cherry-picks the fix since we'll probably need to do a bug fix release before the next minor release. As usual, this bug exists because the code is too clever by half and doesn't properly validate function arguments. Or, alternatively, too many places take advantage of undocumented behavior.

**Comment by paulfloyd** [comment]
Just for info, I'm also seeing this on FreeBSD ksh93 Version A 2020.0.0

**Comment by jghub** [comment]
@paulfloyd:
ksh2020 has known problems (this special bug indeed made it into the ksh2020 "stable" release...) and the project is currently in a state of readjustment, see #1466.

it seems, FreeBSD will again provide the last official stable release (ksh93u+) beside or instead of ksh2020 soon (which was unfortunately not the case in the meantime I have been told?)  but to make sure you might consider to mail the ksh port maintainer of the FreeBSD project.
