### ISSUE TITLE
Crash on `typeset -f` (or: `functions`)

### ISSUE THREAD

**Issue by 0branch** [att/ast#1436]
**Description of problem:**
`ksh` crash on `typeset -f` (or: `functions`).

**Ksh version:**
`2020.0.0-beta1-159-g4a438e51`.

**How reproducible:**
Consistently. 

**Steps to reproduce:**
1. Run `ksh` (or `ksh -p` to ensure user profile suppression)
2. Type `functions` (or `typeset -f`), hit return
3. Observe crash

**Actual results:**

    $ functions
    ### 12114 Function backtrace:
    1   handle_sigsegv (in ksh) + 11
    2   _sigtramp (in libsystem_platform.dylib) + 29
    3   0x0
    4   print_scan (in ksh) + 621
    5   setall (in ksh) + 3755
    6   b_typeset (in ksh) + 2554
    7   sh_exec (in ksh) + 14823
    8   exfile (in ksh) + 1425
    9   sh_main (in ksh) + 1903
    10  start (in libdyld.dylib) + 1
    11  0x00000002 (in ksh)
    Abort trap: 6

**Expected results:**
The defined function list displayed on standard output.

**Additional info:**
Here's an `lldb` session (macOS 10.14.6):

    (lldb) target create "./builds/ast/bld/bin/ksh"
    (lldb) target create ./builds/ast/bld/bin/ksh
    Current executable set to './builds/ast/bld/bin/ksh' (x86_64).
    (lldb) run -p -x
    Process 11072 launched: '/Users/me/builds/ast/bld/bin/ksh' (x86_64)
    + __fpath=/Users/me/builds/ast/bld/share/ksh/functions
    + [[ -z '' ]]
    + FPATH=/Users/me/builds/ast/bld/share/ksh/functions
    + basename /Users/me/builds/ast/bld/share/ksh/functions/_cd
    + typeset -fu _cd
    + basename /Users/me/builds/ast/bld/share/ksh/functions/_ksh_print_help
    + typeset -fu _ksh_print_help
    + basename /Users/me/builds/ast/bld/share/ksh/functions/dirs
    + typeset -fu dirs
    + basename /Users/me/builds/ast/bld/share/ksh/functions/man
    + typeset -fu man
    + basename /Users/me/builds/ast/bld/share/ksh/functions/mcd
    + typeset -fu mcd
    + basename /Users/me/builds/ast/bld/share/ksh/functions/popd
    + typeset -fu popd
    + basename /Users/me/builds/ast/bld/share/ksh/functions/pushd
    + typeset -fu pushd
    + _push_max=32
    + typeset -li _push_max
    + _push_top=32
    + typeset -li _push_top
    + typeset -a _push_stack
    + [[ imsxBE = *i* ]]
    + [[ -f /Users/me/builds/ast/bld/share/ksh/functions/_cd ]]
    + unalias cd
    + 2> /dev/null
    + alias cd=_cd
    + unset __fpath
    $ + tput cuu1
    + 2> /dev/null
    + .sh.subscript=$'\E[A'

    $ functions
    + typeset -f
    Process 11072 stopped
    * thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x20)
        frame #0: 0x00000001000191ca ksh`print_namval(file=0x000000010016e028, np=0x0000000100302de0, omit_attrs=false, tp=0x00007ffeefbfe2d0) at typeset.c:788:62
       785 	            } else if (tp->sh->gd->hist_ptr) {
       786 	                iop = (tp->sh->gd->hist_ptr)->histfp;
       787 	            }
    -> 788 	            if (iop && sfseek(iop, FETCH_VT(np->nvalue, rp)->hoffset, SEEK_SET) >= 0) {
       789 	                sfmove(iop, file, nv_size(np), -1);
       790 	            }
       791 	            if (fname) sfclose(iop);
    Target 0: (ksh) stopped.

A similar crash (abort trap) was encountered on OpenBSD.

**Comment by krader1961** [comment]
Note that this **only happens** in an interactive shell. Doing `ksh -c functions` produces the expected output.

**Comment by krader1961** [comment]
This bug was introduced, or exposed, by my first change to using Sphinx/RST for documentation and `getopt_long()` rather than `optget()`. **Note:** this is only indirectly due to commit fa9673c6. The real cause appears to be the introduction of function scripts run when the shell starts.

**Comment by 0branch** [comment]
Thanks again for taking a look @krader1961.

**Comment by krader1961** [comment]
This happens in interactive shells because this is true:

https://github.com/att/ast/blob/ffbfaf6ff4fd0cb37505b78b02cb1af9eac04eb2/src/cmd/ksh93/bltins/typeset.c#L786-L787

Which causes this statement to dereference a NULL pointer:

https://github.com/att/ast/blob/ffbfaf6ff4fd0cb37505b78b02cb1af9eac04eb2/src/cmd/ksh93/bltins/typeset.c#L788

The Namval_t refers to the autoloaded `_cd` function. Which, unsurprisingly, should have its `struct Ufunction *rp;` be a non-NULL pointer. TBD

**Comment by krader1961** [comment]
Unsurprisingly the output of `functions` is broken:

```
typeset -fu _cdtypeset -fu _ksh_print_helptypeset -fu dirstypeset -fu mantypeset -fu mcdtypeset -fu popdtypeset -fu pushdKSH
```

It is unclear if this bug is related to this issue but I happened to notice it while debugging the issue.

**Comment by krader1961** [comment]
FYI, This has been broken since August 2018 (i.e., more than a year) by my commit 0e41b07c. The `FETCH_VT(np->nvalue, rp)` pointer is NULL when a function is marked to be autoloaded but has not actually been loaded. Fix already made I just need to add a regression test before pushing it upstream.

**Comment by 0branch** [comment]
Thanks @krader1961.
