### ISSUE TITLE
Dead links in web site's resources section

### ISSUE THREAD

**Issue by ryandesign** [att/ast#1440]
**Description of problem:**

The [resources section of the web site](http://kornshell.com/resources/) has a link to pdksh. That link is 404 not found.

I am assuming that pdksh is no longer interesting and that people who were using pdksh should be using ksh now, so the link could probably just be removed.

**Comment by ryandesign** [comment]
While we're there, the links to UNIX KornShell Memento, Bash FAQ, Zsh FAQ, and Dtksh Documentation don't work either because the server is not found.

**Comment by krader1961** [comment]
Sadly, we don't have ownership or control of kornshell.com. I believe Siteshwar has reached out to ~djk about transferring ownership without getting a response.  Closing this issue since there is nothing we can do. If and when we have the ability to update that site we'll take care of these issues.

**Comment by ryandesign** [comment]
Ah yes, after filing this I noticed the very old djk copyright date on the web site. A pity there is a well-known web site about this software that does not reflect its current state. Note that the [Wikipedia article about ksh](https://en.wikipedia.org/wiki/KornShell) has an info box that seems to give equal weight to a link to this GitHub repository and a link to that web site. This may continue to confuse users.
