### ISSUE TITLE
BUG: ${parameter^pattern} etc. causes syntax error although documented in manpage

### ISSUE THREAD

**Issue by jghub** [att/ast#1450]
**Description of problem:**

BUG: ${parameter^pattern} etc. cause syntax error.
      ${parameter^pattern}
       ${parameter^^pattern}
       ${parameter,pattern}
       ${parameter,,pattern}

are 93v- features which were at least partially functional in the 93v- beta at the time.

**Ksh version:**

2020 release. also in commit 42a580c5

**Steps to reproduce:**
x=abc
print ${x^a}

**Actual results:**

syntax error

**Expected results:**

x set to 'Abc'

**Comment by kshfan** [comment]
As seen here, originally:
https://groups.google.com/d/msg/korn-shell/GMNHiyGN31s/GgNSm7pGAgAJ

**Comment by jghub** [comment]
sorry, might better have provided that link myself...

**Comment by krader1961** [comment]
This is a consequence of our misguided, in hindsight, decision to base this work on the ksh93v- release rather than the last stable release, ksh93u+. This behavior depends on BASH emulation being enabled. Something we've disabled for a couple of reasons. We explicitly included one BASH behavior, the `local` keyword (see https://github.com/att/ast/issues/220) without requiring the bogus BASH emulation feature controlled by the `BASH_OPT` build time option.

Like the "local" keyword I'm more than happy to enable this specific bash compatibility feature even if the shell was invoked as "ksh" rather than "bash".  But note that doing so is not backward compatible with ksh93u+.

P.S., I'm curious why you see this as a problem given earlier comments which imply you believe any new ksh release must be 100% compatible with ksh93u+ from seven years ago. The current behavior is ksh93u+ compatible. The fact we haven't updated the ksh man page is just a consequence of too few people contributing changes or reviewing issues and pull-requests.

**Comment by kshfan** [comment]
> P.S., I'm curious why you see this as a problem given earlier comments which imply you believe any new ksh release must be 100% compatible with ksh93u+ from seven years ago. The current behavior is ksh93u+ compatible. The fact we haven't updated the ksh man page is just a consequence of too few people contributing changes or reviewing issues and pull-requests.

That's one big strawman argument.  I don't think he or I (or anyone I can think of off the top of my head) have a problem with having new features added to ksh, regardless of the source of those features.  Speaking for myself, I only care when new bugs emerge that break things in surprising ways.

**Comment by jghub** [comment]
exactly. we were talking about the importance of backward compatibility. syntactically correct ksh93u+ programs/scripts need to produce the results they always did.  the present bug is a different problem. that should be obvious, I'd say.

I am also sure there are some subtle backward incompatible changes in 93v- vs. 93u+. and I am sure those will be then explicitly and in detail  explained in the 93v- changelog. the point here being that some "micro-surgery" going on from release to release is natural but changing stuff indiscriminately and ad hoc (cd, _cd, mcd ...) because it seems a "good idea" to you is something else completely.

I believe it is this what disturbs people like me: your indifference to the importance of these aspects. maintaining backward compatibility (and performance!) while treading carefully. but that appeal has futilely been raised, too, very early during this project, as I see in the archive. so, pointless, obviously, to  repeat it here. -- this here is a bug report of a feature that should work according to manpage and does not. that's all.

**Comment by jghub** [comment]
>Like the "local" keyword I'm more than happy to enable this specific bash compatibility feature even if the shell was invoked as "ksh" rather than "bash". But note that doing so is not backward compatible with ksh93u+.

for the record: my ksh93v- does know of the feature while being called as ksh. the manpage does not signal it as a feature of bash compatibility mode but as a general one.

**Comment by jghub** [comment]
and also for the record: in Version ABIJM 93v- 2014-12-24 (that's the one who's binary I have available) the feature is _not_ bug free (it only works partially). so just activating it again (if I get you right) will not do the trick, probably.

**Comment by siteshwar** [comment]
> This behavior depends on BASH emulation being enabled.

It did not depend on bash emulation being enabled.

@jghub This was previously discussed in #417 and it was reverted by me through [this commit](https://github.com/att/ast/commit/fffe1d92b6c2d0038b844ca5806a5d0421302779). Unfortunately some traces of it are still left in documentation. We had decided to disable some features that were enabled in `ksh93v-` release as they were broken and not properly tested by previous maintainers.

**Comment by jghub** [comment]
@siteshwar 
understood. I know that the feature was broken in ksh93v-. but fixing it would be the better solution, obviously... in any case if it is removed the manpage must be adjusted. has this now been done?

**Comment by siteshwar** [comment]
> @siteshwar
> understood. I know that the feature was broken in ksh93v-. but fixing it would be the better solution, obviously... in any case if it is removed the manpage must be adjusted. has this now been done?

I have removed description of `^` and `,` operators through https://github.com/att/ast/commit/ca8c7e6d881aedb060a3ddba69ab185f59107020
