### ISSUE TITLE
Building on NetBSD 9 arm64 error

### ISSUE THREAD

**Issue by DoktorCranium** [att/ast#1451]
ninja -C build
ninja: Entering directory `build'
[0/195] Compiling C object 'src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c[1/195] Compiling C object 'src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c.o'.
FAILED: src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c.o 
cc -Isrc/lib/libast/tests/misc/258ceee@@optget_long@exe -Isrc/lib/libast/tests/misc -I../src/lib/libast/tests/misc -I. -I../ -Isrc/lib/libast/tests/misc/.. -I../src/lib/libast/tests/misc/.. -I../src/lib/libast/tests/misc/../../include/ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -g -D_GNU_SOURCE -fno-strict-aliasing -Wextra -Wno-attributes -Wno-char-subscripts -Wno-sign-compare -fno-omit-frame-pointer -Werror=implicit -fno-inline -U_FILE_OFFSET_BITS -DUSE_SPAWN=0 -DGCC_4_1PLUS_64_BIT_MEMORY_ATOMIC_OPERATIONS_MODEL=1 -MD -MQ 'src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c.o' -MF 'src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c.o.d' -o 'src/lib/libast/tests/misc/258ceee@@optget_long@exe/optget_long.c.o' -c ../src/lib/libast/tests/misc/optget_long.c
../src/lib/libast/tests/misc/optget_long.c: In function '_test_getopt_long':
../src/lib/libast/tests/misc/optget_long.c:130:21: error: 'getopt_long_only' undeclared (first use in this function); did you mean 'optget_long_only'?
         long_only ? getopt_long_only : getopt_long;
                     ^~~~~~~~~~~~~~~~
                     optget_long_only
../src/lib/libast/tests/misc/optget_long.c:130:21: note: each undeclared identifier is reported only once for each function it appears in
../src/lib/libast/tests/misc/optget_long.c: In function 'check_for_getopt_long_only_bug':
../src/lib/libast/tests/misc/optget_long.c:477:10: error: implicit declaration of function 'getopt_long_only'; did you mean 'test_long_only'? [-Werror=implicit-function-declaration]
     rv = getopt_long_only(argc, argv, "+:v", long_opts, NULL);
          ^~~~~~~~~~~~~~~~
          test_long_only
cc1: some warnings being treated as errors
[3/195] Generating version.c with a custom command.
ninja: build stopped: subcommand failed.
bash-5.0$ 
bash-5.0$ 
bash-5.0$ 
bash-5.0$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/lto-wrapper
Target: aarch64--netbsd
Configured with: /usr/src/tools/gcc/../../external/gpl3/gcc/dist/configure --target=aarch64--netbsd --enable-long-long --enable-threads --with-bugurl=http://www.NetBSD.org/Misc/send-pr.html --with-pkgversion='NetBSD nb3 20190319' --with-system-zlib --without-isl --enable-__cxa_atexit --enable-libstdcxx-time=rt --enable-libstdcxx-threads --with-diagnostics-color=auto-if-env --enable-fix-cortex-a53-835769 --enable-fix-cortex-a53-843419 --with-default-libstdcxx-abi=new --with-mpc-lib=/var/obj/mknative/evbarm-aarch64/usr/src/external/lgpl3/mpc/lib/libmpc --with-mpfr-lib=/var/obj/mknative/evbarm-aarch64/usr/src/external/lgpl3/mpfr/lib/libmpfr --with-gmp-lib=/var/obj/mknative/evbarm-aarch64/usr/src/external/lgpl3/gmp/lib/libgmp --with-mpc-include=/usr/src/external/lgpl3/mpc/dist/src --with-mpfr-include=/usr/src/external/lgpl3/mpfr/dist/src --with-gmp-include=/usr/src/external/lgpl3/gmp/lib/libgmp/arch/aarch64 --enable-tls --disable-multilib --disable-libstdcxx-pch --build=aarch64--netbsd --host=aarch64--netbsd --with-sysroot=/var/obj/mknative/evbarm-aarch64/usr/src/destdir.evbarm
Thread model: posix
gcc version 7.4.0 (nb3 20190319) 
bash-5.0$ uname -a
NetBSD arm64 9.0_RC1 NetBSD 9.0_RC1 (GENERIC64) #0: Wed Nov 27 16:14:52 UTC 2019  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/evbarm/compile/GENERIC64 evbarm

**Comment by krader1961** [comment]
Does NetBSD not provide a `getopt_long_only()` function? Does using it require including a header other than `<getopt.h>` or defining a preprocessor symbol? This builds and runs fine on FreeBSD and OpenBSD. I found this [bug report](http://gnats.netbsd.org/48320) which implies that function isn't available on NetBSD but that bug report is six years old. If it still isn't available it is trivial to wrap the problematic test code in a `#if !defined(__NetBSD__)` block or equivalent.

P.S., I'm assuming you're building from `master` branch head since this code doesn't exist in the 2020.0.0 branch.

**Comment by DoktorCranium** [comment]
Sorry for getting back late .. This is what I dug up about getop_long_only()
     The getopt_long() and getopt_long_only() functions	first appeared in the
     GNU libiberty library.  The first BSD implementation of getopt_long() ap-
     peared in NetBSD 1.5, the first BSD implementation of getopt_long_only()
     in OpenBSD 3.3.  FreeBSD first included getopt_long() in FreeBSD 5.0,
     getopt_long_only() in FreeBSD 5.2. 

This comes directly from https://www.freebsd.org/cgi/man.cgi?query=getopt_long_only&apropos=0&sektion=3&manpath=FreeBSD+7-current&format=html     Since this is FreeBSD related it really seems that it was removed from NetBSD in the past .. 
http://lists.llvm.org/pipermail/lldb-commits/Week-of-Mon-20150831/022054.html
