### ISSUE TITLE
-Dfallback-version-number doesn't affect output of ksh --version

### ISSUE THREAD

**Issue by ryandesign** [att/ast#1456]
**Description of problem:**

The output of `ksh --version` is not affected by the value of `-Dfallback-version-number` set at build time; I had expected that it would be. (Is that expectation wrong?)

**Ksh version:**
Latest git master as of now (031d73aa4a672858716979f5f697e10ce8b6729e)

**How reproducible:**
Always

**Steps to reproduce:**
1. Specify `-Dfallback-version-number=something` while running meson, then build

**Actual results:**
```
$ ksh --version
  version         sh (AT&T Research) 2020.0.0
```

**Expected results:**
I expected `something` to be visible in that string somewhere.

**Additional info:**
The variable `$KSH_VERSION` is updated with `something`.

**Comment by krader1961** [comment]
>  I had expected that it would be. (Is that expectation wrong?)

As the name implies that is the fallback value and will only be used if meson can't figure out the correct version. Which means that either there is no `git` command available or the *.git* directory isn't present.

Also, please note you can't assign an entirely arbitrary string; i.e., the literal `something` isn't legal. It has to be a valid semantic version optionally followed by additional information; e.g., `2020.0.99-something`.

**Comment by krader1961** [comment]
Also, the `--fallback-version-number` flag is only meant to be used in the context of something like a source tarball/rpm/dpkg where you don't want all the baggage of the Git metadata and don't want to require `git` as a dependency to build `ksh`.

**Comment by ryandesign** [comment]
> As the name implies that is the fallback value and will only be used if meson can't figure out the correct version. Which means that either there is no `git` command available or the _.git_ directory isn't present.

Right, that is the case.

> Also, please note you can't assign an entirely arbitrary string; i.e., the literal `something` isn't legal. It has to be a valid semantic version optionally followed by additional information; e.g., `2020.0.99-something`.

Right, let's assume that's what I'm actually specifying.

> Also, the `--fallback-version-number` flag is only meant to be used in the context of something like a source tarball/rpm/dpkg where you don't want all the baggage of the Git metadata and don't want to require `git` as a dependency to build `ksh`.

Correct.

**Comment by krader1961** [comment]
> Right, that is the case.

@ryandesign Are you saying that `-Dfallback-version-number` doesn't work for you when there isn't any Git metadata? Because it works for me:

```
$ mv .git .git.x
$ rm -rf build
$ mkdir build
$ cd build
$ meson -Dfallback-version-number=2666.11.22-wtf
$ ninja
$ src/cmd/ksh93/ksh -c 'print $KSH_VERSION; print $((KSH_VERSION))'
2666.11.22-wtf
26661122
```

**Comment by ryandesign** [comment]
I'm saying that the `$KSH_VERSION` variable is affected by `-Dfallback-version-number`, but the output of `ksh --version` isn't.

**Comment by krader1961** [comment]
This is because the version string written by `ksh --version` is derived from the `sh_optksh_mini` C var. That var used to be populated by the revision control system but is now a hardcoded string (see *./cmd/ksh93/docs/ksh_mini.1*). The `optget()` API handles the `--version` flag by scanning that C var for magic tokens. It's on my TODO list to fix that by eliminating the two remaining uses of `optget()`. Those two uses are because the borg standard `getopt_long()` can't handle the CLI of the `ksh` or `typeset` commands. I've already replaced all the other uses of `optget()` with `optget_long()`. The latter being the new API for parsing args meant to mimic `getopt_long()` but with extensions needed by ksh.

It might be a couple of months before I complete the work of replacing `optget()` with `optget_long()`. In the mean time I'll explore whether there is a trivial way to replace the hardcoded `2020.0.0` string with whatever version would be used. However, the straightforward replacement might be problematic since it would mean that `2666.11.22-wtf` would appear where the simple date `2666.11.22` would appear today. This is a non-issue for any official, stable, release but could be a problem for an unofficial release that includes extra info after the semantic version.

**Comment by krader1961** [comment]
> ...but could be a problem for an unofficial release that includes extra info after the semantic version.

Actually, that's now a non-issue. When switching to semantic versioning @siteshwar and myself discussed this extensively. We concluded that replacing something like `93v- 2014-12-24` in the `ksh--version` output with just the semantic version, `2014.12.24`, was fine as that string is really only usable by a human. So replacing the current hardcoded value with the same string as `$KSH_VERSION` is fine.

**Comment by krader1961** [comment]
Also, notice that the `ksh --version` and `ksh -c 'print $KSH_VERSION'` strings are different where most people would expect them to be identical:

```
$ /bin/ksh -c 'print $KSH_VERSION; print $((KSH_VERSION))'
Version AJM 93u+ 2012-08-01
20120801
$ /bin/ksh --version                                                    29 ms
  version         sh (AT&T Research) 93u+ 2012-08-01
```

That difference is a consequence of the output of `ksh --version` being produced by the `optget()` astlib API whereas `print $KSH_VERSION` is produced by ksh specific code. Which is exhibit 666 for why I hate the `optget()` API. My planned replacement of `optget()` with the new `optget_long()` will cause those two use cases to produce identical output.

**Comment by krader1961** [comment]
I wonder how many people know that the `--version` flag is supported by nearly every ksh builtin, as a consequence of `optget()` behavior, and what the output means. From a ksh93u+ binary:

```
$ /bin/ksh --version
  version         sh (AT&T Research) 93u+ 2012-08-01
$ /bin/ksh
KSH PROMPT:1: echo $KSH_VERSION
Version AJM 93u+ 2012-08-01
KSH PROMPT:2: set --version
  version         set (AT&T Research) 1999-09-28
KSH PROMPT:3: typeset --version
  version         typeset (AT&T Research) 2010-12-08
KSH PROMPT:4: print --version
  version         print (AT&T Research) 2008-11-26
```

**Comment by krader1961** [comment]
@ryandesign, I'm wondering if you are now satisfied that `ksh --version` produces the output you expect.

**Comment by ryandesign** [comment]
Thank you, yes. Mind you, my expectations are not always to be trusted. I don't use ksh, I'm just the guy who maintains the ksh ports in MacPorts. It was reported to us that a user had installed our ksh-devel port and was then unable to determine which commit of ksh had been installed, so I've been trying to make that easier to see. With this latest update, the output of `port installed ksh-devel`, `ksh --version`, and `echo $KSH_VERSION` (while in ksh) should all show the commit date and the commit hash, so hopefully that will make our users happy.
