### ISSUE TITLE
new organization name

### ISSUE THREAD

**Issue by jelmd** [att/ast#1470]
Choices:

* KornShell

* kornshell

* KornShell-Community

* kornshell-community

* kornshell.plus

* KornShell93

* kornshell93

* KornShellCommunity

* kornshellcommunity

* ksh-ast

* ksh-community

* ksh-team

* ksh93u++

* KSHland

* kshland

* KSHlang

* kshlang

* KSHreload

* kshreload

* TheKornShell

* thekornshell

231 points. Max. 21/name.

**Comment by jghub** [comment]
n*(n+1)/2 points -- you make this tough... I do hope not exhausting the points account is permitted by the game's rules :).

```
> Choices:
> 
> * KornShell                      20
> * kornshell
> * KornShell-Community            21
> * kornshell-community
> * kornshell.plus
> * KornShell93                     18
> * kornshell93
> * KornShellCommunity .            19
> * kornshellcommunity
> * ksh-ast                         17
> * ksh-community                   16
> * ksh-team                        15
> * ksh93u++
> * KSHland
> * kshland
> * KSHlang
> * kshlang                         14
> * KSHreload
> * kshreload
> * TheKornShell                    13
> * thekornshell
> 
```
> 231 points. Max. 21/name.

but I could live with other proposals as well except ksh93u++ since @marcastel is right that it has a wrong connotation ;)

**Comment by jens-maus** [comment]
```
> * KornShell                  21
> * kornshell                  21
> * KornShell-Community        17
> * kornshell-community        17
> * kornshell.plus
> * KornShell93
> * kornshell93
> * KornShellCommunity         19
> * kornshellcommunity         19
> * ksh-ast
> * ksh-community              18
> * ksh-team                   18
> * ksh93u++
> * KSHland
> * kshland
> * KSHlang
> * kshlang
> * KSHreload
> * kshreload
> * TheKornShell               20
> * thekornshell               20
```

**Comment by jelmd** [comment]
```
> * KornShell               10
> * kornshell               21
> * KornShell-Community
> * kornshell-community
> * kornshell.plus
> * KornShell93
> * kornshell93
> * KornShellCommunity
> * kornshellcommunity
> * ksh-ast                 20
> * ksh-community            9
> * ksh-team                19
> * ksh93u++
> * KSHland
> * kshland
> * KSHlang
> * kshlang                  8
> * KSHreload
> * kshreload
> * TheKornShell             6
> * thekornshell             7
```

**Comment by dannyweldon** [comment]
I am not voting very highly because I am undecided which ones are the best.

KornShell
kornshell 10
KornShell-Community
kornshell-community 10
kornshell.plus
KornShell93
kornshell93
KornShellCommunity
kornshellcommunity 10
ksh-ast
ksh-community 10
ksh-team 
ksh93u++
KSHland
kshland
KSHlang
kshlang
KSHreload
kshreload
TheKornShell
thekornshell

**Comment by cschuber** [comment]
ksh-community or some name with community in it makes sense.

**Comment by jelmd** [comment]
@cschuber, feel free to vote - ksh-community is already in the list - [see voting details](https://github.com/att/ast/issues/1466#issuecomment-585611425)

**Comment by saper** [comment]
This is not only about ksh. A whole AST repository is there with some other tools. `INIT` defines the following "packages":

* ast-base
* ast-ksh
* ast-make
* ast-open
* INIT

**Comment by marcastel** [comment]
@saper You are totally right. However -- and this is my understanding, the objective is to perpetuate the KornShell and not the whole AST ecosystem.

Obviously you raise the point of the dependency of the KornShell on that ecosystem. And that has to be addressed. In particular from a licensing standpoint. We will probably end up with multiple licenses ... one for the executable, one for the libraries and possibly yet another one for the tools that make up the build system.

Since this repository is the legacy vault of a terminated development, all required AST components will most probably be maintained in the new organisation alongside the KornShell.

So the vote here is really about the KornShell not about AST.

**Comment by aweeraman** [comment]
* KornShell                  
* kornshell - 21
* KornShell-Community
* kornshell-community - 18
* kornshell.plus
* KornShell93
* kornshell93
* KornShellCommunity         
* kornshellcommunity         
* ksh-ast
* ksh-community - 18
* ksh-team - 20
* ksh93u++
* KSHland
* kshland
* KSHlang
* kshlang
* KSHreload
* kshreload
* TheKornShell               
* thekornshell

Also, proposing:

* korn-shell - 21

**Comment by cschuber** [comment]
But we should have community in the name to denote that this is community driven not sponsored by some large company.

**Comment by cschuber** [comment]
@marcastel, would it be fine if some (not all) people on the new project were interested in perpetuating the AT&T INIT? My thinking is that in a volunteer project, which I assume this will become, people will work on whatever interests them, kind of like what we do on the FreeBSD project. Unless of course there's conflict, when core or the steering committee arbitrates or makes a final decision.

**Comment by marcastel** [comment]
@cschuber INIT is required to bootstrap and build the KornShell. Consequently it is within the scope of the new organisation. And I, for one, am particularly attentive to and supportive of anyone interested in perpetuating INIT and ast-make  :smiley:

**Comment by jelmd** [comment]
- Please use this issue for voting, only.
- The name list got closed on 2020-02-14 00:00:00 UTC.
- Voting continues 'til 2020-02-15 00:00:00 UTC. You may edit your current voting at any time. However, if it has a timestamp > the given time, it gets not counted.

**Comment by cschuber** [comment]
- ksh-community
- ast-community

**Comment by jelmd** [comment]
@cschuber, so I guess 21 points for both of your choices?

Actually the name list is already closed (since 2020-02-14 00:00:00 UTC), so ast-community is not on the list. If you have very strong feelings for it, I think we should be flexible enough to extend list finalization and voting another day. But I guess, it would not really change anything anyway. So I prefer to keep the list as is, so that we can get to work before the weekend starts. Is this ok for you?

BTW: Same thing for @aweeraman's korn-shell suggestion.

**Comment by marcastel** [comment]
| Organisation name         | Vote |
| ------------------------- | ---: |
| KornShell                 |   21 |
| kornshell                 |   21 |
| KornShell-Community       |   14 |
| kornshell-community       |   14 |
| kornshell.plus            |    - |
| KornShell93               |    - |
| kornshell93               |    - |
| KornShellCommunity        |   14 |
| kornshellcommunity        |   14 |
| ksh-ast                   |    - |
| ksh-community             |    7 |
| ksh-team                  |    - |
| ksh93u++                  |    - |
| KSHland                   |    - |
| kshland                   |    - |
| KSHlang                   |    7 |
| kshlang                   |    7 |
| KSHreload                 |    - |
| kshreload                 |    - |
| TheKornShell              |    6 |
| thekornshell              |    6 |

I didn't distribute the full 231 pts as this hasn't been followed.

**Comment by jelmd** [comment]
Final results:

Name|Place|Points|@jghub|@jens-maus|@jelmd|@dannyweldon|@aweeraman|@marcastel
---|:---:| :---:|:---:|:---:|:---:|:---:|:---:|:---:
KSHland | 21 | 0 |   0 |  0 |  0 |  0 |  0 |  0
KSHreload | 20 | 0 |   0 |  0 |  0 |  0 |  0 |  0
kornshell.plus | 19 | 0 |   0 |  0 |  0 |  0 |  0 |  0
kornshell93 | 18 | 0 |   0 |  0 |  0 |  0 |  0 |  0
ksh93u++ | 17 | 0 |   0 |  0 |  0 |  0 |  0 |  0
kshland | 16 | 0 |   0 |  0 |  0 |  0 |  0 |  0
kshreload | 15 | 0 |   0 |  0 |  0 |  0 |  0 |  0
KSHlang | 14 | 7 |   0 |  0 |  0 |  0 |  0 |  7
KornShell93 | 13 | 18 |  18 |  0 |  0 |  0 |  0 |  0
kshlang | 12 | 29 |  14 |  0 |  8 |  0 |  0 |  7
thekornshell | 11 | 33 |   0 | 20 |  7 |  0 |  0 |  6
ksh-ast | 10 | 37 |  17 |  0 | 20 |  0 |  0 |  0
kornshellcommunity | 9 | 43 |   0 | 19 |  0 | 10 |  0 | 14
TheKornShell | 8 | 45 |  13 | 20 |  6 |  0 |  0 |  6
KornShell-Community | 7 | 52 |  21 | 17 |  0 |  0 |  0 | 14
KornShellCommunity | 6 | 52 |  19 | 19 |  0 |  0 |  0 | 14
kornshell-community | 5 | 59 |   0 | 17 |  0 | 10 | 18 | 14
KornShell | 4 | 72 |  20 | 21 | 10 |  0 |  0 | 21
ksh-team | 3 | 72 |  15 | 18 | 19 |  0 | 20 |  0
ksh-community | 2 | 78 |  16 | 18 |  9 | 10 | 18 |  7
kornshell | 1 | 94 |   0 | 21 | 21 | 10 | 21 | 21

**Comment by jelmd** [comment]
@jghub, @jens-maus, @jelmd, @dannyweldon, @aweeraman, @marcastel thanks a lot for your voting.

The winner is **kornshell**. I'll try to contact github support to check, whether it is possible to take it over. If not, we will use the name on the 2nd place, which is **ksh-community** (already reserved by me).

**Comment by jelmd** [comment]
@jghub, @jens-maus, @jelmd, @dannyweldon, @aweeraman, @marcastel: github support answered with "... we won’t be able to release that username for you today. ...". So our new  new child is **ksh-community** :-) . Have fun!!!

**Comment by tailhook46** [comment]
Where is the place, where I can download Kornshell93?
