### ISSUE TITLE
Please fix invalid use of memccpy() on master

### ISSUE THREAD

**Issue by McDutchie** [att/ast#1481]
The official AST master branch should at the very least fix a blatantly invalid use of `memccpy()` on potentially overlapping buffers in the commonly used library function `sfputr()`. See #78. The fix can easily be cherry-picked from commit dda258b6.

On the Mac, this makes various crashes magically vanish.

**Comment by gordonwoodhull** [comment]
This repo is inactive - please see #1466 and https://github.com/att/ast/issues/1464#issuecomment-581159703 onward. 

Please search the web for a maintained version of ksh2020 or ksh93.

**Comment by McDutchie** [comment]
I'm well aware. I think you should make an exception for this one. It's such an easy fix and it solves various crashes.

**Comment by gordonwoodhull** [comment]
Sorry, didn't recognize you. 

Thanks for linking to your active repo - that's one of the reasons we are not archiving this one.

**Comment by lkoutsofios** [comment]
I'll make the change.
I have a couple other fixes too.

lefteris

**Comment by McDutchie** [comment]
Done in d2771913c9b5b81a7e53fc6f164a5fd91643cb85.
