### ISSUE TITLE
`a=()` should make `a` an empty array but doesn't

### ISSUE THREAD

**Issue by sckendall2** [att/ast#1488]
Here's an example:
```
$ a=(); print ${#a[*]}
1
$ print "${a[0]}"
(
)
```
I've duplicated this behavior in Version AJM 93t+ 2010-02-02 in RHEL 5.7 and in Version AJM 93u+ 2012-08-01 (rpm ksh-20120801-252.el8.x86_64) in RHEL 8.0.

The ksh93 man page has a construct _varname_=(_assign_list_) but does not specify the meaning of an empty _assign_list_. I think it's safe to say, though, that the result we see -- a one-element array with element zero having the value left-paren LF right-paren -- is a bug.

The same assignment results in an empty array in recent versions of mksh and in bash. And a variation results in an empty array in ksh93 itself:
```
$ a=($empty); print ${#a[*]}                   
0
```
The only reasonable fix is for `a=()` to result in an empty array, too. And the documentation should be fixed to make that clear.

**Comment by hyenias** [comment]
ksh93u+ defaults` a=();` to a compound variable. For insights try issuing a `typeset -p a` and see [KSH93 Compound Variables](https://blog.fpmurphy.com/2009/01/ksh93-compound-variables_05.html).
```ksh
$ a=(); typeset -p a
typeset -C a=() 
```

**Comment by sckendall2** [comment]
@hyenias, thanks for pointing that out. I think it's an unfortunate feature that `a=()` produces a compound variable. But it's been this way a long time, and I'm not going to argue that it should be changed.
