### ISSUE TITLE
Upstream patches from fedora

### ISSUE THREAD

**Issue by siteshwar** [att/ast#172]
There are a number of patches in fedora [ksh repository](http://pkgs.fedoraproject.org/cgit/rpms/ksh.git/tree/) that should be upstreamed.

**Comment by krader1961** [comment]
Glad you mentioned this now as I was going to embark on reformatting the code and it's easier to merge those patches before that is done. When I applied the Solaris patches quite a few either should not be applied (so I ignored them) or needed manual intervention to apply. I picked one of the Fedora patches at random, http://pkgs.fedoraproject.org/cgit/rpms/ksh.git/tree/ksh-20070328-builtins.patch, and it's pretty clear we don't want to take that one. Whatever we decide regarding issue #129 will determine whether we make such a change.

Is there someone at Redhat who is going to do the work of applying the subset of those patches which we do want to the current state of the project?

**Comment by siteshwar** [comment]
I will look at it.

**Comment by siteshwar** [comment]
@krader1961 It will take me some time to review all the patches, write test cases etc. If you want to reformat the code, go ahead.

**Comment by krader1961** [comment]
@siteshwar, I see you've created a lot of PRs corresponding to the Fedora patches. I'll try to get them reviewed and merged ASAP now that my new Mac Pro workstation/server is (mostly) working. As soon as I've worked through that backlog I intend to start reformatting the code then working on making it easy to run the code through tools like `oclint` and `cppcheck`.

**Comment by siteshwar** [comment]
I have already opened pull requests for most of the patches. I will need little more time for rest of the patches, so it's fine if you want to reformat the code.

**Comment by krader1961** [comment]
Closing since it looks like this has been completed.
