### ISSUE TITLE
Exit status when there is a segfault

### ISSUE THREAD

**Issue by siteshwar** [att/ast#175]
https://github.com/att/ast/commit/47fa1800352570cfc708125261b35db9fa885ee1 was made to fix [bug 1469624](https://bugzilla.redhat.com/show_bug.cgi?id=1469624). However, with the legacy build system we can still see exit status of ```267 (256 + 11)``` when ksh crashes sometimes. We should further investigate this issue.

**Comment by krader1961** [comment]
This turns out to be a quirk of the legacy build system and Meson prior to my [enhancement](https://github.com/mesonbuild/meson/issues/3642). AFAICT there is no ambiguity regarding the exit status due to a SIGSEGV or other signal versus a "normal" exit.
