### ISSUE TITLE
Weird while loop issue

### ISSUE THREAD

**Issue by benalt613** [att/ast#192]
I am using ksh "sh (AT&T Research) 93u+ 2012-08-01" under Cygwin and Windows 7. I am finding that when a while loop is used and a file redirected to it in combination with sqlcmd.exe, it never gets past the 1st line of the file. What I mean:
```
$ cat > state.txt
Minnesota
Ohio
$ # This is fine:
$ while read state; do
>     print $state
> done < state.txt
Minnesota
Ohio
$ # This loops forever outputting "Minnesota" and never reads the next line containing "Ohio":
$ while read state; do 
>     sqlcmd.exe -S $s -P $p -d $d -h-1 -Q "SET NOCOUNT ON; SELECT Name FROM tblClient WHERE Name = '$state' "
> done < state.txt
Minnesota
Minnesota
Minnesota
Minnesota
Minnesota
Minnesota
$ # On its own:
$ sqlcmd.exe -S $s -P $p -d $d -h-1 -Q "SET NOCOUNT ON; SELECT Name FROM tblClient WHERE Name = 'Minnesota' "
Minnesota
$ sqlcmd.exe -S $s -P $p -d $d -h-1 -Q "SET NOCOUNT ON; SELECT Name FROM tblClient WHERE Name = 'Ohio' "
Ohio
$ # Also okay:
$ cat state.txt | while read state; do
>     sqlcmd.exe -S $s -P $p -d $d -s, -I -W -h-1 -Q "SET NOCOUNT ON; SELECT Name FROM tblClient WHERE Name = '$state'"
> done
Minnesota
Ohio
$
```
sqlcmd.exe runs SQL Server Command Line Tool. Options are specified for server, password and database with no header set for the query on the command line. Does this look like a bug? I have only encountered the issue in association with sqlcmd.

Thanks,
Ben

**Comment by dannyweldon** [comment]
It could be that sqlcmd.exe is interfering with the input.  What happens if you do this?

    exec {fd}<state.txt
    while read -u$fd state; do
            sqlcmd.exe -S $s -P $p -d $d -s, -I -W -h-1 -Q "SET NOCOUNT ON; SELECT Name FROM tblClient WHERE Name = '$state'"
    done

Also, perhaps as a non-cygwin console program, it's not working with stdio properly in the cygwin console.

**Comment by benalt613** [comment]
Using exec with read -u resulted in it running properly and as expected. I first noticed the issue as a part of a script. Would this then indicate the issue is with sqlcmd interfering with the input and the only solution is to work around it?

**Comment by krader1961** [comment]
In addition to Danny's workaround it should be sufficient to redirect stdin just for `sqlcmd`; that is:

```
while read state; do
    sqlcmd ... </dev/null
done < state.txt
```

In general you need to be careful with commands that read from stdin if your script of function also reads from stdin.

**Comment by krader1961** [comment]
Also, this doesn't really have anything to do with the `while` loop. Just put the following in a file named *testme* (note the lack of stdin redirection on the `sqlcmd`):

```
read first_state
sqlcmd ...
read second_state
echo first_state=$first_state  second_state=$second_state
```

Then invoke it as `ksh ./testme < state.txt` and you should see the same problem.

**Comment by benalt613** [comment]
Redirecting to /dev/null worked. The testme script though did not show the problem.
```
$ ./testme < state.txt
Minnesota
first_state=Minnesota second_state=Minnesota
```

**Comment by krader1961** [comment]
It's going to depend on how each program performs its I/O (specifically any buffering or repositioning of the fd in the stream).

So to sum up: If you are using the `read` builtin to read from stdin and some other command that also reads from stdin the results can be surprising and unpredictable.
