### ISSUE TITLE
build requires meson

### ISSUE THREAD

**Issue by jwrightecs** [att/ast#196]
is the namake system broken or deprecated?   If not shouldn't the README mention both?

**Comment by krader1961** [comment]
Yes, building ksh now requires Meson since we're moving away from the legacy Nmake build system. Did you have a question or problem to report?

**Comment by krader1961** [comment]
See issue #42 for why we now require Meson to build and test ksh93.

**Comment by krader1961** [comment]
The Nmake (`bin/package`) build system is deprecated and will be removed soon from the ksh93 only tree. We're not going to maintain two ways of building ksh93.
