### ISSUE TITLE
What AST API version should we be using?

### ISSUE THREAD

**Issue by krader1961** [att/ast#218]
Short version:

Why are we using the `20130625` AST API version?

Long version:

While working on restyling the source I noticed this block of code in *src/lib/libast/include/ast.h*:

```
#if ASTAPI(20130913)
// some #define's
#else
// some different #define's
#endif
```

The reason I noticed this is that the "else" block was being used. Which seemed odd. The reason seems to be that we are passing `-D_API_ast=20130625` to the compiler. Whereas the Nmake based build did not do so which results in it apparently defaulting to `99999999`. That is, whatever API version is the newest. I confirmed this by adding a `#error` directive to *src/lib/libast/include/ast.h* to confirm which branch is taken by the compiler.

Note that this is not true when compiling the non-ksh AST code. That is because this line in *src/lib/libast/meson.build* does not have the expected effect:

```
c_args: ['-D_BLD_ast', '-D_API_ast=20130625'],
```

That is because simply defining `_BLD_ast` causes the `ASTAPI()` macro to always default to the latest version. But that symbol is not in the *src/cmd/ksh93/meson.build* file so it uses the 20130625 version.

It looks like the current situation is because the ksh source has not been modified to use a AST API newer than 20130625. @siteshwar, Can you explain what you think should be happening vis-a-vis picking a AST API version? And why we're not building ksh using the most recent AST API version?

P.S., The code involved in deciding which AST API version is active is impenetrable and needs to be reworked so it can be understood by mere mortals.

**Comment by siteshwar** [comment]
@krader1961 I think I picked up the API versions from the ```nmake``` build, but it's possible I might have missed something there. IIRC I was having build failures at some point while using the latest versions of API functions.
