### ISSUE TITLE
bracket test fails due to update to Trusty images in Travis

### ISSUE THREAD

**Issue by siteshwar** [att/ast#227]
Below test is consistently failing on Travis since it has updated Trusty images :
```
	bracket.sh[232]: test -N $tmp/*: st_mtime>st_atime after read
```

afaik it has nothinig to do with the recent changes I have merged into master. All the test cases are passing in docker under Fedora.

**Comment by krader1961** [comment]
I assume you're aware there are a large number of test failures on various platforms. Including the ones I have been using to verify changes such as macOS 10.13, FreeBSD 11.1, and Ubuntu 16.10. I have simply been verifying that a particular change does not increase the number of failures of those platforms. Without regard to whether the change simply replaced one failure with a different failure. My goal is to reformat the code and address compiler and lint tool warnings before spending more time on the failures seen on a specific platform. I did not want to expend energy investigating test failures before that cleanup was completed.

**Comment by siteshwar** [comment]
Yes, I am aware about the test failures. I want to get rid of all the ```iffe``` tests before diving into bugs.

**Comment by krader1961** [comment]
> Yes, I am aware about the test failures. I want to get rid of all the iffe tests before diving into bugs.

My comment was rhetorical but I'm happy to see we are on the same page. Being focused on eliminating a lot of legacy baggage that is no longer relevant is a good thing IMHO. Primarily in the hope that doing so will make it easier to fix bugs and add new features. What I don't understand is the perspective of some commenters (e.g., "jelmd") that modernizing the code is unacceptable.

**Comment by DavidMorano** [comment]
@krader1961 

> What I don't understand is the perspective of some commenters (e.g., "jelmd") that 
> modernizing the code is unacceptable. 

I am only guessing here, but there may be people who have written built-ins which use 
some (or more) functionality from either LIBSHELL or LIBAST (or even some other AST libs)
which might get either broken or missing due to the clean-up efforts.

In a dream world, I think everyone would welcome cleaner and more maintainable code,
but perhaps people fear that some old (and maybe occur) function might get compromised.

Just a guess here (I could be wrong).

**Comment by siteshwar** [comment]
With latest Ubuntu images, file access timestamps are not updated on reads and remounting all partitions with `mount -o remount,atime,strictatime -a` does not fix this failure.

**Comment by siteshwar** [comment]
@krader1961 Do you think it is worth keeping [this test](https://github.com/att/ast/blob/dad63843fc7a5a0010950ad667ecde76effc265f/src/cmd/ksh93/tests/bracket.sh#L314-L315) ? Turning off `noatime` is a recommended performance tweak for Linux systems. In any case, this looks like more of a test case for file system rather than ksh.

**Comment by krader1961** [comment]
Yes, I think those tests, including that specific one, should be kept. They ensure that the implementation isn't comparing the wrong `struct stat` fields. But rather than relying on reading and writing the file to implicitly modify the timestamps I would use `touch` to explicitly modify them.
