### ISSUE TITLE
Compilation failure: undefined symbols or functions in MacOS 10.12

### ISSUE THREAD

**Issue by catull** [att/ast#236]
Cannot build the distribution without the patches under MacOS 10.12.

The first issue is in src/cmd/ksh93/sh/io.c.
Until yesterday, accept4() was defined as accept() with 3 arguments, and the fourth one was ignored.
This builds on MacOS 10.12.

The second issue is the lack of UTIME_NOW and UTIME_OMIT.
Not sure the patch works, it merely jump over statements that use the two symbols.

**Comment by krader1961** [comment]
I already fixed the `accept4()` issue with commit 25f9cf1a. The problem with the UTIME symbols isn't present on macOS 10.13. Can you double-check that on macOS 10.12 those symbols aren't defined as I will be very surprised if they aren't.

**Comment by krader1961** [comment]
By the way, @catull, this project needs more people like you contributing improvements. So regardless of the outcome of this specific issue I hope you will continue to comments or changes to the code.

**Comment by catull** [comment]
@krader1961 
First off, I have not modified any header files in /usr/include.
The OS is macOS 10.12.6 with the latest security patches installed just the other day.

```shell
fgrep -r UTIME_ /usr/include
```

displays ....

```log
/usr/include/php/main/php_config.h:#define HAVE_UTIME_H 1
/usr/include/php/main/php_config.h:#define HAVE_UTIME_NULL 1
/usr/include/php/Zend/zend_virtual_cwd.h:#ifdef HAVE_UTIME_H
/usr/include/tidy/platform.h:  closed first, then set UTIME_NEEDS_CLOSED_FILE to 1.
/usr/include/tidy/platform.h:#ifndef UTIME_NEEDS_CLOSED_FILE
/usr/include/tidy/platform.h:#define UTIME_NEEDS_CLOSED_FILE 1
/usr/include/tidy/platform.h:#define UTIME_NEEDS_CLOSED_FILE 0
/usr/include/time.h:_CLOCK_PROCESS_CPUTIME_ID __CLOCK_AVAILABILITY = 12,
/usr/include/time.h:#define CLOCK_PROCESS_CPUTIME_ID _CLOCK_PROCESS_CPUTIME_ID
/usr/include/time.h:_CLOCK_THREAD_CPUTIME_ID __CLOCK_AVAILABILITY = 16
/usr/include/time.h:#define CLOCK_THREAD_CPUTIME_ID _CLOCK_THREAD_CPUTIME_ID
/usr/include/utime.h:#ifndef	_UTIME_H_
/usr/include/utime.h:#define	_UTIME_H_
/usr/include/utime.h:#endif /* !_UTIME_H_ */
```
As you can see, none of the resulting lines contain `UTIME_NOW` or `UTIME_OMIT`.
The same is true with `accept4`, no resulting line there.

To be fair, I have not read that this project claims to support a specific macOS version range.
So if the policy is that only the most recent "dot version" is supported, I am fine with the status quo.

However, the laptop at work (MacAir book) must NOT be upgraded due to some old software used which only works up to macOS 10.12.x.

C'est la vie.

**Comment by catull** [comment]
For the record, I pulled the latest changes in master just a few minutes ago (commit 5c728883959244dbb92c56dbd787e356a96d41b6).
src/cmd/ksh93/sh/io.c builds, but src/lib/libast/tm/tvtouch.c does not, no surprise.

I suggest to allow the two changes

https://github.com/att/ast/pull/237/commits/d0dbe9d3c02e31059c6c496f2aeff6431fb3455c#diff-aa8396e42dbfcafd64c230cd50c0772cR88

and

https://github.com/att/ast/pull/237/commits/d0dbe9d3c02e31059c6c496f2aeff6431fb3455c#diff-aa8396e42dbfcafd64c230cd50c0772cR153

temporarily.

**Comment by catull** [comment]
Travis build https://travis-ci.org/att/ast/jobs/317977433 failed due to a network error:

```log
Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
```

Can anyone with admin rights restart that build ?

Thanks.

**Comment by siteshwar** [comment]
I restarted the job, but it failed because one of the signal tests failed. But this test is flakey, so it did not fail due to your changes.

**Comment by catull** [comment]
Actually, one test did fail (122 signal).
