### ISSUE TITLE
Remove src/lib/libast/astsa/error.h, it is a trimmed version of src/lib/libast/include/error.h

### ISSUE THREAD

**Issue by catull** [att/ast#253]
The first header file defines a portion of the constants and structs that are already defined in the second header file.

The second one is included everywhere else.

You can see it with the following experiment:

- If the first header file is removed, everything still builds, i.e. compiles and links successfully.
Even after a `ninja -C build -t clean; ninja -C build`.

- The tests produce the same failures as before, on macOS 10.12.6.

Let's see what the result is on the supported platforms.

**Comment by krader1961** [comment]
Merged.
