### ISSUE TITLE
ksh on Linux/musl

### ISSUE THREAD

**Issue by chneukirchen** [att/ast#257]
I'd like to run ksh with the new musl libc.

So far I found three issues:
- `sh/fault.c` uses non-standard `<execinfo.h>` unconditionally, this should be checked by iffe.
  (Just don't install any SIGSEGV handler if this is not found IMO.)
- `libast/vmalloc/malloc.c` uses non-standard mallinfo, which is not provided (not sure why the iffe test for mallinfo succeeds, does it not use `$CC`?), anyway, this function is not used, can just be `ifdef`'d out.
- `comp/conf.tab` unconditionally uses lots of macros which where in POSIX 2004 but not in more recent versions, such as REGEX_VERSION; these should be guarded by `ifdef`.

With this, ksh compiles and runs the test suite pretty well, there are some things related to collation and numeric formatting that musl doesn't implement.

I can provide a patch if you want, but it's probably easier to do for someone who is familiar with the code base.

**Comment by chneukirchen** [comment]
Ok, the second two things are easily avoided by making `bin/libast_prereq.sh` respect `$CC`.

**Comment by siteshwar** [comment]
hmm I will not be a able to take a look at it before next weekend. 

@chneukirchen If you can provide us a patch before that we would be happy to review it.

**Comment by siteshwar** [comment]
@chneukirchen I am able to compile and run it on Alpine Linux which uses musl. Can we close this issue ?

**Comment by chneukirchen** [comment]
Yes, it works now.
