### ISSUE TITLE
Remove support for CRNL line endings

### ISSUE THREAD

**Issue by krader1961** [att/ast#272]
While restyling the code I noticed there is a `SHOPT_CRNL` symbol that conditionally affects how the code behaves. Enabling that on UNIX platforms causes lots of unit test failures. The *src/cmd/ksh93/Makefile* enables the feature conditioned on whether ksh is being built as a native Windows app:

```
if  CC.HOSTTYPE == "win32*"
        SHOPT_CRNL == 1         /* <cr><nl> is eqivalent to <nl> */
end
```

Note that this only affects `ksh` not any of the other code. That includes the "builtin" commands such as `cat` that are strictly speaking not builtins.

Now that even Microsoft has acknowledged that Linux should be embraced with its Windows 10 WSL ("windows subsystem for linux") feature it seems very unlikely we'll ever want to build with this enabled in the future.

Consider that if you create a script with CRNL line endings bash treats the CR as part of the statement and not part of the line ending. If we did enable this feature it should work on both Win32 and UNIX platforms. But treating CRNL line endings as equivalent to NL even on UNIX platforms is risky since it deviates from long standing behavior. Therefore I'm just going to remove that symbol and the code predicated on it.

**Comment by siteshwar** [comment]
Sounds good to me.

**Comment by catull** [comment]
Fully agree; reduces complexity.

**Comment by krader1961** [comment]
It's amazing how much cruft there is in a code base this old. I found this in *src/cmd/ksh93/sh/lex.c*:

```
#if SHOPT_DOS
                if (!(inquote & 1) && sh_lexstates[ST_NORM][n] == 0) break;
#endif /* SHOPT_DOS */
```

That is the only mention of `SHOPT_DOS` anywhere in the project. It's not even in any of the legacy build config files.
