### ISSUE TITLE
Why we should restyle the code and pay attention to compiler/lint tool warnings

### ISSUE THREAD

**Issue by krader1961** [att/ast#273]
Per issue #125 I was restyling *src/cmd/ksh93/sh/lex.c* and noticed the clang compiler reporting this warning:

```
[2/4] Compiling C object 'src/cmd/ksh93/shcomp@exe/sh_lex.c.o'.
../src/cmd/ksh93/sh/lex.c:284:28: warning: '&&' within '||' [-Wlogical-op-parentheses]
        while ((fcgetc(c)) && c == ' ' || c == '\t' || c == '\n') {
               ~~~~~~~~~~~~^~~~~~~~~~~ ~~
../src/cmd/ksh93/sh/lex.c:284:28: note: place parentheses around the '&&' expression to silence this warning
        while ((fcgetc(c)) && c == ' ' || c == '\t' || c == '\n') {
                           ^
               (                      )
```

To @jelmd, @dannyweldon, and everyone else who has expressed misgivings about the modernization I feel is essential please think about the following.

What do you think is the correct behavior of the statement the compiler warned about? Should we suppress the warning by adding parens as suggested by the compiler? The answer is NO, NO, NO! The current logic is wrong. It is pretty obvious the parens belong around the `x || y || z` portion of the condition so that those predicates test the value returned by the most recent `fcgetc()` call. The lack of those parens means the code is not behaving as the author intended.

This is also an example, of which there are thousands, where the ksh programmers tried to do too much in a single statement. Which makes it hard for a mere human to interpret what is intended.

**Comment by krader1961** [comment]
Also, the `fcgetc()` API is FUBAR:

```
#define fcgetc(c)  (((c=fcget()) || (c=fcfill())), c)
```

Notice that it looks like a C function call. It is passed a char/int (not a pointer) and that char/int var is modified as a side-effect of what appears to be a function call. WTF! This is a good example why the code is hard to understand and has so many bugs and unexpected unit test failures.

**Comment by krader1961** [comment]
Also, note that the existing code has an empty `while() { }` block. Which itself is a source of confusion. Changing the code to the following silences the compiler warnings and is somewhat more obvious to a human what is intended:

```
       fcgetc(c);
       while (c == ' ' || c == '\t' || c == '\n') {
           fcgetc(c);
        }
```

I say "somewhat more obvious" because of the non-obvious side effect of the `fcgetc()` statement.

**Comment by dannyweldon** [comment]
Personally, I would just go for this to fix it up, as repeating the `fcgetc()` makes it look like pascal:

    while ((fcgetc(c)) && (c == ' ' || c == '\t' || c == '\n'))
        ;

Also, I believe the code should still work correctly without the extra parentheses because if `fcgetc()` fails, c will be set to EOF, so won't match anything and if it succeeds and is a space, well and good, and if it succeeds and is not a space, it is then checked if it is a tab or a newline.

With the `fcgetc(c)` macro itself, I can understand what you are saying, but perhaps it was done to make the resultant code less cluttered, as it doesn't need brackets around it, eg: `(c=fcgetc())`, as long as you were aware of the side effect, but it probably would have been better defined as (not tested):

    #define fcgetc       ((fcget()) || (fcfill()))

**Comment by krader1961** [comment]
Yeah, upon closer inspection that statement will produce the correct results. But the fact that isn't obvious to an experienced software engineer is a red flag. I'm going to defer changing the `fcgetc()` macro since that's not within the bounds of the code restyling work.

**Comment by krader1961** [comment]
Gah! Here's another block the compiler warns about ("warning: array subscript is of type 'char'"):

```
while ((n = state[ *dp++ = *sp++]) == 0)
    ;
```

It's not obvious from that block alone but the value assigned to `n` is used 177 lines earlier: `while(n) {`. Way too clever.

**Comment by dannyweldon** [comment]
Look, I want to be able to merge individual commits from your branch to another branch that uses nmake and has the whole ast codebase, but if you reformat the code, it will be impossible.

**Comment by krader1961** [comment]
> Look, I want to be able to merge individual commits from your branch to another branch that uses nmake and has the whole ast codebase, but if you reformat the code, it will be impossible.

I understand your concern but that ship has sailed. Even without reformatting the code it will be impossible to merge individual commits to the legacy branches without manual intervention. Simply removing the use of the legacy `iffe` tool does that. Not to mention all the other changes we are making without reformatting the code. Such as removing features that were never included in a public release, are broken (e.g., the code predicated on `SHOPT_FIXEDARRAY`), and are still broken many years later.
