### ISSUE TITLE
UWIN support ?

### ISSUE THREAD

**Issue by catull** [att/ast#284]
[UWIN on Wikipedia](https://en.wikipedia.org/wiki/UWIN) tells us that ...

> UWIN runs best on Windows NT/2000/XP/7 with the file system NTFS, but can run in degraded mode using FAT, and further degraded on Windows 95/98/ME. (See the External link for more details.) A beta version for Windows Vista and 7 is released as UWin 5.0b (June 2011, 17th).[1]

[1] https://web.archive.org/web/20120315010517/https://mailman.research.att.com/pipermail/uwin-users/2011q2/001681.html

It is also open sourced under https://github.com/att/uwin, published almost 2 years ago, with 1 commit labeled "Version: 2012-08-06-master".

The repository does have 17 forks, but no issue and not pull request against it.

Is it being used ?
More importantly, do the pieces of code still need to be maintained ?

When I was a Windows Users, I used Cygwin.
These days, developers can use "Windows Subsystem for Linux".

**Comment by krader1961** [comment]
Yes, we want to remove the UWIN code. Go for it.

P.S., I mentioned doing this in issue #81 where I also talk about removing support for OS personality "universes" such as was found on DYNIX/3 and Solaris.

**Comment by krader1961** [comment]
Commit 5e0009bda5 removed all the UWIN code. The only remaining references are in the legacy build system (soon to be removed) and README's.
