### ISSUE TITLE
Ksh doesn't build on macOS 10.8 (Mountain Lion)

### ISSUE THREAD

**Issue by krader1961** [att/ast#285]
The macOS 10.8 release is only five years old. It should still be possible to build on it. At the moment the meson config step fails:

```
Checking if "posix_spawn exists and it works and its worth using " runs: NO (1)
Library m found: YES
Library iconv found: YES

Meson encountered an error in file src/lib/libast/meson.build, line 215, column 0:
File features/conftab.c does not exist.
```

TBD is what aspect of the feature testing needs to be tweaked.

P.S., It should be possible to build ksh on macOS at least as far back as macOS 10.6 (Snow Leopard) but I don't have that setup for testing. So we'll have to wait to see if anyone tries to build it on that release and reports any problems.

**Comment by siteshwar** [comment]
It looks like some ```iffe``` test failed to execute. You can see it by executing these commands manually :

```
git clean -dfx
bin/setup_cmds.sh
bin/libast_prereq.sh
```

**Comment by krader1961** [comment]
I'm going to close this because there are so many more serious problems. If and when those issues (like #398) are fixed and someone actually using an old version of macOS complains they can't build it a new issue can be opened asking that it be supported. Too, in all likelihood once the other problems involving support for the BSD based operating systems are fixed this issue will probably also be resolved.
