### ISSUE TITLE
Problematic: code implementation inside of sfstrtof.h

### ISSUE THREAD

**Issue by catull** [att/ast#288]
Four C source files include the header mentioned above:
- src/lib/libast/comp/strtold.c
- src/lib/libast/string/strntod.c
- src/lib/libast/string/strntold.c
- src/lib/libast/sfio/sfvscanf.c

The header file currently consists of roughly 160 lines of structs and constants, followed by roughly 400 lines of a single function.

Haven't analysed it in great detail, however, I am wondering if the single function can be extracted to say sfstrtof.c with an API that the four other C source files can use.

As opposed to having four almost identical copies of the function that differ in function name; like I said, haven't checked too deeply, so this is a guess.

If one of the copies has a bug, then a fix most be checked 3 more times potentially.
Refactoring is also risky, specially without extensive unit tests.

**Comment by krader1961** [comment]
Please ignore all the code in the *src/ast* tree. We are only touching it if a bug fix is required or to remove a dependency from ksh. For example, we want to remove the dependency on the AST vmalloc subsystem. There is no point in cleaning up that code if we end up removing the dependency on it. It will be a long time (likely a year or more) before things have improved enough that we will worry about issues like this one.

**Comment by catull** [comment]
Sounds good to me.
