### ISSUE TITLE
Can we eliminate the "host type" detection done at build time?

### ISSUE THREAD

**Issue by krader1961** [att/ast#297]
We are really close to being able to remove all of the legacy Nmake build infrastructure. One item that blocks that is the use of the *bin/package* command to emit a "host type" string:

```
hosttype_cmd=run_command('bin/package')
hosttype=hosttype_cmd.stdout().strip()

add_project_arguments('-DHOSTTYPE="' + hosttype + '"', language: 'c')
```

AFAICT this only affects the behavior of the legacy Nmake build system and is not actually used by ksh. It is, however, used in exactly two places in the libast code. One is `pathprobe_20100601()`. The other is in *src/lib/libast/port/astconf.c* to populate the `dynamic[]` table. Neither of which seem to actually affect ksh in any way. The callers of `pathprobe()` all seem to be from the legacy Nmake build system which we no longer support.

Does anyone know of any reason we can't eliminate using the legacy `bin/package` command when called with no options to return a "host type" string? This would mean defining the `HOSTTYPE` symbol to a static string such as `"unknown"` in the two places it is used.

**Comment by krader1961** [comment]
> This would mean defining the HOSTTYPE symbol to a static string such as "unknown" in the two places it is used.

At least until such time as that code is eliminated as a dependency to build `ksh`.

**Comment by krader1961** [comment]
Note that *bin/package* host type generation does some questionable transformations. For example, my primary system is actually `x86_64` architecture and that's probably true for nearly everyone running ksh today. Yet *bin/package* transforms that to `i386`. I think what I'm going to do as a baby step is replace it with calls to `uname -s` and `uname -m`, fold the values to lowercase, and join with a period. That should work on all systems we're currently working with. If we find a system where that doesn't produce a sensible value we can deal with it then. And by then we may have concluded the value truly isn't needed and thus no longer generate the value.

**Comment by dannyweldon** [comment]
> I think what I'm going to do as a baby step is replace it with calls to uname -s and uname -m, fold the values to lowercase, and join with a period.

That sounds reasonable to me.

**Comment by krader1961** [comment]
I just found the first distro we need to special-case. On Cygwin the output of `uname -s` is `CYGWIN_NT-10.0` on my MS Windows 10 system with the latest Cygwin software.
