### ISSUE TITLE
Test `locale` assumes GNU `join` flags are supported which isn't valid for BSD `join`

### ISSUE THREAD

**Issue by catull** [att/ast#301]
In comparing the difference in runtime between macOS and Fedora, I found this behaviour.

At first, on macOS I get this with `meson test -v locale`:

```log
TODO: Enable when custom builtins of external commands is working.
join: multi-character tab ‘＠’
	locale.sh[205]: join test script failed -- exit code 1
	locale.sh[208]: LC_ALL test script failed -- expected 'f1', got ''
1/1 locale                                  FAIL     0.64 s

OK:         0
FAIL:       1
SKIP:       0
TIMEOUT:    0
```

The same test run on Fedora actually gets the same error, you only see it if you look very hard for it.
The effect is though that it fails on macOS repeatedly, but not on Fedora.

These lines slightly changed make macOS catch up:

```diff
diff --git a/src/cmd/ksh93/tests/locale.sh b/src/cmd/ksh93/tests/locale.sh
index a353949..5be316f 100755
--- a/src/cmd/ksh93/tests/locale.sh
+++ b/src/cmd/ksh93/tests/locale.sh
@@ -196,9 +196,9 @@ done
 # setocale(LC_ALL,"") after setlocale() initialization
 locale=en_US.UTF-8

-printf 'f1\357\274\240f2\n' > input1
-printf 't2\357\274\240f1\n' > input2
-printf '\357\274\240\n' > delim
+printf 'f1@f2\n' > input1
+printf 't2@f1\n' > input2
+printf '@' > delim
 print "export LC_ALL=$locale
 join -j1 1 -j2 2 -o 1.1 -t \$(cat delim) input1 input2 > out" > script
 $SHELL -c 'unset LANG ${!LC_*}; $SHELL ./script' ||
```

Credit goes to https://stackoverflow.com/questions/24587955/bash-sort-and-multi-character-tab-error

The temp file `delim` above could be entirely removed in favour of

```sh
 join -j1 1 -j2 2 -o 1.1 -t '@' input1 input2 > out" > script
```

**Comment by krader1961** [comment]
You've misdiagnosed the problem. This fails on macOS because the `-j1 1` and `-j2 2` flags aren't valid . That's a GNU'ism not supported by the BSD `join` command. The solution is to change that to `-1 1` and `-2 2` which is valid for GNU and BSD. Also, you're replacing a non-ASCII code point with an ASCII code point. Which negates the main point of this test which is to verify that a non-ASCII field delimiter is handled correctly.

**Comment by krader1961** [comment]
P.S., Those three bytes are the UTF-8 representation for this [code point](https://codepoints.net/U+FF20?lang=en). Which in a UTF-8 local is a single character, not three chars.

**Comment by catull** [comment]
In my case, `join` actually is GNU coreutils 8.29, picked up from /usr/local/bin/join.

With your suggested change,
```sh
meson test -v locale
```
gives me:
```log
TODO: Enable when custom builtins of external commands is working.
join: multi-character tab ‘＠’
	locale.sh[205]: join test script failed -- exit code 1
	locale.sh[208]: LC_ALL test script failed -- expected 'f1', got ''
1/1 locale                                  FAIL     0.56 s
```

If I rename /usr/local/bin/join to gjoin, then ksh uses /usr/bin/join.
With the same suggested change, the test passes now.

I am puzzled, perhaps I have not built GNU coreutils correctly.
Most likely.
Because I only have `LANG=en_US.UTF-8` and it works for stock /usr/bin/join.

**Comment by catull** [comment]
Looking at the sources of GNU coreutils 8.29 join.c, lines 1100-1117:

```c
        case 't':
          {
            unsigned char newtab = optarg[0];
            if (! newtab)
              newtab = '\n'; /* '' => process the whole line.  */
            else if (optarg[1])
              {
                if (STREQ (optarg, "\\0"))
                  newtab = '\0';
                else
                  die (EXIT_FAILURE, 0, _("multi-character tab %s"),
                       quote (optarg));
              }
            if (0 <= tab && tab != newtab)
              die (EXIT_FAILURE, 0, _("incompatible tabs"));
            tab = newtab;
          }
          break;
```

The utilities `sort` and `split` give a bit more insight into "multi-character" support for the `-t` option.
Concentrate on the block comment in the middle of both of the excerpts below.
My interpretation is that only the argument "\0" is currently supported.
Multi-byte is not supported yet, either.

`sort.c` lines 4519-4542:
```c
        case 't':
          {
            char newtab = optarg[0];
            if (! newtab)
              die (SORT_FAILURE, 0, _("empty tab"));
            if (optarg[1])
              {
                if (STREQ (optarg, "\\0"))
                  newtab = '\0';
                else
                  {
                    /* Provoke with 'sort -txx'.  Complain about
                       "multi-character tab" instead of "multibyte tab", so
                       that the diagnostic's wording does not need to be
                       changed once multibyte characters are supported.  */
                    die (SORT_FAILURE, 0, _("multi-character tab %s"),
                         quote (optarg));
                  }
              }
            if (tab != TAB_DEFAULT && tab != newtab)
              die (SORT_FAILURE, 0, _("incompatible tabs"));
            tab = newtab;
          }
          break;
```
`split.c` lines 1407-1435:
```c
        case 't':
          {
            char neweol = optarg[0];
            if (! neweol)
              die (EXIT_FAILURE, 0, _("empty record separator"));
            if (optarg[1])
              {
                if (STREQ (optarg, "\\0"))
                  neweol = '\0';
                else
                  {
                    /* Provoke with 'split -txx'.  Complain about
                       "multi-character tab" instead of "multibyte tab", so
                       that the diagnostic's wording does not need to be
                       changed once multibyte characters are supported.  */
                    die (EXIT_FAILURE, 0, _("multi-character separator %s"),
                         quote (optarg));
                  }
              }
            /* Make it explicit we don't support multiple separators.  */
            if (0 <= eolchar && neweol != eolchar)
              {
                die (EXIT_FAILURE, 0,
                     _("multiple separator characters specified"));
              }

            eolchar = neweol;
          }
          break;
```

On Fedora 27 I have GNU coreutils 8.27 installed and the `locale` tests pass.
Something may have changed after version 8.27.

# Conclusion

GNU Coreutils 8.27 works with either `join -j1 .. -j2 ... -t ....` and `join -1 .. -2 ... -t .....`.
macOS join only works with `join -1 ... -2 ... -t .....`

GNU coreutils 8.29 potentially does not support multi-character tabs.

**Comment by krader1961** [comment]
> If I rename /usr/local/bin/join to gjoin, then ksh uses /usr/bin/join.

I used to install GNU coreutils aliased to the same names as the macOS equivalents. I no longer do so since it causes problems. Especially when running unit tests for projects like this one or the Fish shell.

> Because I only have LANG=en_US.UTF-8 and it works for stock /usr/bin/join.

That doesn't make sense. The macOS */usr/bin/join* program does not recognize the `-j` flag as I stated earlier. That's why the `locale` test fails with this in the test log:

```
 72/156 locale                                  FAIL     0.66 s

--- command ---
SHELL='/Users/krader/projects/3rd-party/ast/build/src/cmd/ksh93/ksh' LANG='' LD_LIBRARY_PA
--- stdout ---
TODO: Enable when custom builtins of external commands is working.
--- stderr ---
usage: join [-a fileno | -v fileno ] [-e string] [-1 field] [-2 field]
            [-o list] [-t char] file1 file2
        locale.sh[205]: join test script failed -- exit code 1
        locale.sh[208]: LC_ALL test script failed -- expected 'f1', got ''
        locale.sh[351]: incorrect string from printf %q
-------
```

**Comment by krader1961** [comment]
> The utilities sort and split give a bit more insight into "multi-character" support for the -t option. Concentrate on the block comment in the middle of both of the excerpts below. My interpretation is that only the argument "\0" is currently supported. Multi-byte is not supported yet, either.

Multi-character delimiters is not what is being tested. These three bytes, `\357\274\240`, represent a single character. Those three bytes is U+FF20 (a single Unicode code point) when encoded as UTF-8. The join command, both GNU and BSD, supports UTF-8 and treats those three bytes as a single character delimiter.

**Comment by catull** [comment]
I agree with you that GNU tools are a two-edged sword, causing problems on BSDs and macOS.

Unfortunately, quite a few open source software does not properly build/configure if you do not have autoconf, automake and GNU coreutils installed.

Anyway, you found an elegant solution here.

**Comment by krader1961** [comment]
Also, related to the earlier discussion around the differences between the GNU versus BSD `join` command the `od` command used by that unit test also has different behavior depending on which variant is used. The BSD version includes more whitespace in its output. Which causes the test at line 351 to fail: `locale.sh[351]: incorrect string from printf %q`. The fix for that is to modify the `sed` command that normalizes the `od` output to also condense multiple spaces to a single space.

**Comment by krader1961** [comment]
The fix I'm about to push to the `master` branch reduces the test failures from 26 to 23 on macOS :smile: No doubt many of the other failures are similar in nature. That is, not due to any inherent bug in `ksh` when built and run on BSD based systems but rather unwarranted assumptions about the behavior of various commands.
