### ISSUE TITLE
Missing realpath program on BSD, macOS

### ISSUE THREAD

**Issue by catull** [att/ast#323]
At least OpenBSD and macOS do not have a binary installed named `realpath`.
The system call `realpath` does exist on these platform.

Perhaps a shrink-down helper utility could be written, compiled and temporarily copied to bin/.
This utility could then be used in the scripts bin/*.sh.

**Comment by catull** [comment]
Something along the lines of https://github.com/harto/realpath-osx.

**Comment by krader1961** [comment]
For now I'm just going to modify the three scripts that use `realpath` to also use `grealpath` if it's available. That should be good enough for any reasonably modern BSD or Linux system. Although googling shows that old systems, such as Fedora 14, don't have it. If and when we need to build on those systems hopefully these bootstrap scripts won't be needed.

**Comment by siteshwar** [comment]
According to [run_command](http://mesonbuild.com/Reference-manual.html#run_command) documentation it sets `MESON_SOURCE_ROOT` variable for source directory. We should be able to use it instead of determining path at runtime with `realpath`.
