### ISSUE TITLE
Latest builds from GitHub for Fedora

### ISSUE THREAD

**Issue by siteshwar** [att/ast#333]
I have enabled builds from GitHub `master` branch in Fedora copr. Copr repository can be found [here]( https://copr.fedorainfracloud.org/coprs/g/ksh/latest/). This is the command to subscribe to the repository :

```
dnf copr enable @ksh/latest
```

For now I am triggering the builds manually, but I would like to setup a webhook to trigger the builds automatically on each commit. I am opening this issue to get some initial feedback about current setup.

**Comment by krader1961** [comment]
I don't know enough about setting up a project on Fedora Copr or Suse OBS to be able to offer meaningful feedback. But I wanted to add a reminder to document this type of thing in the *CONTRIBUTING.md* document I just created.

**Comment by siteshwar** [comment]
@krader1961 Good point. I will wait for feedback from community for current set up and update README.md and CONTRIBUTING.md once we have a stable set up.

**Comment by siteshwar** [comment]
GitHub webhook is working now, so we should get latest builds from [copr repo](https://copr.fedorainfracloud.org/coprs/g/ksh/latest/).
