### ISSUE TITLE
Bug: `!tp->lst.lstlef->tre.tretyp == TCOM`

### ISSUE THREAD

**Issue by krader1961** [att/ast#338]
While restyling the *src/cmd/ksh93/sh/name.c* module I noticed the following compiler warning:

```
../src/cmd/ksh93/sh/name.c:507:44: warning: logical not is only applied to the left hand side of this comparison [-Wlogical-not-parentheses]
                    if (!tp->lst.lstlef || !tp->lst.lstlef->tre.tretyp == TCOM ||
                                           ^                           ~~
../src/cmd/ksh93/sh/name.c:507:44: note: add parentheses after the '!' to evaluate the comparison first
                    if (!tp->lst.lstlef || !tp->lst.lstlef->tre.tretyp == TCOM ||
                                           ^
                                            (                                 )
../src/cmd/ksh93/sh/name.c:507:44: note: add parentheses around left hand side expression to silence this warning
                    if (!tp->lst.lstlef || !tp->lst.lstlef->tre.tretyp == TCOM ||
                                           ^
                                           (                          )
```

That expression is obviously wrong.

If you run `grep 'tre\.tretyp' *` in that directory you will see that there are zero other instances of this pattern. Most are of the form `(tp->tre.tretyp & COMMSK) == TCOM`. Some omit the `& COMMSK`. There are a couple instances of this expression: `tp->tre.tretyp != TLST`.

I'm opening this issue semi-rhetorically. It is obvious that the `==` should be `!=`. The only question is whether the value being tested should be masked with `& COMMSK`. And, for that matter, whether every other instance of an equality or inequality test of that form should be masking the value before doing the comparison.

**Comment by krader1961** [comment]
Interestingly fixing that obvious bug does not affect any unit test or any obvious behavior of the shell. So either that is controlling some really obscure behavior or it doesn't matter if that subexpression is true or false.

**Comment by catull** [comment]
Likely none of the tests "reach" that function yet.
