### ISSUE TITLE
Mamfile needed ?

### ISSUE THREAD

**Issue by catull** [att/ast#339]
My limited knowledge of `meson`, `iffe` and `Mamfile` in specific leads me to question if we still need the `Mamfile` ?

I notice that almost in each case where there is a `Mamfile` in a folder, there is also a `meson.build` file.

In other words, as soon as each `Mamfile` is re-written with a `meson` build file, the `Mamfile` will be removed ?

Mamfile:
./src/cmd/builtin/Mamfile
./src/cmd/coshell/Mamfile
./src/cmd/ksh93/Mamfile
./src/cmd/kshlib/cmdtst/Mamfile
./src/cmd/kshlib/codex/Mamfile
./src/cmd/kshlib/dbm/Mamfile
./src/cmd/kshlib/dbm_t/Mamfile
./src/cmd/kshlib/dss/Mamfile
./src/cmd/kshlib/Mamfile
./src/cmd/kshlib/open/Mamfile
./src/cmd/kshlib/setid/Mamfile
./src/cmd/Mamfile
./src/cmd/msgcc/Mamfile
./src/cmd/msggen/Mamfile
./src/cmd/std/Mamfile
./src/cmd/tests/Mamfile
./src/lib/libardir/Mamfile
./src/lib/libast/Mamfile
./src/lib/libcmd/Mamfile
./src/lib/libcoshell/Mamfile
./src/lib/libcs/Mamfile
./src/lib/libdll/Mamfile
./src/lib/libodelta/Mamfile
./src/lib/libsum/Mamfile
./src/lib/Mamfile
./src/Mamfile

meson.build:
./meson.build
./src/cmd/ksh93/bltins/meson.build
./src/cmd/ksh93/data/meson.build
./src/cmd/ksh93/edit/meson.build
./src/cmd/ksh93/meson.build
./src/cmd/ksh93/sh/meson.build
./src/lib/libast/aso/meson.build
./src/lib/libast/cdt/meson.build
./src/lib/libast/comp/meson.build
./src/lib/libast/disc/meson.build
./src/lib/libast/hash/meson.build
./src/lib/libast/meson.build
./src/lib/libast/misc/meson.build
./src/lib/libast/path/meson.build
./src/lib/libast/port/meson.build
./src/lib/libast/regex/meson.build
./src/lib/libast/sfio/meson.build
./src/lib/libast/string/meson.build
./src/lib/libast/tm/meson.build
./src/lib/libast/vmalloc/meson.build
./src/lib/libcmd/meson.build
./src/lib/libcoshell/meson.build

**Comment by krader1961** [comment]
We don't need the `Makefile`s either. The only reason we haven't already removed them was to make it easy to look at their contents for comparison with the current build defaults. But I agree we've probably reached the point where that is unlikely to be needed. And if it is we can always checkout the `2016-01-10-beta` branch to examine these files. In fact, I have a copy of the git repo  (named `ast.beta`) with that branch permanently checked out expressly for that purpose. I've gone ahead and merged a change to remove these legacy build files.
