### ISSUE TITLE
Enable libast unit tests

### ISSUE THREAD

**Issue by krader1961** [att/ast#350]
Since we're stuck for the foreseeable future using subsystems like SFIO we should probably enable running their unit tests.

**Comment by siteshwar** [comment]
+1. We should also enhance current test suite and write unit tests for other components of libast that we will continue to use.

**Comment by fpmurphy** [comment]
@krader1961.  You most certainly should such be running the existing libast tests.  To do otherwise would demonstrate gross ineptitude.

**Comment by krader1961** [comment]
@fpmurphy, Does your comment indicate you will be providing fixes so those tests pass? Because at the moment a huge number of tests fail on the `2016-01-10-beta` branch; i.e., before we started all the recent cleanup activity and changed the build system.
