### ISSUE TITLE
Tests create temporary folders which are difficult to associate with test scripts

### ISSUE THREAD

**Issue by catull** [att/ast#360]
The tests run on Fedora produced little diagnostic output until recently.

I ran all tests with `meson test -v`, the workspace is unmodified from commit 19d0620a72fe8c1b0ae43ae198f1f505fc9320c1.

When running all tests, these sort of lines are difficult to associate with the test affecting it:
```log
....
rm: cannot remove '/tmp/tmp.vUGNMNYPSf/a/b/c': Permission denied
....
rm: cannot remove '/tmp/tmp.11kcPtcerj/a/b/c': Permission denied
....
rm: cannot remove '/tmp/tmp.ffVNsoxJsZ/a/b/c': Permission denied
...
```

My conclusion is that the three failed removals of temporary directories happen in the EXIT `trap`.

It would be great if the temporary folders were created with a bit more context.
Such as
```sh
tmp=$(mktemp -dt ksh.${Command}-XXXXXXXX)
```

It would help in tracking problems; imagine the situation where you have dozens of temporary directories or files in /tmp/ matching `tmp.*` over time.

**Comment by catull** [comment]
The fact that some temp directories are left behind after the tests are run indicates the test scripts are not terminating in a way for the trap code to be executed.

In at least one case, the test involves file manipulations in a temporary sub-directory which have to fail because the sub-directory has no execute bit set; the final `rm -fr $tmp` will not be able to remove all the folders under $tmp, if the user is not `root`.

I am more concerned with other scenarios.
For those cases, the more descriptive naming of the temporary folders are a benefit.

**Comment by fpmurphy** [comment]
@Catull.   The current Unix/Linux practice is to reserve /tmp for system temporary files and /var/tmp for other temporary files.  I suggest that /var/tmp is the correct location for ksh93 test temporary files.

**Comment by catull** [comment]
That's nice, if that works great for Linux systems.

**Comment by hlangeveld** [comment]
On 01/21/2018 13:13, Finbarr Murphy wrote:
> @catull <https://github.com/catull>. The current Unix/Linux practice is to reserve /tmp for system temporary files and /var/tmp for 
> other temporary files. I suggest that /var/tmp is the correct location for ksh93 test temporary files.

The convention I'm most familiar with is that |/tmp| may be cleared automatically on boot (it should be safe to mount
this on a memory based file system), while |/var/tmp| may persist across reboots.

Cheers,
Henk

Linux man hier(7):

/tmp

This directory contains temporary files which may be deleted with no notice, such as by a regular job or at system boot up.

/var/tmp

Like /tmp, this directory holds temporary files stored for an unspecified duration.


FreeBSD: https://www.freebsd.org/cgi/man.cgi?query=hier&format=html


/tmp/		temporary files	that are not guaranteed	to persist across sys-
		tem reboots
/var
	tmp/	temporary files that are kept between system reboots


OpenBSD appears to be the exception, as it explicitly links /var/tmp to /tmp.
https://man.openbsd.org/hier

/tmp/
		Temporary files that are not preserved between system reboots. Periodically cleaned by daily(8).

/var/
	tmp -> ../tmp
		A symbolic link to the system /tmp directory. To protect other users of
		/var from overfill conditions, this is no longer a space you can trust
		to retain storage over a reboot. Periodically cleaned by daily(8).

**Comment by catull** [comment]
I checked both /tmp and /var/tmp on Fedora 27.
As non-root I can create files and folders in either `/var/tmp/` or `/tmp/`, they are both set to **drwxrwxrwt.*.

However, I am inclined to believe the opposite of what you are stating, @fpmurphy.

Under /var/tmp/ I find many files and folders owned by `root` containing "service" in them, such as 
- systemd-private-0bf61235f3ec40b39a810fe7ad802919-chronyd.service-6XgenB
- systemd-private-0bf61235f3ec40b39a810fe7ad802919-colord.service-rYW5bP
- systemd-private-0bf61235f3ec40b39a810fe7ad802919-rtkit-daemon.service-y3xzn9

On the other hand, in /tmp/ I see _personal_, i.e. non-root ...
- X11 meta files
- socket files
- editor temp files
- etc

Like I said, the opposite of your description.

In the end it is a choice of the developer.

**Comment by DavidMorano** [comment]
@hlangeveld wrote:
> The convention I'm most familiar with is that |/tmp| may be cleared automatically on boot (it should be safe to mount this on a memory based file system), while |/var/tmp| may persist across reboots.

This is my experience also, now for about 30 years; namely, /tmp gets deleted (erased whatever) on reboots and can therefore (optionally) be mounted on memory or swap (what have you).  While /vat/tmp is retained across reboots and not usually mounted onto memory or swap. 

I am not entirely sure, but I think that this convention was first adopted around 1988 with the introduction of System V Release 4 from AT&T. Sun Microsystems says that they adopted this idea from SysV when they split off their own SunOS-5 (otherwise named Solaris-2).  I think several other distros followed suit sometime afterwards., This convention (/tmp getting deleted across reboots) may even predate SVR4 in about 1988. In practice, this possible speed distinction may usually be very small indeed since all disk access is generally cached using system memory anyway.

If someone knows more about the history of this, please share that history.

**Comment by krader1961** [comment]
@DavidMorano is correct AFAIK as a grey beard (I started using UNIX, then supporting it, in the 1980's). Furthermore, best practice today is to use env var `TMPDIR` if it exists or let the implementation default to the appropriate directory.

**Comment by krader1961** [comment]
I merged the PR associated with this issue. It isn't ideal but is a step in the right direction. I have no idea what @fpmurphy means by "system temporary files". Historically the */tmp* directory was for files that could be removed when the system was rebooted. Much later the */var/tmp* convention was created for files that may, or may not, persist across reboots. Ideally all of the temporary files created by AST unit tests would be anchored under the *build* directory of the project. But that is a problem for another day.
