### ISSUE TITLE
Improve escape sequence handling in prompt

### ISSUE THREAD

**Issue by perette** [att/ast#399]
The code that calculates the prompt length takes into account some escape sequences, but not all.  One might use these for a highlighted prompt, for example.  Incorrect calculation causes vi mode (`set -o vi`) to behave erratically: with a multi-line statement, the cursor is moved to the second line earlier than it should, causing the cursor to incorrectly reflect the edit point.  Using j/k to travel back through the history also causes problems, including duplicate lines, moving back up the screen, or "eating the prompt" by moving the first line to the left.

The attached patch adds additional escape sequence recognition.  In revising the code, my citations were:

- [Xterm Control Sequences](https://www.xfree86.org/4.8.0/ctlseqs.html)
- The escape sequence from `tput sgr0`: 033   (   B 033   [   m
- The escape sequence from `tput rs2`:  033   [   !   p 033   [   ?   3   ;   4   l 033   [   4   l 033 &lt;

Additionally, the `rs2` sequence involves a '!'.  The prompt display was modified to avoid expanding '!' in an escape sequence to the command number, which breaks the escape sequence.

Please integrate this into the code base.

[ksh-prompt.txt](https://github.com/att/ast/files/1695874/ksh-prompt.txt)

**Comment by siteshwar** [comment]
@perette Mind doing a pull request ? I can integrate this patch manually, but a commit on your name should give you due credit.

**Comment by perette** [comment]
Not worried about credit, just hoping to fix the bug.

**Comment by siteshwar** [comment]
@perette Merged requested patch. Thanks for your contribution.
