### ISSUE TITLE
locale test failure

### ISSUE THREAD

**Issue by floppym** [att/ast#411]
I'm getting the following test failures on master.

Gentoo Linux
glibc-2.26
coreutils-8.29 (provides the /usr/bin/join binary)

```
 69/153 locale                                  FAIL     0.30 s

--- command ---
SHELL='/home/floppym/src/ast/build/src/cmd/ksh93/ksh' LANG='' LD_LIBRARY_PATH='/home/floppym/src/ast/build/src/lib/libast:/home/floppym/src/ast/build/src/lib/libcmd:/home/floppym/src/ast/build/src/lib/libcoshell' /home/floppym/src/ast/build/src/cmd/ksh93/ksh /home/floppym/src/ast/src/cmd/ksh93/tests/locale.sh locale
--- stdout ---
TODO: Enable when custom builtins of external commands is working.
--- stderr ---
join: multi-character tab ‘＠’
        locale.sh[224]: join test script failed -- exit code 1
        locale.sh[227]: LC_ALL test script failed -- expected 'f2＠t2', got ''
-------

 70/153 locale/C.UTF-8                          FAIL     0.29 s

--- command ---
SHELL='/home/floppym/src/ast/build/src/cmd/ksh93/ksh' LANG='C.UTF-8' LD_LIBRARY_PATH='/home/floppym/src/ast/build/src/lib/libast:/home/floppym/src/ast/build/src/lib/libcmd:/home/floppym/src/ast/build/src/lib/libcoshell' /home/floppym/src/ast/build/src/cmd/ksh93/ksh /home/floppym/src/ast/src/cmd/ksh93/tests/locale.sh locale
--- stdout ---
TODO: Enable when custom builtins of external commands is working.
--- stderr ---
join: multi-character tab ‘＠’
        locale.sh[224]: join test script failed -- exit code 1
        locale.sh[227]: LC_ALL test script failed -- expected 'f2＠t2', got ''
-------

 71/153 locale/shcomp                           FAIL     0.31 s

--- command ---
SHELL='/home/floppym/src/ast/build/src/cmd/ksh93/ksh' LANG='' SHCOMP='/home/floppym/src/ast/build/src/cmd/ksh93/shcomp' LD_LIBRARY_PATH='/home/floppym/src/ast/build/src/lib/libast:/home/floppym/src/ast/build/src/lib/libcmd:/home/floppym/src/ast/build/src/lib/libcoshell' /home/floppym/src/ast/build/src/cmd/ksh93/ksh /home/floppym/src/ast/src/cmd/ksh93/tests/shcomptest /home/floppym/src/ast/src/cmd/ksh93/tests/locale.sh locale
--- stdout ---
TODO: Enable when custom builtins of external commands is working.
--- stderr ---
join: multi-character tab ‘＠’
        ksh.locale.Lx7uRZOA[224]: join test script failed -- exit code 1
        ksh.locale.Lx7uRZOA[227]: LC_ALL test script failed -- expected 'f2＠t2', got ''
-------
```

**Comment by siteshwar** [comment]
It looks like `join` might be failing. Can you apply below patch and give output of `meson test locale -v` ?

```
diff --git a/src/cmd/ksh93/tests/locale.sh b/src/cmd/ksh93/tests/locale.sh
index ae218a4b..ab99dd3d 100755
--- a/src/cmd/ksh93/tests/locale.sh
+++ b/src/cmd/ksh93/tests/locale.sh
@@ -218,7 +218,7 @@ locale=en_US.UTF-8
 printf 'f1\357\274\240f2\n' > input1
 printf 't2\357\274\240f1\n' > input2
 printf '\357\274\240\n' > delim
-print "export LC_ALL=$locale
+print "set -x; export LC_ALL=$locale
 join -1 1 -2 2 -o 1.2,2.1 -t \$(cat delim) input1 input2 > out" > script
 $SHELL -c 'unset LANG ${!LC_*}; $SHELL ./script' ||
 err_exit "join test script failed -- exit code $?"
```

This test works fine for me on Fedora 26 with `coreutils-8.27-7.fc26.x86_64`.

**Comment by floppym** [comment]
Yes, the join command is exiting with a error message and status 1.
```
floppym@naomi build % meson test locale -v
ninja: Entering directory `/home/floppym/src/ast/build'
ninja: no work to do.
TODO: Enable when custom builtins of external commands is working.
+ LC_ALL=en_US.UTF-8
+ export LC_ALL
+ cat delim
+ join -1 1 -2 2 -o 1.2,2.1 -t $'＠' input1 input2
+ 1> out
join: multi-character tab ‘＠’
        locale.sh[224]: join test script failed -- exit code 1
        locale.sh[227]: LC_ALL test script failed -- expected 'f2＠t2', got ''
1/1 locale                                  FAIL     0.22 s

OK:         0
FAIL:       1
SKIP:       0
TIMEOUT:    0
```

**Comment by floppym** [comment]
It seems that Fedora patches the join command to allow multi-byte characters to be used as a field separator.

https://src.fedoraproject.org/rpms/coreutils/blob/master/f/coreutils-i18n.patch

**Comment by siteshwar** [comment]
@kdudka should be able to elaborate on it, but it's not a bug in ksh.

**Comment by floppym** [comment]
Well, I would say it is not a great idea to have a unit test that relies on behavior that varies based on the Linux distro being used.

**Comment by floppym** [comment]
Ideally, the multibyte support would be merged I GNU coreutils upstream, and then everyone benefits. I'm very curious to know why the hasn't happened in the 3 years that Red Hat has been patching it. 

I think this portion of the local test should be removed, or the AST version of the join command should actually be built/used.

**Comment by krader1961** [comment]
Thanks for reminding me to take a look at this failure, @floppym. I disabled that subtest because it was clearly meant to test the builtin `join` command which we currently don't enable. Issue #129 is for discussions about whether borg standard `ksh` should have so many builtin analogues of external commands. Running `meson test` now succeeds on Ubuntu and should succeed on Gentoo (modulo the usual random failures).

> Ideally, the multibyte support would be merged I GNU coreutils upstream, and then everyone benefits. I'm very curious to know why the hasn't happened in the 3 years that Red Hat has been patching it.

Me too.

**Comment by kdudka** [comment]
If you think that ```join(1)``` does not work properly on Fedora, please create a bug for it in Red Hat Bugzilla  using the default template (steps to reproduce, expected results, actual results).  Thanks in advance!

**Comment by kdudka** [comment]
On Thursday, February 15, 2018 1:18:57 AM CET Mike Gilbert wrote:
> Ideally, the multibyte support would be merged I GNU coreutils upstream, and
> then everyone benefits.

I totally agree on that.  There is an upstream plan to make it supported:

http://www.pixelbeat.org/docs/coreutils_i18n/

Any help on the effort is highly appreciated!

> I'm very curious to know why the hasn't happened in
> the 3 years that Red Hat has been patching it.

Actually, the i18n patch has been used since 2002.

**Comment by floppym** [comment]
Ah, thanks for the info!
