### ISSUE TITLE
Fix to parameter substitution case modification operators

### ISSUE THREAD

**Issue by perette** [att/ast#417]
Attached is a patch to fix the case modification operators `${name^pattern}` and `${name,pattern}`.  It now uses shell patterns, and replaces the matched portion with upper or lower case.  These are consistent with the behaviour of other parameter substitution forms, and closer to bash's operator, although bash exhibits some arbitrary limitations.  Further down in this thread is a comparison of prior ksh, this patch, and bash behaviors.  [ksh-case-modification.patch.txt](https://github.com/att/ast/files/1759513/ksh-case-modification.patch.txt)

The original code's behavior was (for ^ and ,) to modify the first character only, and then only if the first character of the pattern was a '?'; and (for ^^ and ,,) to modify the whole string, regardless of the pattern.

Included is an update to the man page for these operators, to clarify and bring the text into line with similar operators.

>   Case  modification.   This expansion modifies the case of alphaetic characters in parameter.  The pattern is expanded to  produce a  pattern just as in pathname expansion.  The  ^  operator converts  lowercase  characters  matching  pattern to uppercase.  The  , operator converts matching uppercase characters to lowercase.   The ^^ and ,, expansions  convert  all  matched  character  in  the expanded  value.  The  ^ and , expansions match and convert only the first character in the expanded value.  If pattern is  omitted it is treated like a  ?,  which  matches  every character.  If parameter is @ or *, or an array subscripted by @ or *, the case modification operation is  applied to  each  element.

The proposed new text reads:

>    Case modification.  If the shell _pattern_ matches the value of _parameter_, then this expansion is the value of the _parameter_ with alphabetic characters in the matched portion changed to uppercase for **^** and **^^**, or to lowercase for **,** and **,,**.    For **^** and **,** the transformation is applied only if the match is at the beginning of the string.  For **^** and **,,** all matches are transformed.  If _pattern_ is unmatched, then _parameter_ is substituted unmodified. When _parameter_ is **@**, __*__, or an array variable with subscript **@** or __*__, the transformation is applied to each element in turn.

**Comment by krader1961** [comment]
This looks like a backward incompatible change to me. Am I mistaken? Also, while I only glanced at the test cases the last example looks incorrect to me:

```
[array]          ${arr[@],,*([A-Ma-m])} -->arrr thar be PIRATES!
```

Why isn't the final `PIRATES` converted to lowercase? It matches the pattern and therefore should have been converted to lowercase it seems to me.

**Comment by perette** [comment]
The character class specified in the shell pattern is for A-M.  P is outside that range.

This does slightly change the behavior, which was introduced in the last few years although I haven't nailed down a date, I suspect as a copycat feature from bash.  Since prior behavior resembled neither bash's operators, nor other ksh behavior, and this hasn't had a lot of time to get entrenched, I think fixing it is worth considering.

**Comment by krader1961** [comment]
> The character class specified in the shell pattern is for A-M. P is outside that range.

Argh! Yes, you are correct about that incorrect behavior. 

> I suspect as a copycat feature from bash

That is probably true. Which is why I have argued for removing support for bash compatibility. See issue #238.

**Comment by perette** [comment]
For compatibility, it sounds like ${name^^} (without a pattern) should uppercase the whole substitution, both for compatibility with other shells and for minimizing ksh behavior change.  In the existing code, however, ${name^} does nothing, while in bash this just does one character.  Doing a single character seems like the right thing: ${name^} is pointless if it behaves the same as ${name}.

zsh does not seem to have this support yet.  (Version 5.1.1)

**Comment by DavidMorano** [comment]
@perette 
> ${name^} is pointless if it behaves the same as ${name}.

I am not aware of what all of the shells do with these patterns, but your proposal seems sound to me; namely,
${name^ } -> upper-case first letter only
${name^^}   -> upper-case all letters

The lack of standardization with these forms (above) probably stems from the fact that ^ and ^^ (as above) were never initially meant to be used unqualified (without a following specifier), but your proposal seems to be both logical and reasonable (as far as I understand the matter). But you should try to get some broader consensus on this.  These simple patterns (^ alone and ^^) may have been left pseudo-unused for possible future feature expansion of some sort.

**Comment by perette** [comment]
I've been reworking the implementation, and here's what the output looks like so far:
```
Input        Query                  /bin/ksh      ./ksh         bash        
abcdef       ${value}               abcdef        abcdef        abcdef      =
abcdef       ${value^}              abcdef        Abcdef        Abcdef      =
abcdef       ${value^?}             Abcdef        Abcdef        Abcdef      =
abcdef       ${value^????}          Abcdef        ABCDef        abcdef      !=
abcdef       ${value^*}             abcdef        ABCDEF        Abcdef      !=
abcdef       ${value^^}             ABCDEF        ABCDEF        ABCDEF      =
abcdef       ${value^^+(?)}         ABCDEF        ABCDEF        ABCDEF      =
abcdef       ${value^+([a-cA-C])}   abcdef        ABCdef        Abcdef      !=
abcdef       ${value^[a-e]}         abcdef        Abcdef        Abcdef      =
abcdef       ${value^[b-e]}         abcdef        abcdef        abcdef      =
abcdef       ${value^^+([a-cA-C])}  ABCDEF        ABCdef        ABCdef      =
abcdef       ${value^^+(?[bd])}     ABCDEF        ABCDef        abcdef      !=
abcdef       ${value^^ab+([^ef])}   ABCDEF        ABCDef        abcdef      !=
abcdef       ${value^^[a-e]}        ABCDEF        ABCDEf        ABCDEf      =
abcdef       ${value^^[b-e]}        ABCDEF        aBCDEf        aBCDEf      =
abc def ghi  ${value^}              abc def ghi   Abc def ghi   Abc def ghi =
abc def ghi  ${value^^}             abc def GHI   ABC DEF GHI   ABC DEF GHI =
abcdef       ${value,?}             abcdef        abcdef        abcdef      =
abcdef       ${value,????}          abcdef        abcdef        abcdef      =
abcdef       ${value,+([a-cA-C])}   abcdef        abcdef        abcdef      =
abcdef       ${value,,+([a-cA-C])}  abcdef        abcdef        abcdef      =
CAPITOLS     ${value}               CAPITOLS      CAPITOLS      CAPITOLS    =
CAPITOLS     ${value,?}             cAPITOLS      cAPITOLS      cAPITOLS    =
CAPITOLS     ${value,????}          cAPITOLS      capiTOLS      CAPITOLS    !=
CAPITOLS     ${value,+([a-cA-C])}   CAPITOLS      caPITOLS      cAPITOLS    !=
CAPITOLS     ${value,,+([a-cA-C])}  capitols      caPITOLS      caPITOLS    =
Testing array:
[array]      ${arr[@]} -->Arrr thar be PIRATES!
[array]      ${arr[@]^?} -->Arrr Thar Be PIRATES!
[array]      ${arr[@]^^*} -->ARRR THAR BE PIRATES!
[array]      ${arr[@],,*} -->arrr thar be pirates!
[array]      ${arr[@]^????} -->Arrr Thar Be PIRATES!
[array]      ${arr[@],,*([A-Ma-m])} -->arrr thar be pirates!
```
The = or != column compares ./ksh vs. bash.  /bin/ksh is the prior implementation; notice newfound screwy behavior when there are spaces in the value.  ./ksh is the one I'm working on.  zsh doesn't have this operator, thus isn't listed.

Bash implements this by applying the pattern to exactly one character at a time, thus it doesn't change anything with multi-character-only patterns.  This improves over their implementation, but otherwise provides similar behavior except for ${name^*}.

As to compatibility with ksh: all forms of `^^` work the same, except unquoted expansion when there are spaces, but in this case the prior behavior (only case adjusting the last word) is not a sane behavior.  `^?` works the same, and all other forms of `^` did either nothing at all or nothing more than `^?`, so there's no reason they should be in use.  I think this means we're safe on that front too.

If this seems sane, I'll provide the patch.

**Comment by siteshwar** [comment]
@perette Sorry it went off my radar. Usually a pull request with a test case helps in getting patches integrated  much faster. I am travelling at the moment, but I will definitely look at it when I get back.

**Comment by siteshwar** [comment]
@perette If I am not missing anything, case modification was introduced by [this commit](https://github.com/att/ast/commit/0bc6abf9e1e7f5af40a8fa69da94f7ec7c34eb02#diff-67be2c688cd12b270a30931af86ad6d6) and it was not available in the last stable release. This is the output I receive on my RHEL 7 machine running `ksh-20120801-137.el7.x86_64`:

```
# value=abcdef
# echo ${value}
abcdef
# echo ${value^}
ksh: syntax error: `^' unexpected
```

Since we want to stay compatible with the last stable release, I think we should disable this feature.

**Comment by siteshwar** [comment]
> I'm getting the impression there is distrust of outsiders working on this code.

How did you get that impression ? I am a bit surprised by this statement. Current code is in very bad shape and we value any contributions to improve it. Only thing is that we try to be careful with backward incompatible changes as it might break existing scripts.

**Comment by perette** [comment]
It's hard to pin down a single reason.  But, I'll take you at your word and look into some other issues.  Thanks.

**Comment by siteshwar** [comment]
@perette fwiw I appreciate the time you spent in writing this patch and it's [thorough analysis](https://github.com/att/ast/issues/417#issuecomment-367575427). It's a bit unfortunate that we can not ship this patch due to concerns around compatibility. And you have already helped us in debugging couple of issues, so you are no outsider to this project. It would be awesome to see more contributions from you.

**Comment by krader1961** [comment]
> I'm getting the impression there is distrust of outsiders working on this code.

@perette, I suspect you got that impression from my first couple of comments on this issue. My comments were influenced by the folks at RedHat (e.g., @siteshwar) and some others whom we haven't heard from in several months. Specifically that any change which affects legacy behavior requires extra scrutiny. I am personally not convinced we need to be quite so conservative. But I do understand why vendors such as RedHat want the next ksh release to be as compatible with ksh93u+ as feasible while otherwise modernizing the source code and build system.

I too am an "outsider". If you search the issues you'll see that many of my proposals to improve the project, such as by removing dubious features (e.g., a bash emulation mode), received very vocal pushback from a few individuals. I came very close to giving up on improving this project. But the individuals who expressed those strong opinions, all of whom never made a single change to the code, have disappeared. So I'm sticking around in the hope that the official ksh can displace all the clones and remain relevant. Like @siteshwar I hope you continue to contribute to that goal.

**Comment by siteshwar** [comment]
Since we have disabled this feature, I am going to close this issue. Thanks @perette for brining this to our attention.
