### ISSUE TITLE
bin/style uses `cmp --quiet`, fails in OpenBSD

### ISSUE THREAD

**Issue by kernigh** [att/ast#433]
OpenBSD's `cmp` doesn't know `--quiet`, so bin/style always reports that the file was not correctly formatted, even if clang-format didn't change anything. I believe that the fix is to use `cmp -s`.

```
diff --git a/bin/style b/bin/style
index 6a0eadff..b9446d39 100755
--- a/bin/style
+++ b/bin/style
@@ -103,7 +103,7 @@ else if type -q clang-format
     for file in $c_files
         cp $file $file.new # preserves mode bits
         clang-format $file >$file.new
-        if cmp --quiet $file $file.new
+        if cmp -s $file $file.new
             rm $file.new
         else
             echo $file was NOT correctly formatted
```

These manuals mention `-s` but not `--quiet`: https://man.openbsd.org/cmp, https://www.freebsd.org/cgi/man.cgi?query=cmp, https://illumos.org/man/cmp

**Comment by krader1961** [comment]
Thanks for actually trying this utility script; especially since it requires installing the Fish shell.
