### ISSUE TITLE
Job control not enabled on initial shell

### ISSUE THREAD

**Issue by perette** [att/ast#437]
I'm experiencing trouble with job control.  In my initial shell (SHLVL=1) it doesn't work.  It works correctly if I fork a subshell.

I've tracked it down to job.jobcontrol == 0, because in job_init (defined at jobs.c:576):

:622 Tries to sets process group ID, but fails so it sets `possible = 0`
:623 Since setpgid failed with `errno == EPERM`, it enters the if
:625 And skips the while loop because the process is already in the foreground
:640 This `#ifdef` block is skipped (`NTTYDISC` is undefined on my system)
:661 `possible` is still false from earlier so it returns...
...and thus it never gets around to enabling job control, which is down at :692.

Note at :637, then `#endif` comment (`SIGTTIN`) does not match `#ifdef` checked on :621 (`SIGTSTP`).  I'm not sure if this a red herring or a sign of edit fatigue which may have introduced this problem.

It seems to me that the intervening code tries to handle the `!possible` situation, and if it can't, it returns--meaning the extra check for !possible is superfluous.  Thus, I've tried removing line :662 (`if (!possible) return;`), with good results--but considering the obscure stuff going on here, I'm not confident that's free from side effects I don't understand.

Session demonstrating problem:
```
perette@lenora ~ $ sleep 5 &
[1]     4467
perette@lenora ~ $ fg %1
ksh: fg: No job control
perette@lenora ~ $ sleep 5 &
[1]     26065
perette@lenora ~ [subshell 2]$ fg %1
sleep 5
perette@lenora ~ [subshell 2]$
```

**Comment by siteshwar** [comment]
I am running `ksh-20180316+git.660.2b3bffbd-0.fc26.x86_64` on my Fedora box, but could not reproduce this issue. What OS you are using ?

**Comment by perette** [comment]
```
RELEASE=18.3
CODENAME=sylvia
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 18.3 Sylvia"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sylvia_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sylvia_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18.3 Cinnamon 64-bit
```

It's turning out that another screwy behaviors (applications fighting for input with ksh instead of dieing a proper death on ^C) is a result of this issue.

**Comment by siteshwar** [comment]
I managed to reproduce this issue on both Linux Mint and Fedora. It's not reproducible with last stable release so it's probably introduced by either last beta release or our build system changes.

**Comment by siteshwar** [comment]
[This call](https://github.com/att/ast/blob/2b3bffbd8ba8f79add81e2387df1c3845f33fea1/src/cmd/ksh93/sh/jobs.c#L622) will fail if current process is the session leader, that's why it's failing when ksh is used as login shell. I will open pull request to fix this issue.

**Comment by krader1961** [comment]
I can't reproduce this using the instructions in the original comment. I would recommend that before we try to determine root cause the hard way the first thing to do is see if the problem exists using a ksh built from the `2016-01-10-beta` branch.

**Comment by siteshwar** [comment]
@krader1961 You are right about checking if it worked in `2016-01-10-beta` branch. However if you look at [this code](https://github.com/att/ast/blob/14604f580e3e9e4e2e228a1a3ae1a29bed869391/src/cmd/ksh93/sh/jobs.c#L600-L622) in `job_init` function it looks unneeded. I will try to explain:

1. [`job.mypgid = getpgrp();`](https://github.com/att/ast/blob/14604f580e3e9e4e2e228a1a3ae1a29bed869391/src/cmd/ksh93/sh/jobs.c#L600) sets `job.mypgid` to current process group.

2. [According to POSIX](http://pubs.opengroup.org/onlinepubs/009695399/functions/getpgrp.html) getpgrp should never fail. This means `job.mypgid` will always be set to a value greater than or equal to 1. So [this code](https://github.com/att/ast/blob/14604f580e3e9e4e2e228a1a3ae1a29bed869391/src/cmd/ksh93/sh/jobs.c#L602-L620) is unnecessary and will never be executed.

3. [`possible = setpgid(0, job.mypgid) >= 0`](https://github.com/att/ast/blob/14604f580e3e9e4e2e228a1a3ae1a29bed869391/src/cmd/ksh93/sh/jobs.c#L622) tries to set process group id of current process to the same value that it got in step 1. It is unneeded and as I understand this will only fail if current process is the session leader.

I think we can just assume a process is always started in a valid process group and remove bogus code. But I need to figure out why this code worked in last stable release.

**Comment by perette** [comment]
1.  Agreed.
2.  According to documentation, yes--though this may be there to fix an issue on some ancient non-POSIX compliant system.
3.  I think you're proposing to remove this check, and have all processes go through the loop that ensures they have the foreground.  Is there risk this would effect batch/cron jobs, causing hangs on some systems?

**Comment by siteshwar** [comment]
> I think you're proposing to remove this check, and have all processes go through the loop that ensures they have the foreground. Is there risk this would effect batch/cron jobs, causing hangs on some systems?

When ksh is started as  non-interactive shell, it returns from [here](https://github.com/att/ast/blob/14604f580e3e9e4e2e228a1a3ae1a29bed869391/src/cmd/ksh93/sh/jobs.c#L584). So it should not affect background jobs.

**Comment by perette** [comment]
The interactive mode flag is not a reliable expectation, as it can be set or unset by the -i/+i flags to ksh, which are processed prior to `job_init()` being called.  To be fair, it's a flag I've never used, and I've been shell scripting for 0x1b years.  Still, rarely needed is not never.

```
sh_main (main.c:117) calls sh_init at :139.
sh_init (init.c:1260) calls sh_argopts at 1439.
sh_argopts (args.c:214) does optget at :228, where -i is processed.
sh_main calls job_init at :188.
```

**Comment by siteshwar** [comment]
I don't know which exotic cases will require running a shell in background with interactive mode. In any case, the current code should not handle the situation any better.

**Comment by DavidMorano** [comment]
@siteshwar
> To be fair, it's a flag I've never used, and I've been shell scripting for 0x1b years. Still, rarely needed is not never.

:-) I have used the -i flag many times (semi-regularly sometimes).
It is useful any time the shell is not on a TTY yet one wants to use it in an interactive mode.

The most common case is a network connection of some sort (usually a socket) or a local connection over a pipe, and one wants to get an interactive shell.  It is often more of a maintenance thing or for some sort of debugging.

Also, I use a remote execution facility which creates a connection from the current host to a load-balance selected host on the same cluster.  This is usually used for non-interactive jobs but can be used by the shell by specifying KSH as the remove program to execute. But the connection does not provide a TTY. So if I want an interactive shell to a remote machine that is lightly loaded (facility will select the lightest-load machine in the cluster), I use ksh -i as the program to execute remotely.
