### ISSUE TITLE
ksh misparses parentheses in ${var-word}, ${var+word}, ${var:-word}, ${var:+word}

### ISSUE THREAD

**Issue by McDutchie** [att/ast#475]
$ ksh -c 'echo ${var-(word)}'
    ksh: syntax error at line 1: `(' unexpected
    $ ksh -c 'echo ${var-w(or)d}'
    w(or)d
    $ ksh -c 'echo ${var-(wor)d}'
    ksh: syntax error at line 1: `(' unexpected
    $ ksh -c 'echo ${var-w(ord)}'
    w(ord)
    $ ksh -c 'echo ${var-w(ord}'
    ksh: syntax error at line 1: `}' unexpected
    $ ksh -c 'echo ${var-wor)d}'
    ksh: syntax error at line 1: `)' unexpected

Same behaviour with `${var+word`}, `${var:-word}`, and `${var:+word}`.

These syntax errors should not happen; parentheses should not be parsed in this type of parameter substitution, as the `word` is a string literal and not a pattern (unlike `${var#word}`, etc.). [POSIX says](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02) that the `word` is (only) subject to expansion.

This seems to be a regression introduced in early ksh93; "Version M 1993-12-28 s+" has the bug, but on ksh88 (on Solaris) it works as expected. It also works fine on every other current POSIX shell.

**Comment by McDutchie** [comment]
Also see #431 which seems like it could be related.

**Comment by siteshwar** [comment]
For the record, the error is coming from [here](https://github.com/att/ast/blob/448bf23d5621d58c45bdc69a331015627854c120/src/cmd/ksh93/sh/lex.c#L900-L904). But I will avoid touching parser code for now.

**Comment by McDutchie** [comment]
This fix seems incomplete:
```
$ build/src/cmd/ksh93/ksh -c 'echo ${var-w(ord}'
w(ord
$ build/src/cmd/ksh93/ksh -c 'echo ${var:-w(ord}'
build/src/cmd/ksh93/ksh: syntax error at line 1: `}' unexpected
$ build/src/cmd/ksh93/ksh -c 'echo ${var+w(ord}'
build/src/cmd/ksh93/ksh: syntax error at line 1: `}' unexpected
$ build/src/cmd/ksh93/ksh -c 'echo ${var:+w(ord}'
build/src/cmd/ksh93/ksh: syntax error at line 1: `}' unexpected
```
and even stranger (note the third output):
```
$ build/src/cmd/ksh93/ksh -c 'echo ${var-wor)d}'
wor)d
$ build/src/cmd/ksh93/ksh -c 'echo ${var:-wor)d}'
build/src/cmd/ksh93/ksh: syntax error at line 1: `)' unexpected
$ build/src/cmd/ksh93/ksh -c 'echo ${var+wor)d}'
d}
$ build/src/cmd/ksh93/ksh -c 'echo ${var:+wor)d}'
build/src/cmd/ksh93/ksh: syntax error at line 1: `)' unexpected
```

**Comment by krader1961** [comment]
@McDutchie, the fix probably is incomplete. But having just looked at `sh_lex()` because it is the source of an ASAN error I am amazed that @etscrivner even attempted a fix for this issue. That function is more than 1000 lines in length. Which qualifies it for the function most in need of refactoring that I have ever seen in my four decades of programming.

Reopening because the fix doesn't address all possible permutations of the core issue.

**Comment by krader1961** [comment]
Also, note that bash and zsh have different behavior. Here is zsh:

```
macpro% echo ${var-(word)}
zsh: unknown sort specifier
macpro% echo ${var-"(word)"}
(word)
```

Here is bash:

```
bash-4.4$ echo ${var-(word)}
(word)
bash-4.4$ echo ${var-"(word)"}
(word)
```

And ksh93u+:

```
$ echo ${var-(word)}
ksh: syntax error: `(' unexpected
$ echo ${var-"(word)"}
(word)
```

While it appears the bash behavior is probably the most correct of the three this looks like a really obscure corner case. And it is not at all obvious given the informal description of the ksh syntax documented in its man page that the current behavior is wrong.

**Comment by McDutchie** [comment]
zsh is not POSIX compliant by default. To properly compare zsh with other POSIX shells, you should put it in POSIX mode first using the `emulate sh` command (or by symlinking 'sh' to it).

```
$ zsh -c 'emulate sh; echo ${var-(word)}'
(word)
```

To a lesser extent, the same applies to other shells with POSIX modes, including bash. Safer to use 'set -o posix' there.

By the way, zsh has a ksh compatibility mode as well:

```
$ zsh -c 'emulate ksh; echo ${var-(word)}'
(word)
```

…although that emulates something closer to ksh88 than ksh93 (e.g. local variables use dynamic scoping).

> And it is not at all obvious given the informal description of the ksh syntax documented in its man page that the current behavior is wrong.

Since this parameter substitution is specified by POSIX, that [specification](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02) should lead. It states that, in a parameter expansion like `${var-word}`, the `word` is subject to tilde expansion, parameter expansion, command substitution, and arithmetic expansion. Other than those, all that should be done is scan for the final `}`. So we're not in a context where simple parentheses should be special in any way.

**Comment by McDutchie** [comment]
Thanks, it all seems good now.

I made a little test script, feel free to make it into a regression test case (I don't have time to figure out how the regression tests work at the moment).

````
emulate sh 2>/dev/null  # put zsh in posix mode
(set -o posix) 2>/dev/null && set -o posix
unset -v var
for op in - + :- :+; do
	for word in '(word)' 'w(or)d' '(wor)d' 'w(ord)' 'w(ord' 'wor)d'; do
		printf '%s\t%s\t: ' "$op" "$word"
		eval "echo \${var${op}${word}}"
	done
done
````

Expected output:

````
-	(word)	: (word)
-	w(or)d	: w(or)d
-	(wor)d	: (wor)d
-	w(ord)	: w(ord)
-	w(ord	: w(ord
-	wor)d	: wor)d
+	(word)	: 
+	w(or)d	: 
+	(wor)d	: 
+	w(ord)	: 
+	w(ord	: 
+	wor)d	: 
:-	(word)	: (word)
:-	w(or)d	: w(or)d
:-	(wor)d	: (wor)d
:-	w(ord)	: w(ord)
:-	w(ord	: w(ord
:-	wor)d	: wor)d
:+	(word)	: 
:+	w(or)d	: 
:+	(wor)d	: 
:+	w(ord)	: 
:+	w(ord	: 
:+	wor)d	: 
````

Output with the bug (before any of your fixes):
````
-	(word)	: test.sh[8]: eval: syntax error at line 1: `(' unexpected
-	w(or)d	: w(or)d
-	(wor)d	: test.sh[8]: eval: syntax error at line 1: `(' unexpected
-	w(ord)	: w(ord)
-	w(ord	: test.sh[8]: eval: syntax error at line 1: `}' unexpected
-	wor)d	: test.sh[8]: eval: syntax error at line 1: `)' unexpected
+	(word)	: test.sh[8]: eval: syntax error at line 1: `(' unexpected
+	w(or)d	: 
+	(wor)d	: test.sh[8]: eval: syntax error at line 1: `(' unexpected
+	w(ord)	: 
+	w(ord	: test.sh[8]: eval: syntax error at line 1: `}' unexpected
+	wor)d	: test.sh[8]: eval: syntax error at line 1: `)' unexpected
:-	(word)	: (word)
:-	w(or)d	: w(or)d
:-	(wor)d	: (wor)d
:-	w(ord)	: w(ord)
:-	w(ord	: test.sh[8]: eval: syntax error at line 1: `}' unexpected
:-	wor)d	: test.sh[8]: eval: syntax error at line 1: `)' unexpected
:+	(word)	: 
:+	w(or)d	: 
:+	(wor)d	: 
:+	w(ord)	: 
:+	w(ord	: test.sh[8]: eval: syntax error at line 1: `}' unexpected
:+	wor)d	: test.sh[8]: eval: syntax error at line 1: `)' unexpected
````
