### ISSUE TITLE
case: '[0-9]' matches [0-9]

### ISSUE THREAD

**Issue by McDutchie** [att/ast#476]
$ ksh -c 'case "[0-9]" in [0-9]) echo BUG;; *) echo ok ;; esac'
    BUG

Apparently, if the pattern fails to match as a pattern, ksh checks if it matches as a literal string as a fallback.

As Geoff Clare [pointed out on austin-group-l](https://www.mail-archive.com/austin-group-l@opengroup.org/msg02127.html), this breaks a common input validation use case:

    case $input in
    [0-9]) ;;
    *) echo "Input must be a single digit"; exit ;;
    esac

This will fail to catch an error if `"$input"` equals `'[0-9]'`.

This is historical behaviour going back to ksh88 and the historical Bourne shell, but it's completely broken and no other current POSIX shell of note implements it.

It directly contravenes the text of the POSIX standard, which says unquoted `[0-9]` is a bracket pattern and not a literal string.

**Comment by kernigh** [comment]
The form `[[ $x = [0-9] ]]` correctly rejects '[0-9]'; only the form `case "$x" in [0-9])...` is broken. (In bash and zsh, both forms reject '[0-9]'.)

```
for x in 2 '[0-9]'; do
	[[ $x = [0-9] ]] && y="matches" || y="doesn't match"
	echo "$x $y [0-9] in [[ ... ]]"
	case "$x" in
	[0-9]) y="matches";;
	*)     y="doesn't match";;
	esac
	echo "$x $y [0-9] in case"
done
```

```
$ type nksh
nksh is an alias for /home/kernigh/park/ast/build/src/cmd/ksh93/ksh
$ nksh try.sh
2 matches [0-9] in [[ ... ]]
2 matches [0-9] in case
[0-9] doesn't match [0-9] in [[ ... ]]
[0-9] matches [0-9] in case
```

**Comment by McDutchie** [comment]
Yes, the only other shells that have this behaviour in `case` are the historical ksh88 and Bourne shells. All other POSIX shells have left this breakage behind and so should ksh93.

This behaviour is so broken I suspect Stephen Bourne meant to temporarily add a literal string comparison for debugging purposes sometime in the late 70s and then forgot to remove it, so it took on a life of its own.

**Comment by kernigh** [comment]
The fix is to delete this call to trim_eq(). TODO delete unused trim_eq() function, write test.

```diff
diff --git a/src/cmd/ksh93/sh/xec.c b/src/cmd/ksh93/sh/xec.c
index 6824ac5f..8768ffea 100644
--- a/src/cmd/ksh93/sh/xec.c
+++ b/src/cmd/ksh93/sh/xec.c
@@ -2258,7 +2258,7 @@ int sh_exec(Shell_t *shp, const Shnode_t *t, int flags) {
                         }
                         type = (rex->argflag & ARG_RAW);
                         if ((type && strcmp(r, s) == 0) ||
-                            (!type && (strmatch(r, s) || trim_eq(r, s)))) {
+                            (!type && strmatch(r, s))) {
                             do {
                                 sh_exec(shp, t->reg.regcom,
                                         (t->reg.regflag ? (flags & sh_state(SH_ERREXIT)) : flags));
```

**Comment by siteshwar** [comment]
@kernigh Please also make a note of it in `CHANGELOG.md`.
