### ISSUE TITLE
ksh -u or 'set -o nounset' behaviour for undefined positional parameter like $1.

### ISSUE THREAD

**Issue by lijog** [att/ast#5]
This is an issue which was reported earlier in the ast-developers forum, details can be found at 
https://www.mail-archive.com/ast-developers@lists.research.att.com/msg01906.html

I've observed the issue in the beta, alpha and master versions.  
I've applied the following patch( for alpha and the master version) to fix the issue. 

--- INIT.2013-10-10/src/cmd/ksh93/sh/macro.c    2015-11-12 03:05:54.008417740 -0800
+++ INIT.2013-10-10/src/cmd/ksh93/sh/macro.c     2016-03-14 11:15:32.158386840 -0700
@@ -1220,7 +1220,7 @@
                {
                        d=fcget();
                        fcseek(-1);
-                       if(!strchr(":+-?=",d))
-                       if(d=='\0'  || !strchr(":+-?=",d))
                              errormsg(SH_DICT,ERROR_exit(1),e_notset,ltos(c));
              }
              break;

**Comment by siteshwar** [comment]
It shoudl be fixed by #47
