### ISSUE TITLE
Should `SHOPT_HISTEXPAND` be removed or made the default

### ISSUE THREAD

**Issue by krader1961** [att/ast#503]
While working on issue #210 I noticed build time symbol `SHOPT_HISTEXPAND`. It is present in the last stable release (version ksh93u+) and is enabled by default in that build. The `hist -p` flag it enables is not documented in the `man ksh` output. It is, however, available in that version and using it produces no error (unlike, say, `hist -z`).

That build time symbol is also present in the current beta release (the `2016-01-10-beta` branch) but is no longer enabled by default. In fact, if you type `hist -p` you get dropped into your preferred editor and upon exiting it you're told that `hist -a` is invalid.

If I explicitly enable `SHOPT_HISTEXPAND` then the build fails because the `hist_expand()` function now takes three arguments but the invocation hidden behind that build symbol only passes two parameters.

P.S., I have no idea what this feature is intended to do since the `csh` command doesn't seem to have a `-p` flag for its `history` command. The code for the ksh93u+ release says:

```
SHOPT_HISTEXPAND == 1            /* csh-style history file expansions */
```

I vote we drop this build time symbol and the code predicated on it.

**Comment by krader1961** [comment]
> P.S., I have no idea what this feature is intended to do since the csh command doesn't seem to have...

Yes, I could dig deeper into the ksh code to understand what enabling this "feature" does. That isn't the point. The point is that the feature isn't documented in the last stable release. So it should be safe to remove. Too, it isn't enabled in the current branch and doesn't build if enabled.

**Comment by siteshwar** [comment]
It is documented under `history --help` and is used to see output of history expansions (when histexpand is turned off). For e.g. `history -p !2` will show second command from history. Despite of it's questionable usefulness, I will prefer to keep it.

@krader1961 I will take care of fixing it.

**Comment by krader1961** [comment]
FWIW, my comment about it being undocumented pertains to the man page. The fact that internal documentation differs from the man page is itself another, big, problem. Note that `hist --help` also lists a `-N` flag that is not in the man page.
