### ISSUE TITLE
How to enable CI for non-Linux operating systems ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#515]
Currently we have setup Travis builds for fedora and opensuse only. Travis has support for macOS but we have not found a way to integrate it in our current setup. I would like to hear ideas about how we can enable CI for non-Linux operating systems like macOS, different BSDs etc.

**Comment by dannyweldon** [comment]
What about something like:

    matrix:
        include:
            - os: linux
            - env: OS_TYPE=fedora
            - env: INSTALL_REQUIREMENTS="dnf repolist; dnf install -y gcc meson sudo langpacks-zh_CN ed ncurses vi"
    
            - os: linux
            - env: OS_TYPE=opensuse
            - env: INSTALL_REQUIREMENTS="zypper refresh; zypper in -y gcc python3 python3-pip ninja sudo glibc-locale glibc-devel ed ncurses-utils vim; pip3 install meson==0.44.0"
    
            - os: linux
            - env: OS_TYPE=dauchida/freebsd
            - env: INSTALL_REQUIREMENTS="pkg install ..."
    
            - os: osx
            - env: OS_TYPE=osx
            - env: INSTALL_REQUIREMENTS="brew update; brew install ..."

    before_install:
        - [[ $TRAVIS_OS_NAME == "linux" ]] && docker pull ${OS_TYPE}
    
    script:
        # Test for osx and run different build or prep commands:
        - [[ $TRAVIS_OS_NAME == "osx" ]] && ...
        - [[ $TRAVIS_OS_NAME == "linux" ]] && ...

I'm not sure if the above will work, but you get the idea.  The script will get a bit messier but it will get the job done.

Adapted from:

https://docs.travis-ci.com/user/multi-os/#Python-example-(unsupported-languages)

**Comment by krader1961** [comment]
I looked into enabling macOS (OS X) for this project long ago but couldn't find a way to do so with a docker based config. What I didn't consider was seeing if OpenSuse and Fedora could be installed using a non-docker based config as in @dannyweldon's example.

I do agree that we should add a mainstream Linux distro (e.g., Ubuntu), macOS, and one other BSD flavor (either FreeBSD or OpenBSD). That should be plenty of CI coverage. Other platforms (e.g., Cygwin, Solaris, Haiku) can be tested adhoc by those with an interest in running ksh on those platforms.

**Comment by siteshwar** [comment]
@dannyweldon Thanks for the hint. Your example may work with our set up.

At this point I am more concerned about BSDs. I don't want to test it with any non-official BSD docker images. My experience with BSDs is pretty limited. Is anyone subscribed to this repository work on BSD (any BSD) and can give us a hint how they handle CI for GitHub projects ?

**Comment by kernigh** [comment]
Travis runs Linux. I believe that Linux can't run [auchida/freebsd](https://hub.docker.com/r/auchida/freebsd/). It says, "FreeBSD Docker host is required to run this image, consult [Docker on FreeBSD](https://wiki.freebsd.org/Docker) for detail." Linux doesn't emulate FreeBSD system calls, but [FreeBSD does emulate Linux system calls](https://www.freebsd.org/cgi/man.cgi?query=linux), so Docker on FreeBSD can try Linux images.

I run OpenBSD. I can't remember any GitHub project that did CI on OpenBSD, except maybe [factor/factor](http://github.com/factor/factor/) until year 2011. [Factor does CI](http://builds.factorcode.org/dashboard) with [its own build farm](http://concatenative.org/wiki/view/Factor/Build%20farm). Years ago, the farm made official builds of Factor 0.94 for FreeBSD, NetBSD, and OpenBSD. Factor [dropped support for those BSDs in 2011](https://github.com/slavapestov/factor/commit/75cba3106afda4a8729edbb376d421446ab04af7), so any CI on OpenBSD must have stopped by then. [Factor also uses Travis on Linux and macOS](https://travis-ci.org/factor/factor); its [.travis.yml](https://github.com/factor/factor/blob/master/.travis.yml) suggests that Travis on macOS is difficult. Factor's farm doesn't look at GitHub pull requests; Travis does.

**Comment by krader1961** [comment]
@kernigh Note that @dannyweldon's example config implies that macOS, a BSD like OS, can be installed via Docker. I haven't tested that but if it works it should be possible to do the same thing for OpenBSD or FreeBSD. However I suspect his example won't work based on my investigation from ~6 months ago. And your comment reinforces that conclusion.

The only way to get macOS to work is to use the non-Docker based virtual machine Travis setup such as the [Fish shell uses](https://github.com/fish-shell/fish-shell/blob/master/.travis.yml#L62-L66). And I couldn't discover a way to mix the docker and non-docker based test environments. Which implies that unless Travis supports BSD based environments "natively" (i.e., as a VM) it won't work.

**Comment by dannyweldon** [comment]
Okay, you are correct.  The whole point of Docker is that it's a wrapper around Linux containers, so it won't be able to run non-Linux containers.  So my example would only benefit from being able to run builds for OS X, but would still be limited to whatever version is used by Travis CI.

Another idea I was going to suggest then would be to use Vagrant inside Travisi and spin up various OS flavours with that, but a check with Google shows that Virtualbox is not supported.  I had done some work locally a while ago, before we started using Travis, to create a multi-os Vagrantfile for ksh with various OS flavours including CentOS, Fedora, macOS, and Windows (for Cygwin), with plans to add Solaris and Ubuntu.  Not all of these are working correctly yet.  The idea was that developers, once their code worked on their host machine, could then spin up each OS for compatibility testing.  Of course, it's not true CI though.

**Comment by siteshwar** [comment]
@krader1961 I have a `.travis.yml` in [this branch](https://github.com/siteshwar/ast/commits/gh515) that works with both Linux docker builds and macOS . I don't have a mac machine and it's been a while since I built this project on macos, so I don't recall exact steps. You can pull from my branch and add the steps under `scripts/build-on-macos.sh`.

**Comment by siteshwar** [comment]
@dannyweldon For Linux and macOS we will continue to use Travis. It's been many years since I used vagrant. If you can provide us a vagrantfile that can be used to do builds on different BSDs on our local machines, I would use it. But I will prefer to use kvm as backend rather than VirtualBox.

**Comment by krader1961** [comment]
FWIW, I was surprised to see the newly added macOS travis build passing the tests since I'm seeing 22 test failures on my workstation. The last line in the travis log is

```
/Users/travis/.travis/job_stages: line 57: shell_session_update: command not found
```

This issue might help us figure out why that is happening: https://github.com/travis-ci/travis-ci/issues/6307

**Comment by siteshwar** [comment]
@krader1961 I am not running test cases on macOS builds. I think we should not enable them until they are fixed.

**Comment by krader1961** [comment]
> I am not running test cases on macOS builds. I think we should not enable them until they are fixed.

Doh! /face-palm on my part

But we should be able to enable them while also keeping macOS test failures from causing Travis to report a failure. That would a) eliminate the unexpected "command not found" error I noted, b) make it obvious to someone looking at the macOS environment results to recognize the tests ran but had failures, and c) tell us that we can actually run the tests on Travis's macOS environment with results comparable to what I'm seeing on my workstation. I'll take a stab at doing that.

**Comment by siteshwar** [comment]
Also, I wrote a simple [Vagrantfile](https://github.com/siteshwar/ast/blob/vagrant-freebsd/Vagrantfile) that can be used to test on `FreeBSD`. But I will avoid commiting it in `master` unless someone else asks for it.

**Comment by siteshwar** [comment]
Since we have already enabled CI for macOS and it does not seem trivial to enable it for other operating systems, I am going to close this issue.

**Comment by siteshwar** [comment]
I managed to set up some custom infrastructure and starting yesterday we have CI for FreeBSD. It's still in early stages, but hopefully it will get better over time.
