### ISSUE TITLE
Remove poll builtin

### ISSUE THREAD

**Issue by siteshwar** [att/ast#528]
This builtin was added after `ksh93u+` release:

```
12-08-21  The poll builtin from Roland Mainz has been added with the option                                           
      SHOPT_POLL.
```

I will prefer not to include it in the next release.

**Comment by krader1961** [comment]
I'll admit my first reaction was to say "hold on, this might be useful." Then I read the documentation embedded in *src/cmd/ksh93/bltins/poll.c*. Gah! It's just exposing the low-level `poll()` syscall with no attempt to provide a higher level abstraction more appropriate for a shell script. Furthermore, I can't imagine anyone writing the type of application that needs `poll()` (e.g., a web server) as a ksh script. Other than as a "hey, look what I managed to do" type of experiment. So, yes, let's ditch this.
