### ISSUE TITLE
Enable test cases for ksh builtins

### ISSUE THREAD

**Issue by siteshwar** [att/ast#533]
There are some tests for ksh builtins listed under `src/cmd/builtin`. These test cases are run by `src/cmd/INIT/regress.sh` script which was removed through 9e54c8eafb7fcd1bef314f9d2e8a1d00fa4fcee4. We should restore this script and start running these test cases.

**Comment by krader1961** [comment]
@siteshwar, I think this issue should be closed. No one is ever going to expend the effort to reinstate that script and modernize it and its associated unit tests. Also, 98% of those tests are no longer relevant. And those that are still relevant should be, and probably are, handled by other tests.

**Comment by krader1961** [comment]
Closing for the reasons listed in my previous comment.
