### ISSUE TITLE
Variables created with the "${:=}" substitution following "set -a"

### ISSUE THREAD

**Issue by gwatt** [att/ast#537]
After running `set -a`, variables subsequently created with the `${:=}` substitution are not exported as environment variables but they are created in the session's local environment.
Is this behavior expected? I was hoping that `set -a` before `${:=}` would export the created variables.

My specific use-case is that I have a test-suite that uses many environment variables. Most of these variables can be automatically determined based on the environment and the service, but I want to allow easy overrides.

I know I can do `var=${var:-value}` to achieve the same effect, but I dislike typing every variable name twice.

**Comment by siteshwar** [comment]
This is the output I receive with latest build from `master`:
```
$ set -a
$ foo=${bar:=baz}
$ echo $foo
baz
$ bash
(bash) $ echo $foo
baz
```

It works as expected.

**Comment by krader1961** [comment]
I was testing with

```
$ set -a
$ echo ${bar:=baz}
$ env | grep bar
```

The point of the issue is that the creation of `bar` via the implicit `${bar:=baz}` assignment doesn't automatically export it when `set -a` is in effect. And it seems like it should and does so in bash and zsh.

**Comment by gwatt** [comment]
@siteshwar In your code snippet I would also expect `bar` to be an exported environment variable, which is not what happens.
In my script I've been doing the following:
```
set -a
: ${a:=a}
: ${b:=b}
: ${c:=c}
...
```
In this case I want a, b, c, etc to be exported for use in child processes.

**Comment by siteshwar** [comment]
For reference, this is the POSIX specification for `${:=}`:
```
${parameter :=word}
Assign Default Values. If parameter is unset or null, the expansion of
word shall be assigned to parameter. In all cases, the final value of
parameter shall be substituted. Only variables, not positional parameters
or special parameters, can be assigned in this way.
```

and `set -a`:

```
−a When this option is on, the export attribute shall be set for each variable to which an
assignment is performed; see the Base Definitions volume of IEEE Std 1003.1-2001, Section
4.21, Variable Assignment. If the assignment precedes a utility name in a command, the
export attribute shall not persist in the current execution environment after the utility
completes, with the exception that preceding one of the special built-in utilities causes the
export attribute to persist after the built-in has completed. If the assignment does not
precede a utility name in the command, or if the assignment is a result of the operation of
the getopts or read utilities, the export attribute shall persist until the variable is unset.
```

**Comment by siteshwar** [comment]
@krader1961 I agree it should be considered a bug.
