### ISSUE TITLE
ksh should show proper error message if command inside back quote ends in a quote

### ISSUE THREAD

**Issue by siteshwar** [att/ast#54]
```
for f in `ls -d /home/*"`; do echo $f; done
ls: cannot access /home/*
: No such file or directory
```
should show the same error as when using $():

```
for f in $(ls -d /home/*"); do echo $f; done
ksh: syntax error: `"' unmatched
```

**Comment by stephane-chazelas** [comment]
ksh (like its predecessor the Bourne shell) has been traditionally lax about matching quotes (backtick there being considered one of those quotes). While I agree that doesn't make for a very clean syntax and encourages dirty coding, that could be considered as a feature (and fixing it would probably cause backward portability issues). As ksh93 was a rewrite, I suspect the behaviour was intentional for backward portability with ksh88.

See also

```
echo "`uname"
```

And it not complaining about missing heredoc terminators

**Comment by siteshwar** [comment]
Thanks @stephane-chazelas for the insightful comment. @krader1961 @kdudka I would appreciate your views on this issue. I don't see it as a major bug and we can close it without fixing.

**Comment by krader1961** [comment]
Normally I would agree that the parser should be modified to treat the unmatched quote as an error. That is, this is a bug. However, the backtick mechanism is deprecated in favor of the `$(...)` syntax. And given that any change made to the associated code is likely to cause problems it seems like a bad idea to try and "fix" this.

However, in ksh93u+ the unmatched trailing quote simply causes the glob expansion to be inhibited. While in the current code it inhibits the glob expansion and adds a trailing newline to the string. So once again we see the AST team making a change that is not backward compatible and introduces a new bug. Where did the newline come from?

So we have three choices:

1) Revert to the ksh93u+ behavior.

2) Make the backtick and `$(...)` forms throw the same syntax error.

3) Shrug our shoulders and accept that anyone relying on the legacy behavior deserves to have their script broken.

**Comment by kdudka** [comment]
Do we actually have a fix for this?  I would personally avoid any changes in the parsing logic unless they are really necessary because they often trigger unwanted side effects.

**Comment by siteshwar** [comment]
@kdudka No fix for it yet.

**Comment by siteshwar** [comment]
@krader1961 I think suggestion 3 is a good choice for now. I would rather wait and see if it actually breaks any scripts.
