### ISSUE TITLE
Bug in sh_setsiginfo() corrupts memory

### ISSUE THREAD

**Issue by krader1961** [att/ast#556]
I was testing my change to replace Vmalloc with the system malloc. That change works fine on my 64 bit systems. However, on Ubuntu 16.04 32 bit, the very first test in the `sigchld` unit test causes a SIGSEGV. That's because of this statement in `sh_setsiginfo()`:

```
strncpy(signame, p, SIGNAME_MAX);
```

The problem is that `signame` points to a buffer just 16 bytes before the structure pointed to by `SH_SIG->nvfun` (aka `(shgd->bltin_nodes + 66)->nvfun`). And because `SIGNAME_MAX` is 32 that `strncpy()` modifies the first four words of the `Namfun_t` structure that follows it. Which sets the `disc` member of that structure to NULL. Which leads to a SIGSEGV when it is dereferenced by this statement in `sh_setsiginfo()` the next time it runs:

```
while (fp->disc->createf != create_svar) fp = fp->next;
```

TBD is whether the target buffer pointed to by `signame` should be at least `SIGNAME_MAX` in length or this is a misuse of `strncpy()`.

**Comment by krader1961** [comment]
Also, that code shouldn't even need to use `strncpy()` since it is copying a constant string that is guaranteed to be a reasonable length. It is not copying a string obtained from an external source. So a simple `strcpy()` is safe to use in this case.

**Comment by DavidMorano** [comment]
@krader1961 
> I am sorely tempted to swear like a sailor after investigating this issue. ...

I feel your pain. I would have converted the code files to C++ (probably the latest version) by now and have written access methods for the crazier (or all) accesses to the original objects!

Coming from a hard-core porno object-oriented well and highly abstracted code background myself, seeing code like this is hard. It is hard for most anyone who has coded in a more modern style over the last 25+ years or so. It is a test -- everyday -- of your mental ability to "hold on" and to "keep it together" mentally.  I have been there, and sadly, I am there right now also -- dealing with old code like what you are seeing now in the KSH base.

So please keep the faith, and know that others have your back!
