### ISSUE TITLE
Failed to build on armv7l

### ISSUE THREAD

**Issue by kekePower** [att/ast#558]
**Description of problem:**
Build fails on armv7

**Ksh version:**
Git master 2018-05-29

Here is the build log
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20180529213558.kekepower.duvel.47174/log/ksh-20180529_gitebe3b505-0.1.mga7/build.0.20180529213610.log

I don't know if it's related to the removal og vmalloc or not, but the build before this one worked fine.

Cheers.

**Comment by siteshwar** [comment]
Build is failing at this point:

```
../src/cmd/tests/sfio/tbadargs.c: In function ‘main’:
../src/cmd/tests/sfio/tbadargs.c:59:30: error: incompatible type for argument 4 of ‘sfvsprintf’
     CALL(sfvsprintf(0, 0, 0, 0));
                              ^
../src/cmd/tests/sfio/tbadargs.c:27:43: note: in definition of macro ‘CALL’
 #define CALL(x) ((Code_line = __LINE__), (x))
                                           ^
In file included from ../src/cmd/tests/sfio/../../../lib/libast/include/sfio_t.h:59:0,
                 from ../src/cmd/tests/sfio/sftest.h:27,
                 from ../src/cmd/tests/sfio/tbadargs.c:22:
../src/cmd/tests/sfio/../../../lib/libast/include/sfio.h:246:16: note: expected ‘va_list {aka __va_list}’ but argument is of type ‘int
```

It looks like definition of `va_list` slighty varies on armv7 and it is invalid to initialize variable of this type with `0`. I wonder why this was not caught before.

**Comment by krader1961** [comment]
It is very unlikely the change that removed AST Vmalloc is the culprit. If you `git checkout 11398511e` (the change preceding the AT Vmalloc removal) does it actually compile?

**Comment by kekePower** [comment]
@krader1961 I guess you're right.

The last version I pushed was from 20180520, so something has changed between then and now.
Will now try to push another version to see if it builds.

**Comment by krader1961** [comment]
@kekePower Can you confirm that https://github.com/att/ast/pull/559 fixes this for you?

**Comment by siteshwar** [comment]
Also, I think we should give an option to compile out api tests. Not every package maintainer would like to build them.

**Comment by kekePower** [comment]
@krader1961 Failed as well.

http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20180530224939.kekepower.duvel.7919/log/ksh-20180531_git9c99e73a-0.1.mga7/build.0.20180530225342.log

**Comment by krader1961** [comment]
@kekePower, by "try again" I mean to apply #556 again. All four function calls that need to pass a `va_list` instead of zero as the final arg now do so and that should fix the build failures you're seeing.

**Comment by kekePower** [comment]
Thank you @krader1961 

The last update to 559 did the trick.

http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20180531060206.kekepower.duvel.47763/ksh-20180531_git9c99e73a-0.2.mga7/build.0.20180531060313.log
