### ISSUE TITLE
Ksh fails to start if current directory is not accessible

### ISSUE THREAD

**Issue by siteshwar** [att/ast#567]
**Description of problem:**
Ksh fails to start if current directory is not accessible

**Ksh version:**
ksh-20180526+git.945.4ed72ac1-0.fc27.x86_64

**How reproducible:**
Always

**Steps to reproduce:**
1. mkdir /tmp/foo
2. chmod o-rwx /tmp/foo
3. useradd test
4. cd /tmp/foo
5. su -c "ksh" test

**Actual results:**
ksh: Can't obtain directory fd. [Permission denied]

and ksh fails to start.

**Expected results:**
ksh should start.

**Additional info:**
Here is the code from `src/cmd/ksh93/sh/init.c` that throws this error:

```
    // This should _never_ happen, guaranteed by design and goat sacrifice.
    if (shp->pwdfd < 0) errormsg(SH_DICT, ERROR_system(1), "Can't obtain directory fd.");
```

We should not need another goat sacrifice to fix it.

**Comment by krader1961** [comment]
Note that this works with ksh93u. It's also not necessary to create a dummy user account. Just do this instead:

1. mkdir /tmp/foo
1. cd /tmp/foo
1. chmod 0 .
1. ksh
