### ISSUE TITLE
Replace the AST locale subsystem with the system version

### ISSUE THREAD

**Issue by krader1961** [att/ast#579]
We recently replaced the AST Vmalloc subsystem with the system malloc subsystem. In the process numerous bugs were found that were being masked by Vmalloc. It also allowed us to shed over 10000 LOC that no longer needs to be maintained. I'm proposing we replace the AST locale subsystem with the system provided one. Because that may be difficult we might want to start by removing or disabling AST features that are not found in GNU or BSD locale subsystems. For example, env vars like `LC_OPTIONS=nounicodeliterals`. This would at least keep us from being locked into the AST implementation forever.

**Comment by krader1961** [comment]
Something I didn't realize until just now is that the AST locale support can selectively use the native implementation. For example, if the native *wchar.h* header defines `iswprint` as a macro it is used rather than the AST implementation. See https://github.com/att/ast/issues/577#issuecomment-394929360. That caused me to Picard face-palm.

**Comment by krader1961** [comment]
This is going to take many more commits than the removal of AST Vmalloc needed but it is definitely doable. The first round of changes has removed ~2200 LOC. At this point `ksh` is using the platform's locale subsystem. The bits of the AST locale subsystem still present are solely because I want to do this in as many bite size changes as possible to minimize the chance of a stupid mistake. And if such a mistake is made it should be easier to bisect. Too, there are a couple of bits of logic which still need to be implemented on top of the platform's locale subsystem.

**Comment by krader1961** [comment]
It is really annoying how many places directly access what should be a private locale subsystem var such as `locales[]`. Either directly or indirectly via the `LCINFO()` macro. Annoying because it both obscures the purpose of the access and makes it harder to replace the AST locale subsystem with the platform implementation. Many, if not all, of these accesses appear to be done in the name of efficiency. Which is rarely a legitimate reason and definitely not so in any of the cases I've examined.

Despite my metaphorical teeth grinding as evidenced by the previous paragraph I think I'm close to being able to eliminate almost all of the AST locale implementation. Which mostly just wraps the native implementation other than the `C` and `C.UTF-8` locales which are special-cased and implemented directly by AST. Most of the references to the private implementation details can be replaced by calls to `setlocale(..., NULL)` or `nl_langinfo()`. I'm down to just two modules which have somewhat more complex interactions by virtue of modifying the AST locale subsystem state.

**Comment by siteshwar** [comment]
Although the tests are passing in CI. I am getting these failures on my fedora 27 machine:

```
<I> locale[-1]: TEST_DIR=/tmp/ksh.locale.93yddPU
<I> locale[201]: TODO: Enable the `join` test when it is a builtin again (issues #411, #129).
<E> locale[220]: multibyte variable definition/expansion failed
<E> expect: |OK|
<E> actual: ||
<E> locale[223]: multibyte ksh function definition/execution failed
<E> expect: |OK|
<E> actual: |/home/situ/upstream/ast/build/src/cmd/ksh93/ksh: \u[0101]: invalid function name|
<E> locale[225]: multibyte posix function definition/execution failed
<E> expect: |OK|
<E> actual: |/home/situ/upstream/ast/build/src/cmd/ksh93/ksh: syntax error at line 1: `(' unexpected|
<E> locale[292]: unicode chars 1680,2000,2001,2002,2003,2004,2005,2006,2008,2009,200a,2028,2029,3000 are not space characters in locale en_US.UTF-8
<E> locale[305]: incorrect
<E> expect: |string|
<E> actual: |from|
<E> locale[316]: locales not handled correctly in command substitution
<W> locale[-1]: error_count = 6
1/1 locale/C                                FAIL     0.12 s (exit status 6)
```

**Comment by krader1961** [comment]
@siteshwar All tests pass for me on Fedora 28 server edition. Does your server have locale `en_US.UTF-8` installed? Because those errors are exactly what you'll get if the locale is invalid.

**Comment by siteshwar** [comment]
Running `locale -a | grep -i en_US` gives me this output:

```
en_US
en_US.iso88591
en_US.iso885915
en_US.utf8
```
On a clean f27 installation which have exactly same locales, all tests are passing. So either there is a configuration issue on my system or we are hitting some undefined behavior.

**Comment by krader1961** [comment]
@siteshwar What does `env -i LC_ALL=en_US.UTF-8 locale` output? On Fedora 28 that works even though it too has `en_US.utf8` as the canonical locale name. On the other hand if I run the invalid `env -i LC_ALL=en_US.UTF-88 locale` it complains that it `Cannot set LC_ALL to default locale`. What I'm hoping is that on Fedora 27 it is simply failing to correctly transform the non-canonical name to the canonical name. In which case the fix is for the unit test preamble to determine the correct canonical name, assign it to a var, and use the var everywhere we currently hardcode `en_US.UTF-8`.

**Comment by siteshwar** [comment]
> What does env -i LC_ALL=en_US.UTF-8 locale output? 

```
> env -i LC_ALL=en_US.UTF-8 locale 
LANG=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by siteshwar** [comment]
`git bisect` leads me to d02d10d69a1e4086ff11cd4d3760121576c9a65c as the culprit. Reverting this commit fixes the failures.

**Comment by siteshwar** [comment]
@krader1961 It looks like we need to fix `./features/syslocale.sh` script. Running it on my system produces:

```
utf8
```

I put this patch in `set_ctype` function:


```
iff --git a/src/lib/libast/comp/setlocale.c b/src/lib/libast/comp/setlocale.c
index 4ebbce22..495c7f21 100644
--- a/src/lib/libast/comp/setlocale.c
+++ b/src/lib/libast/comp/setlocale.c
@@ -158,6 +158,7 @@ static int (Lc_category_t *cp) {
     }
 
     const char *codeset = nl_langinfo(CODESET);
+    fprintf(stderr, "codeset: %s\t _locale_utf8_str: %s \t is_utf8: %d\n", codeset, _locale_utf8_str, strcmp(codeset, _locale_utf8_str) == 0);
     ast.locale.is_utf8 = strcmp(codeset, _locale_utf8_str) == 0;
     ast.mb_width = wcwidth;
     ast.mb_cur_max = MB_CUR_MAX;
```

and got:

```
codeset: UTF-8   _locale_utf8_str: utf8          is_utf8: 0
```

This is causing rest of the tests to fail.

**Comment by krader1961** [comment]
I'll bet that if you `grep _locale_utf8_str build/config_ast.h` it will show `utf8`. That commit expected that the build time feature test for the canonical spelling of the UTF-8 codeset is actually useful. But since GNU locale does not return the normalized locale string when making calls like `setlocale(LC_LANG, NULL)` or `nl_langinfo(CODESET)` it the result of that build time feature test isn't useful. It sure would have made everyone's lives easier if this stuff had been standardized. See #412.

I'll drop the useless feature test and change the affected code to do string insensitive compares against the two known spellings; i.e., with and without the hyphen.

**Comment by krader1961** [comment]
At this stage I judge the AST locale subsystem removal to be 99.9% complete. There are indirect function pointers in the `_ast_info` structure that could still be removed. But I'm going to leave those for the moment just in case we need to install wrappers to debug problems introduced by this series of changes.
