### ISSUE TITLE
mkdir builtin does not set ACL attributes correctly

### ISSUE THREAD

**Issue by siteshwar** [att/ast#585]
**Description of problem:**
`mkdir` builtin is not SELinux aware, so it does not set ACL attributes correctly.

**Ksh version:**
ksh-20180608+git.982.3d409346-0.el7.x86_64

**How reproducible:**
Always

**Steps to reproduce:**
Run this script as root:

```
#!/bin/ksh
dd if=/dev/zero of=image count=512
mke2fs -F image
mkdir acl_test
mount -o acl,loop image acl_test

print "Creating testing users"

useradd acl1
useradd acl2

print "Creating the testing directory and setting its permissions"

cd acl_test
umask 0002
mkdir acl
setfacl -m d:u:acl1:rwx acl
setfacl -m d:u:acl2:rwx acl

setfacl -m u:acl1:rwx acl
setfacl -m u:acl2:rwx acl

print "Trying umask"

ksh_output=`su acl1 -c 'ksh -c "cd acl;
    umask 777;
    umask;"' 2>&1`

print $ksh_output

if [ $ksh_output != "0777" ]; then
	print "FAIL: the umask was not set to 0777"
	RESULT=FAIL
else
	print "PASS: umask ok"
fi

print "Creating file 'test' and directory 'test_dir'"

su acl1 -c 'ksh -c "cd acl;
    umask 777;
    touch test;
    builtin mkdir 2>/dev/null;
    mkdir test_dir"'

print "Listing ACLs ..."

su acl1 -c 'ksh -c "cd acl;
    getfacl test test_dir;"' 2>&1 > ../ksh_output

print $RESULT
```

**Actual results:**
`ksh_output` file contains:

```
# file: test
# owner: acl1
# group: acl1
user::rw-
user:acl1:rwx   #effective:rw-
user:acl2:rwx   #effective:rw-
group::rwx      #effective:rw-
mask::rw-
other::r--

# file: test_dir
# owner: acl1
# group: acl1
user::---
user:acl1:rwx   #effective:---
user:acl2:rwx   #effective:---
group::rwx      #effective:---
mask::---
other::---
default:user::rwx
default:user:acl1:rwx
default:user:acl2:rwx
default:group::rwx
default:mask::rwx
default:other::r-x
```

**Expected results:**
`ksh_output` file should contain:

```
# file: test
# owner: acl1
# group: acl1
user::rw-
user:acl1:rwx	#effective:rw-
user:acl2:rwx	#effective:rw-
group::rwx	#effective:rw-
mask::rw-
other::r--

# file: test_dir
# owner: acl1
# group: acl1
user::rwx
user:acl1:rwx
user:acl2:rwx
group::rwx
mask::rwx
other::r-x
default:user::rwx
default:user:acl1:rwx
default:user:acl2:rwx
default:group::rwx
default:mask::rwx
default:other::r-x
```

**Additional info:**
This was fixed in fedora by disabling `mkdir` builtin: https://src.fedoraproject.org/cgit/rpms/ksh.git/tree/ksh-20070328-builtins.patch

**Comment by siteshwar** [comment]
@krader1961 It turns out that it will be very hard to get it's functionality right. Do you prefer to remove this builtin or document it's limitations ?

**Comment by krader1961** [comment]
This sort of incompatibility between a ksh builtin and the external command of the same name is inevitable and is certain to affect more commands than just `mkdir`. I don't think this issue by itself warrants removing the builtin. It's not clear it needs to be documented either. Other than in a generic "Every ksh builtin that mirrors an external command may have different flags and behavior."

Did Fedora disable it because it was enabled by default? Which is a problem we've already noted. None of the builtins that were created to explicitly mirror an external command (as opposed to accidentally having the same name) should be enabled by default. Precisely because of issues like this one.

**Comment by siteshwar** [comment]
I checked that the [original bug](https://bugzilla.redhat.com/show_bug.cgi?id=222985) (private) was reported against RHEL-4.4. I think this builtin was enabled by default at that time, so just keeping it disabled by default should be fine.

**Comment by siteshwar** [comment]
Closing as not a bug.
