### ISSUE TITLE
ksh93 dumps core in emacs mode while entering characters in different locale.

### ISSUE THREAD

**Issue by lijog** [att/ast#6]
I observed this issue in a Solaris 11 system on ksh2012-08-01, ie the master version. I guess this issue is present in the later versions too as the relevant code has not changed.

The issue can be reproduced if we add Asian locales to ibus (such as Korean).
In the ksh93 shell prompt, input some Asian character. ksh promptly dumps core with the following stacktrace.

bash-4.2$ pstack core 
core 'core' of 1134:    ksh 
 00000000004f1cf4 ed_emacsread () + 404 
 00000000004a5096 slowread () + 116 
 0000000000592d12 sfrd () + 482 
 000000000058b707 _sffilbuf () + 297 
 00000000005936ac sfreserve () + 2ac 
 0000000000477ae2 exfile () + 6e2 
 0000000000477393 sh_main () + af3 
 00000000004767dd main () + 4d 
 0000000000476614 ???????? () 

The coredump happens at the following line no 320 in src/cmd/ksh93/edit/emacs.c
   i.e if(c!='\t' && c!=ESC && !isdigit(c)). 

I referred the vi.c code and added the digit(c) macro, i.e
 ((c&~STRIP)==0 && isdigit(c)) and replaced the isdigit(c) usage with the "digit(c)" macro. Here's the patch which fixes the issue for me.

--- INIT.2012-08-01.old/src/cmd/ksh93/edit/emacs.c      2016-01-18 03:52:58.380801240 -0800
+++ INIT.2012-08-01/src/cmd/ksh93/edit/emacs.c  2016-02-05 01:39:08.350312914 -0800
@@ -90,6 +90,7 @@
     static int print(int);
     static int _isword(int);
 #   define  isword(c)  _isword(out[c])
+#   define digit(c)    ((c&~STRIP)==0 && isdigit(c))

 #else
 #   define gencpy(a,b) strcpy((char_)(a),(char_)(b))
@@ -97,6 +98,7 @@
 #   define genlen(str) strlen(str)
 #   define print(c)    isprint(c)
 #   define isword(c)   (isalnum(out[c]) || (out[c]=='_'))
+#   define digit(c)    isdigit(c)
 #endif /*SHOPT_MULTIBYTE */

 typedef struct _emacs_
@@ -317,7 +319,7 @@
                        count = 1;
                adjust = -1;
                i = cur;
-               if(c!='\t' && c!=ESC && !isdigit(c))
-               if(c!='\t' && c!=ESC && !digit(c))
                      ep->ed->e_tabcount = 0;
              switch(c)
              {
  @@ -775,7 +777,7 @@
      int digit,ch;
      digit = 0;
      value = 0;
-       while ((i=ed_getchar(ep->ed,0)),isdigit(i))
-       while ((i=ed_getchar(ep->ed,0)),digit(i))
      {
              value *= 10;
              value += (i - '0');
  @@ -1013,7 +1015,7 @@
                              {
                                      i=ed_getchar(ep->ed,0);
                                      ed_ungetchar(ep->ed,i);
-                                       if(isdigit(i))
-                                       if(digit(i))
                                              ed_ungetchar(ep->ed,ESC);
                              }
                      }

**Comment by siteshwar** [comment]
@lijog Are you able to reproduce it if you build from current master branch ?

**Comment by siteshwar** [comment]
I am closing this bug due to lack of activity. Please reopen if it is still reproducible.
