### ISSUE TITLE
Switch (or add) one of the Travis environments to 32-bits

### ISSUE THREAD

**Issue by krader1961** [att/ast#609]
I've been focusing this past week on making ksh free of compiler lint warnings. It now builds with no compiler warnings on macOS, OpenSuse, and FreeBSD. On Ubuntu 32-bit there is this warning:

```
../src/cmd/ksh93/edit/edit.c: In function ‘sh_ioctl’:
../src/cmd/ksh93/edit/edit.c:1383:22: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
         Sflong_t l = (Sflong_t)val;
                      ^
```

We should add, or switch one of the existing, Travis test environments to 32-bits to help catch code that incorrectly assumes the length of a `long int` is the same as a pointer.

**Comment by krader1961** [comment]
The compiler warning in the opening comment is from this block of code:

```
int sh_ioctl(int fd, int cmd, void *val, int sz) {
    int r, err = errno;
    if (sizeof(val) == sizeof(void *)) {
        while ((r = ioctl(fd, cmd, val)) < 0 && errno == EINTR) errno = err;
    } else {
        Sflong_t l = (Sflong_t)val;
```

On what broken system is `sizeof(val)` **not equal to** `sizeof(void *)`? I'm guessing the author meant to write `if (sizeof(void *) != sz)` given how the function is used via this macro:

```
#define ioctl(a, b, c) sh_ioctl(a, b, c, sizeof(c))
```

**Comment by krader1961** [comment]
Quell surprise, the `sh_ioctl()` function isn't even used and therefore can just be deleted.

**Comment by krader1961** [comment]
Do we care if this project builds and runs correctly on 32-bit environments? I googled "travis 32 bit" and the answer is that Travis CI support for 32-bit environments requires jumping through hoops. The native Travis environments are now all 64 bit. See, for example, https://github.com/travis-ci/travis-ci/issues/986. This [issue](https://github.com/travis-ci/travis-ci/issues/5770) shows how to do so using Docker but that is fragile.

**Comment by siteshwar** [comment]
> The only question is whether we should repurpose one of the Linux CI test environments to be 32-bit or add one.

We should add a new one.

**Comment by siteshwar** [comment]
I tried to add 32-bit test environment in [Travis](https://github.com/siteshwar/ast/tree/gh609) and there is one test failing with this error:

```
163/194 sh_match                                FAIL     0.36 s

--- command ---
SHELL='/source/build/src/cmd/ksh93/ksh' LANG='en_US.UTF-8' LD_LIBRARY_PATH='/source/build/src/lib/libast:/source/build/src/lib/libcmd:/source/build/src/lib/libcoshell:/source/build/src/lib/libdll' LIBSAMPLE_PATH='/source/build/src/lib/libdll/libsample.so' /source/build/src/cmd/ksh93/ksh /source/src/cmd/ksh93/tests/util/run_test.sh sh_match
--- stdout ---
<I> run_test[73]: TEST_DIR=/tmp/ksh.sh_match.PkAuwzr
--- stderr ---
<E> sh_match[420]: test_xmlfragment1/0/testfile1.xml: Expected stdout==$'9762 characters to process...\n#input and output OK (9763 characters).', got '9762 characters to process...'
<E> sh_match[421]: test_xmlfragment1/0/testfile1.xml: Expected empty stderr, got $'free(): invalid pointer\n/tmp/ksh.sh_match.PkAuwzr/sh_match.sh[736]: test_xmlfragment1: line 492: 19705: Abort(coredump)'
<E> sh_match[422]: test_xmlfragment1/0/testfile1.xml: Unexpected exit code 262
<W> sh_match[-1]: error_count = 3
```

@krader1961 Do you regularly test on your 32-bit system ? Is it a recent regression ?

**Comment by krader1961** [comment]
I have Ubuntu 16.04 installed as a 32-bit platform with `uname -m` reporting `i686` and the ksh feature tests result in this *config_ast.h* content:

```
#define _ast_sizeof_int 4
#define _ast_sizeof_long 4
#define _ast_sizeof_off_t 8
#define _ast_sizeof_pointer 4
#define _ast_sizeof_size_t 4
```

On 64 bit platforms all but `_ast_sizeof_int` are 8. The only failures I'm seeing in my Ubuntu 32-bit VM are the occasional flakey test failures (e.g., `types.sh`) that fail randomly on all the platforms.

**Comment by siteshwar** [comment]
fwiw I should mention that these failures are reproducible only if you use buffer poisoning.

**Comment by krader1961** [comment]
I see the failure with `meson test --setup=malloc`. This test passed up until commit 489c672d, "Replace calls to AST Vmalloc with system malloc". It's apparently been a few weeks since I ran with malloc poisoning enabled on any platform other than macOS.
