### ISSUE TITLE
ksh93: <>; combined with <#pattern with some builtins or no command fails to truncate

### ISSUE THREAD

**Issue by stephane-chazelas** [att/ast#61]
(tested with ksh93u+ and ksh93v- 2014-12-24 on Ubuntu 16.04 amd64)

In:

```
$ seq 10 > a; strace -e read,write,lseek,ftruncate ksh -c 'printf "" <>; a >#5; cat a'
lseek(1, 0, SEEK_CUR)                   = 0
read(1, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n", 65536) = 21
lseek(1, 0, SEEK_CUR)                   = 21
read(1, "", 65515)                      = 0
lseek(1, 8, SEEK_SET)                   = 8
lseek(1, 0, SEEK_CUR)                   = 8
ftruncate(1, 8)                         = 0
1
2
3
4
```

The file is properly truncated to the start of the line matching the pattern (5).

But if we remove `printf ''` or replace it with many other builtins (I tried `:`, `true`, `eval`, `alias x=x`...), then we see:

```
$ seq 10 > a; strace -e read,write,lseek,ftruncate ksh -c '<>; a >#5; cat a'
lseek(1, 0, SEEK_CUR)                   = 0
read(1, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n", 65536) = 21
lseek(1, 0, SEEK_CUR)                   = 21
read(1, "", 65515)                      = 0
lseek(1, 0, SEEK_CUR)                   = 21
ftruncate(1, 21)                        = 0
lseek(1, 8, SEEK_SET)                   = 8
1
2
3
4
5
6
7
8
9
10
```

We see a truncation attempt but at the end of the file as if the `<#5` failed to find a match.

It's the same if we use a fd other than 1 with `printf ""` like:

```
$ seq 10 > a; strace -e read,write,lseek,ftruncate ksh -c 'printf "" 3<>; a 3<#5; cat a'
lseek(3, 0, SEEK_CUR)                   = 0
lseek(3, 0, SEEK_CUR)                   = 0
read(3, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n", 65536) = 21
read(3, "", 65515)                      = 0
lseek(3, 0, SEEK_CUR)                   = 21
ftruncate(3, 21)                        = 0
lseek(3, 8, SEEK_SET)                   = 8
1
2
3
4
5
6
7
8
9
10
```

That does smell like an incorrect optimisation.

Note that the `<#((expr))` operator doesn't seem to have a similar issue:

```
$ seq 10 > a; strace -e read,write,lseek,ftruncate ksh -c '<>; a >#((10)); cat a'
lseek(1, 0, SEEK_SET)                   = 0
lseek(1, 0, SEEK_CUR)                   = 0
read(1, "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n", 65536) = 21
lseek(1, 10, SEEK_SET)                  = 10
lseek(1, 0, SEEK_CUR)                   = 10
ftruncate(1, 10)                        = 0
1
2
3
4
5
```

**Comment by stephane-chazelas** [comment]
side note, `>#pattern` as an alternative to `1<#pattern` is not documented (though referred to in the text of the man page).

**Comment by siteshwar** [comment]
Couple of notes about this bug:

1. After fixing issue #75, `<>` redirects `stdin` by default instead of `stdout`. So the reproducer for this issue will be:

```
seq 10 > a; strace -e read,write,lseek,ftruncate src/cmd/ksh93/ksh -c '1<>; a >#5; cat a'
```

2. This issue is caused by a delay in syncing streams. If you look closely at strace reports posted by @stephane-chazelas , order of `lseek` and `ftruncate` is reversed in the reproducer. This patch worksaround this bug:

```
diff --git a/src/cmd/ksh93/sh/io.c b/src/cmd/ksh93/sh/io.c
index 4ffd2aa7..b71eb4ff 100644
--- a/src/cmd/ksh93/sh/io.c
+++ b/src/cmd/ksh93/sh/io.c
@@ -1899,6 +1899,7 @@ void sh_iorestore(Shell_t *shp, int last, int jmpval) {
             return;
         }
         if (filemap[fd].tname == Empty && shp->exitval == 0) {
+            sfsync(NULL);
             ftruncate(origfd, lseek(origfd, 0, SEEK_CUR));
         } else if (filemap[fd].tname) {
             io_usename(shp, filemap[fd].tname, NULL, origfd, shp->exitval ? 2 : 1);
```

This is the second bug I have found after #1069 that's caused by not syncing streams. We need to find a consistent way to sync file streams.

**Comment by siteshwar** [comment]
> side note, >#pattern as an alternative to 1<#pattern is not documented (though referred to in the text of the man page).

@stephane-chazelas I see this comment about `>#` in man page:

```
>#((offset))  The same as <# except applies to file descriptor 1.
```
Is there something else that you would like to see documented ?
