### ISSUE TITLE
What to do with the code in src/cmd/builtin

### ISSUE THREAD

**Issue by krader1961** [att/ast#615]
While working on the `#include` statements to make it clear which includes are system versus project specific, and fix IWYU warnings, I noticed that several modules are not being built. In fact, they will fail to build due to missing headers. For example, *src/cmd/builtin/uuencode.c* contains `#include <uu.h>`. That header used to be located at *src/lib/libuu/uu.h* but no longer exists since we eliminated that directory.

The only command in that directory that we are building is `pty`. What do we want to do about the other commands and files in that directory?

**Comment by dannyweldon** [comment]
I don't think any of the `.c` files are needed, however the various `.tst` and `.rt` files may need to be converted to a new form of regression tests for the commands in `src/lib/libcmd`.

**Comment by krader1961** [comment]
FWIW, @dannyweldon, I am proposing removing all the "regression" test files in PR #616. That's because a) they are not regression tests in the usual sense of the term, b) they haven't been run since the project was open sourced, and c) I don't think the cost of that mechanism is worth the benefits. See issue #614.

P.S., Regression tests should be part of the normal test framework. That is, every time a bug is fixed ideally a test is added to ensure the broken behavior is not reintroduced by a subsequent change. Running regression tests should not require a special build with special invocation options.

**Comment by krader1961** [comment]
Face palm on my part with respect to my previous comment

It turns out the "regression" test files I alluded to in my previous comment have nothing whatsoever to do with the `SHOPT_REGRESSION` symbol.  They are simply unit tests written in the legacy IFFE based language. Which need to be converted to shell scripts as are used for all of the ksh unit tests.

That, however, does not negate my original question regarding what to do about the "commands" in the the *src/cmd/builtin* directory.

**Comment by dannyweldon** [comment]
> They are simply unit tests written in the legacy IFFE based language. Which need to be converted to shell scripts as are used for all of the ksh unit tests.

Thanks.  Yes, that's what I meant.  :-)

**Comment by krader1961** [comment]
Okay, I took a second look and realized that directory exists to create standalone versions of the ksh builtins of the same name. No distro will ever build and ship these with the possible exception of the `pty` command. But I've concluded that even that should be limited to being a ksh builtin.
