### ISSUE TITLE
AST intercept mechanism should be removed

### ISSUE THREAD

**Issue by krader1961** [att/ast#622]
The *ast_intercept.h* header and *src/lib/libast/port/intercept.c* module did not exist in the ksh93u+ release. Their presence causes many problems with respect to the order in which system and project headers are included. While working on resolving IWYU (include what you use) recommendations I regularly see errors about redefinition of functions like `faccessat()`.

Those "intercepts" also hide important implementation details to anyone looking at the code since someone looking at a function call like `chmod()` won't recognize it is really a call to `ast_chmod()`.

Too, those "intercepts" are now mostly (all?) pointless since we removed the 3DFS emulation implemented by `pathdev()` and friends. The only possibly useful thing they still do is to restart syscalls that are interrupted via the `RESTART()` macro. But note that ksh93u+ did not have this mechanism and it seems to be sufficiently robust with respect to signals.

Note that `RESTART()` invokes the `astserial()` function which appears to be broken, or at least incompletely implemented, because neither `AST_SERIAL_ENVIRON` or `AST_SERIAL_LOCALE` is used. And `AST_SERIAL_RESTART` is only used in *src/cmd/ksh93/sh/fault.c* which seems to be pointless on initial inspection. That's because if a signal results in `sh_fault()` being called and the syscall was interrupted without being restarted then there doesn't seem to be any need to inspect `&GLOBAL(restart)` (from the `astserial()` function). The return value of the syscall and `errno` will make it clear the syscall was interrupted.

I am no doubt missing the reasons why this mechanism was added. But it is opaque and the source of problems when trying to do simple tasks such as normalizing included headers.

**Comment by krader1961** [comment]
What prompted me to open this issue was running `bin/lint all` after recently including all of *bin/cmd/&ast;* in the files being checked for lint and enabling several previously disabled test modules. This results in recommendations like this:

```
../src/cmd/tests/cdt/tbags.c should add these lines:
#include "ast_intercept.h"  // for link
```

But in many cases adding that preprocessor directive results in a build failure due to conflicts with the system headers that provide prototypes for syscalls/functions like `chmod()`.

**Comment by krader1961** [comment]
Note that all you have to do is something like `grep AST_SERIAL_ENVIRON */*` to see that the symbol is not used. This is clearly something the AST team was in the middle of implementing when the project was killed within AT&T and the code moved to Github. Whether the end goal of that work is worthwhile is not known due to the lack of documentation around these symbols and code.

No other shell whose code I have inspected or modified has used this type of opaque syscall/function intercept. And that includes bash, zsh, elvish, and fish. I find it hard to believe that ksh is unique in this regard.

**Comment by krader1961** [comment]
If I remove (i.e., comment out) every `#include "ast_intercept.h"` and modify the contents of the *src/lib/libast/port/intercept.c* module so that it is a no-op I can successfully build and run all the unit tests.  Which makes it clear that these intercepts are not needed.

**Comment by siteshwar** [comment]
> The only possibly useful thing they still do is to restart syscalls that are interrupted via the RESTART() macro. But note that ksh93u+ did not have this mechanism and it seems to be sufficiently robust with respect to signals.

We should check if code was modified to ignore conditions such as interrupted system calls because intercept functions take care of restarting such calls.

**Comment by krader1961** [comment]
What happens if intercepts aren't installed (by not including *ast_intercept.h*) is the shell uses a handful its own implementations to handle EINTR such as `sh_chdir()`. That's true for both the ksh93u+ branch and the current code.
