### ISSUE TITLE
Stop building `pty` and drop the source?

### ISSUE THREAD

**Issue by krader1961** [att/ast#634]
A conscious decision was made a year ago to limit the focus of this project to the `ksh` command. Libast would be maintained only to the extent required by ksh so that features like Vmalloc could be dropped. And we finally removed all but one of the commands in *src/cmd/builtin*. In part because some of the commands were of historical interest only (e.g., `asa`). But also because every distro includes implementations of the others, generally from BSD or GNU, that they are not going to replace with the versions in this project.

At present we only build two commands: `ksh` and `pty`. I propose dropping `pty`. It has at least one known bug (see issue #375). And it doesn't provide any functionality not provided by `expect`; a much more widely known and used tool.

**Comment by siteshwar** [comment]
@bitstreamout It is shipped with suse. I would appreciate your comments on this issue.

**Comment by siteshwar** [comment]
I will open a pull request to drop it.
