### ISSUE TITLE
Cppcheck points out another problem in an unused SFIO module: sfdcfilter.c

### ISSUE THREAD

**Issue by krader1961** [att/ast#654]
Cppcheck tells us this:

```
[../src/lib/libast/disc/sfdcfilter.c:100] warning (uselessAssignmentPtrArg):
 Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
[../src/lib/libast/disc/sfdcfilter.c:103] warning (uselessAssignmentPtrArg):
 Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
```

Which is due to this function:

```
/* for the duration of this discipline, the stream is unseekable */
static Sfoff_t filterseek(Sfio_t *f, Sfoff_t addr, int offset, Sfdisc_t *disc) {
    f = NULL;
    addr = 0;
    offset = 0;
    disc = NULL;
    return (Sfoff_t)(-1);
}
```

That module has a doc string saying it was written in 1998! And it still contains that obviously pointless function. Fortunately it isn't used by ksh so we can just remove it.

**Comment by DavidMorano** [comment]
> That module has a doc string saying it was written in 1998! And it still contains that obviously pointless function.

It was probably an experiment that was never fleshed completely out, and then somewhat forgotten. These sorts of things do occasionally happen to mere mortals like us also.
