### ISSUE TITLE
my ksh93 program randomly self-terminates when calling "sleep 1"

### ISSUE THREAD

**Issue by ezonakiusagi** [att/ast#68]
I'm dealing with a strange issue that I can't figure out, so I'm hoping I can get some assistance. Even if no one can identify the exact problem, I would be happy to even get suggestions on how to troubleshoot this further.

The issue is that my ksh93 program is randomly terminating; details will follow. This is part of a larger system that contains several 10's of thousands lines of ksh93 code, so I can't post everything, but I've isolated the issue to a few lines of code and I'll try to share as much information that I think will be relevant. Unfortunately, I have not been able to reproduce this problem with any code sample/snippet to demonstrate it in isolation; it only happens on some particular systems.

So, here are the details:

1) This is ksh on a CentOS-7.2.1511 (x86_64) system. The ksh package is:

ksh-20120801-22.el7_1.3.x86_64

I don't think the problem is specific to this version of ksh. We have about 50+ systems that run this code, but only a handful of recently deployed systems are exhibiting the problem. I've been trying to identify what is different between the problematic systems vs the older systems that do not exhibit the problem and haven't found much other than one thing:

- I found several segfault messages like these on the problematic systems:
[2495762.526630] worker-inbound-[33980]: segfault at 20 ip 000000000043b110 sp 00007fff9f4be310 error 4 in ksh93[400000+15c000]
[2511351.121174] worker-inbound-[11296]: segfault at 12 ip 00000000004a95cc sp 00007ffce5abadb0 error 4 in ksh93[400000+15c000]
[2535332.660135] worker-inbound-[33298]: segfault at 20 ip 000000000043b110 sp 00007ffcfe208e90 error 4 in ksh93[400000+15c000]

- I discovered that the version of glibc was different on the systems having the problem. I've since updated glibc to see if that makes any difference. I'm still observing to see if the segfaults show up again; none as of this writing. regardless, I'm not sure if the segfaults are related to the problem as I am still experiencing it.

2) This is the section of code we've isolated the problem to:

    while [[ -d ${outbound_mesg} ]]
    do
        log_message -p debug -m "queue_injection(): directory ${outbound_mesg} already exists."
        sleep 1
        log_message -p debug -m "queue_injection(): slept for 1 second."
        timestamp=$($DATE +%s)
        log_message -p debug -m "queue_injection(): got new timestamp=${timestamp}."
        outbound_mesg="${WORKER_OUTBOUND_QUEUE}/${job_id}_${task_id}_${timestamp}"
        log_message -p debug -m "queue_injection(): trying ${outbound_mesg}."
    done

the "log_message" is a general logging function we use throughout the code base; you can imagine what it does. i will say also, that this particular program also traps for TERM and EXIT signal like:

trap "release_lock $LOCK_DIR" TERM EXIT

the failure does not occur all the time. from the sampling we have, it seems to happen about 10-15% of the time. so it is not consistently reproducible.

Here is a snippet of the logs from our "log_message" function when the problem occurs:

[2017.08.24 (Thu) 22:40:03 UTC][PID=20791] queue_injection(): directory /var/lib/worker/queue/outbound/941f3665-24e1-4aeb-8dcb-dcaac2f7f87e_a36c223f-7f2b-4280-9cc1-b91203bc49a4_1503614403 already exists.
[2017.08.24 (Thu) 22:40:03 UTC][PID=20791] call release_lock(/var/lib/worker/queue/inbound/941f3665-24e1-4aeb-8dcb-dcaac2f7f87e_a36c223f-7f2b-4280-9cc1-b91203bc49a4.lock)

As you can see, we get the log message from the 1st log_message call in the above code, but we do not get the message about "slept for 1 second.". So, it seems that a call to "sleep 1" is randomly failing and causes the program to exit, hence calling the release_lock function from the signal trap.

On a "normal" run of this program, we see all the other log messages as expected, but the above is the type of messages we get when it fails.

I've managed to isolate it down to the single line "sleep 1", but I can't understand why the ksh program would self terminate at that point???

What else can I do to identify the cause? is there a way to gather more information when the program self-terminates unexpectedly?

I've been working on this problem for 2 weeks straight now and have gotten to this, but I don't know what else to do.

**Comment by siteshwar** [comment]
```sleep``` is a builtin in ksh. To narrow down this bug to the builtin I would probably change ```sleep 1
``` calls to ```command sleep 1``` and check if the bug reproduces. This would call the command ```sleep``` instead of builtin. This should help us in confirming that there is a problem in ```sleep``` builtin.

**Comment by dannyweldon** [comment]
Also, see if you can enable user core dumps, by adding this to the profile for the user it is running as:

    ulimit -c unlimited

For centos7/rhel7, you may also have to add this to /etc/systemd/system.conf and reboot:

    DefaultLimitCORE=infinity

Then once you have a core file, run (substitute core for whatever the core file is):

    gdb ksh core

Then type 'bt' to get the backtrace:

    bt

You could even install a debuginfo version of ksh from http://debuginfo.centos.org/7/x86_64/ which may give more info from the backtrace.  You probably don't need to run this version; I think you could get away with only using it with gdb, but I'm not sure.

**Comment by ezonakiusagi** [comment]
@siteshwar - thanks for the suggestion on sleep. i just tried replacing sleep with /usr/bin/sleep and let it run for a few hours. unfortunately, i'm still experiencing the program terminating at the exact same place! so i guess it might not have much to do with sleep... i don't know what to think now??? how can I find out why it is terminating?

also, another point of data: when the program terminates, it doesn't always run the trap function. sometimes it does, but sometimes the log messages end at the "directory ... already exists." message!

@dannyweldon - thanks for that suggestion. I need to see if I can enable that and reboot the system. we don't have a proper test system, so I have to make these changes in production.

**Comment by siteshwar** [comment]
Also, since it looks like a memory corruption, ```valgrind``` logs should help.

**Comment by ezonakiusagi** [comment]
ok. thanks for the suggestions. turning on core dumps will have to wait until next week. i will report back when i have more info.

additionally, we are still seeing the segfaults on the problematic systems:
[82034.344459] worker-inbound-[21770]: segfault at 20 ip 000000000043b110 sp 00007ffe481de550 error 4 in ksh93[400000+15c000]

although, the number of segfault messages in dmesg do not correspond to the number of problem instances we've counted. i don't know if they are related.

**Comment by ezonakiusagi** [comment]
unfortunately, we've decided to solve this problem by changing our code to avoid the section of ksh that triggers this problem. in the end, it seems like a quicker solution and forced us to re-design our system for the better. i'm going to close this issue as unresolved.
