### ISSUE TITLE
On Cygwin, meson.build uses incorrect gcc/ld option --

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#703]
**Description of problem:**
meson.build checks to see if the gcc/ld option '-Wl,-E' is valid.  On Cygwin, gcc/ld produces PE+ executables and that requires the '-Wl,--export-all-symbols' option.  See patch in "Additional info".

**ksh version:**
Don't know.  Used the current (2018-07-22) clone download as source.
The shell says ${KSH_VERSION} == "Version A 0.0.0".
Another bug, maybe?

**Steps to reproduce:**
1. Run the ninja -C build on Cygwin and watch the compiler complaints that contain --export-dynamic and --export-all-symbols.
2.
3.

**Actual results:**

**Expected results:**

**Additional info:**
[difs.txt](https://github.com/att/ast/files/2217466/difs.txt)

**Comment by krader1961** [comment]
Thanks. I merged your patch. I've known about this but didn't bother to fix it because it's sole purpose is to try to make it more likely the `dump_backtrace()` function produces useful output. This compiler flag isn't actually needed for the correct functioning of ksh.

**Comment by aabatpurdue** [comment]
Okay.  It's time for dumb questions.  What/where are git tags, how do I find them and how do I download them?  To my old eyes there was no outright reference to 'tags' that I could see.


--  Thanks,

--    Paul Townsend


________________________________

**Comment by krader1961** [comment]
@aabatpurdue The short answer is that `git fetch --tags` should resolve your situation.

You don't need to know about git tags unless you are a developer or someone who is integrating this project into an operating system. Git tags are an advanced feature of the Git source code management system. See, for example, https://stackoverflow.com/questions/10491146/in-git-how-do-i-sync-my-tags-against-a-remote-server in answer to your question. The Git SCM is a bit of a mess with regard to the management of commit tags. Especially when a remote server is involved that is perceived to be the "source of truth". Which is something antithetical to the ethos of Git.

**Comment by aabatpurdue** [comment]
Your 'git fetch --tags' did not work.  The only thing that I wanted was the keys but I ended up downloading the entire repo when I appended the repo URL to the above command.  Is there any way to get just the tags?


--  Thanks,

--    Paul Townsend


________________________________

**Comment by siteshwar** [comment]
@aabatpurdue Doing a fresh clone of this repo should automatically fetch you the tags:

```
git clone https://github.com/att/ast.git
```

You can verify it by running this command under `ast` directory:

```
git tag -l
```

**Comment by aabatpurdue** [comment]
Thanks.  Worked like a charm.   ${KSH_VERSION} = "Version A 93v-1328-g2e6acdf2".


--  Thanks again,

--    Paul Townsend


________________________________
