### ISSUE TITLE
Compiling on Cygwin results in warnings due to wchar_t being 16 bits

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#704]
**Description of problem:**
On Cygwin with gcc (GCC) 7.3.0, gcc makes "always true"/"always false" warnings about some value comparison code.  See attachment for all current warnings.  This code might explain some other random issues.
[warns.txt](https://github.com/att/ast/files/2217488/warns.txt)

**Comment by aabatpurdue** [comment]
Oboy, try two.  Try one disappeared somewhere.  I hope this is the correct place to present a patch to fix the 'gcc' compiler warnings problem caused by the '-Wtype-limits' option.

This is an ugly fix.  FWIW - I initially tried to coerce 'gcc' by casting the `wchar_t c;` variables to 32-bit quantities, i..e., `(long)c` and `(uint32_t)c`.  'gcc' did not take the bait and continued to issue warnings.  I ended up assigning `c` to new 32-bit variables as in `long long_c = c;` and `uint32_t uint32_c = c;` and replacing the `wchar_t` variables with them in the problem code.  Like I initimated above - UGLY.

A second bad(?) coding problem arose from the code assigning '-1' to a `wchar_t c` variable then checking the variable to see if it was negative.

A third problem was because of a comparison of a `whar_t c` against a value that exceeded the size of 'c'.

**Comment by krader1961** [comment]
I have "fixed" this by changing the two places that cause a compiler warning or error. I use scare quotes because the fix does not handle characters outside the BMP; i.e., does not handle surrogate pairs. But then neither did the original code. My fix simply allows building ksh that works if your LANG is representable in the Unicode BMP.
