### ISSUE TITLE
Remove symbol SHOPT_DYNAMIC and unconditionally enable the feature if the platform supports dynamic loading

### ISSUE THREAD

**Issue by krader1961** [att/ast#716]
We've already eliminated a large number of the `SHOPT_` symbols. And we're already enabling `SHOPT_DYNAMIC` unconditionally. Removing it and treating it as always enabled will simplify the code and make it easier for humans to read. This feature should only be disabled if the platform doesn't support it as determined by a config time feature test.

We're also building `libsample.so` from *src/lib/libdll/sample.c* but the test of dynamically loaded builtins at the bottom of *src/cmd/ksh93/tests/builtin.sh* is woefully inadequate.

**Comment by krader1961** [comment]
Also, whether or not dynamically loading builtins is enabled should not be predicated on a symbol like `SHOPT_DYNAMIC`. It should be predicated on ksh being built as a dynamically linked, rather than static, binary. And, obviously, that the platform provides the necessary support such as a usable `dlopen()` function. But the latter should be implicit if the shell is a dynamically linked binary.

**Comment by dannyweldon** [comment]
Will it still be possible to build a static version of `ksh` if someone needs it for a system that normally supports dynamic linking?  Eg.  For a boot environment or for a portable binary?

**Comment by siteshwar** [comment]
> Will it still be possible to build a static version of ksh if someone needs it for a system that normally supports dynamic linking? Eg. For a boot environment or for a portable binary?

Yes. Code under `SHOPT_DYNAMIC` macro is related to dynamically loading shell builtins from libraries and it does not affect whether `ksh` is built dynamically or statically. In fact we build `ksh` statically by default.

**Comment by krader1961** [comment]
Actually, at the moment we do not build ksh as a statically linked binary. We do build the AST libraries statically so the functions ksh needs from them are statically linked into the ksh binary. But ksh still depends on the system shared libc and other system libraries:

```
$ ldd src/cmd/ksh93/ksh             12 ms
        linux-vdso.so.1 (0x00007fffeadda000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f1a7b30d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1a7b109000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f1a7ad64000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1a7b60a000)
```

If we did build ksh as a fully statically linked binary that should also disable the dynamic loading of builtins. On some systems `dlopen()` and friends won't work reliably in a statically linked binary. But even if they do it is dangerous to load a shared library that is linked against a dynamic/shared version of any system library (e.g., libc) that ksh is statically linked against.

**Comment by krader1961** [comment]
It doesn't appear to be possible to build as a fully ksh statically linked binary. At least not on macOS or Linux using just the `-static` flag at link time. On Linux there are several linker errors such as this one:

```
/home/krader/projects/3rd-party/ast/build/../src/cmd/ksh93/sh/io.c:536: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Comment by DavidMorano** [comment]
> It doesn't appear to be possible to build as a fully ksh statically linked binary.

Somewhere between ten and fifteen years ago Solaris (and its derivatives) also dropped the ability to build fully static binaries.  For myself, I say good riddance! :-) Remember that one can still link to non-system libraries statically, so that gives about as much flexibility as most anyone would want. Many projects use a mix of both statically linked and dynamically linked libraries routinely.

**Comment by krader1961** [comment]
FWIW, I consider @dannyweldon's scenario of using ksh in a boot environment to be a non-issue. That is, something we are no longer obligated to support. That's because long ago the ksh maintainers made it clear that ksh is a general purpose language analogous to Python. Would you expect to be able to build python statically linked so it could be used in that scenario?

And, from a practical perspective, I've spent several hours trying to build ksh fully statically linked on Linux and BSD without success. It may be possible to do so but someone more motivated than myself will have to figure out how to do so.

I've merged a change that simplifies the code by assuming we should always attempt to support dynamically loading builtins. If we ever find a platform or situation where that isn't true the error should be detected and reported at run-time rather than build-time. Or a hybrid if the platform doesn't provide the necessary primitives for even an emulated `dlopen()` call to succeed.
