### ISSUE TITLE
Man page corrections --

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#764]
**Description of problem:**
The roff currently being used in the ast-ksh manpage source for an asterisk is \\(\*\*.  On Cygwin, at least with the font that I am using, this produces an extremely tiny asterisk that I thought was a dot at first.  According to groff_char(7), an asterisk is just a plain, unadorned *.  I replaced all of the \\(\*\* with * and it is very readable.

Replaced "can be define as shell functions" with "can be defined as shell functions".

Deleted some duplicate lines - look for CDPATH + COLUMNS in the current ksh.1.

--  Thanks,
--    aabatpurdue

**Ksh version:**
Downloaded the ast.git repository on Jul 25, 2018.
93v and counting.

**How reproducible:**
Always

**Steps to reproduce:**
1. For me, man ksh
2.
3.

**Actual results:**
Bad text in man page

**Expected results:**
Different from what I see with the original.

**Additional info:**
See patch 
[ksh.1.difs.txt](https://github.com/att/ast/files/2260049/ksh.1.difs.txt)

**Comment by krader1961** [comment]
Patch LGTM. @siteshwar, what do you think?

**Comment by siteshwar** [comment]
LGTM too. I will merge it.
