### ISSUE TITLE
What to do about bugs (both actual and potential) identified by lint warnings

### ISSUE THREAD

**Issue by krader1961** [att/ast#79]
I'm wondering how people feel about resolving lint warnings and errors. Such as these:

```
/Users/krader/projects/3rd-party/ast/src/lib/libcmd/ls.c:1260:3: error: non-void function 'ls' should return a value [-Wreturn-type]
                return;
                ^
/Users/krader/projects/3rd-party/ast/src/lib/libcmd/ls.c:1268:3: error: non-void function 'ls' should return a value [-Wreturn-type]
                return;
                ^
/Users/krader/projects/3rd-party/ast/src/lib/libcmd/ls.c:1273:3: error: non-void function 'ls' should return a value [-Wreturn-type]
                return;
                ^
```

That is just the tip of the iceberg. The overall style of the code is problematic. For example, there are a huge number of locations which both assign to and evaluate the result of the assignment in the context of control structures. For example:

```
/Users/krader/projects/3rd-party/ast/src/lib/libast/misc/fastfind.c:125:11: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
        while (c = *t++)
               ~~^~~~~~
/Users/krader/projects/3rd-party/ast/src/lib/libast/misc/fastfind.c:125:11: note: place parentheses around the assignment to silence this warning
        while (c = *t++)
                 ^
               (       )
/Users/krader/projects/3rd-party/ast/src/lib/libast/misc/fastfind.c:125:11: note: use '==' to turn this assignment into an equality comparison
        while (c = *t++)
                 ^
                 ==
```

Most, probably all, of those are correct. But that idiom has been the source of numerous bugs which is why compilers and lint tools (e.g., `oclint`) warn about the pattern.

Then there are warnings like this:

```
../../lib/libpp/ppproto.c:2437:48: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                                proto->op = strcopy(( proto->op),( "\n%{\n"+ !notice));
                                                                   ~~~~~~~~^~~~~~~~~
../../lib/libpp/ppproto.c:2437:48: note: use array indexing to silence this warning
                                proto->op = strcopy(( proto->op),( "\n%{\n"+ !notice));
                                                                           ^
                                                                   &       [        ]
```

That's a cool trick but the behavior is far too subtle. It took me a few seconds to recognize what was going on and I've been programming in C for more than three decades.

I'm also bothered by nested blocks that are not enclosed in braces. For example,

```
                for(; p > 0; --p, ++ps, ++s)
                        if((*ps = *s) == 0)
                                break;
```

That is from *src/lib/libast/sfio/sfputr.c* which I've been touching to fix problems with calling `memccpy()` with overlapping buffers. I have found two bugs in my career due to that pattern because someone came along and added a second statement to the nested block without noticing the first statement wasn't wrapped in braces. Which meant that one of the nested statements wasn't actually predicated on the enclosing control structure.

I love the Korn shell and want to contribute to its evolution. Even if that evolution is doing little more than fixing bugs and making it build cleanly. But if changes to address issues like the above aren't going to be accepted then I'm going to be reluctant to contribute improvements. So I'm curious how the people in control of ksh feel about addressing such issues.

**Comment by krader1961** [comment]
Another problematic example of a coding style that occurs many times in the code which relies on subtle behavior that is likely to lead to mistakes:

```
/Users/krader/projects/3rd-party/ast/src/lib/libast/path/pathcanon.c:580:29: warning: '&&' within '||' [-Wlogical-op-parentheses]
                        z = x || (flags & 0x001) && dev->fd >= 0 ? s : (char*)path;
                              ~~ ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/Users/krader/projects/3rd-party/ast/src/lib/libast/path/pathcanon.c:580:29: note: place parentheses around the '&&' expression to silence this warning
                        z = x || (flags & 0x001) && dev->fd >= 0 ? s : (char*)path;
                                                 ^
```

**Comment by siteshwar** [comment]
If you want to refactor code, I will be fine with reviewing and merging pull requests. However with ksh it's incredibly hard to verify if your changes break any existing use cases. There are test cases already but lot of them already fail. (Also note after this commit[1] number of test cases that fail are reported wrong, because test scripts use number of failed test cases  as exit status code and in some cases more than 256 test cases fail).

[1] https://github.com/att/ast/commit/c04578518d297d89d52fafe8d61409ed65df5ae0

**Comment by krader1961** [comment]
On Wed, Oct 18, 2017 at 5:37 AM, Siteshwar Vashisht <
notifications@github.com> wrote:

> If you want to refactor code, I will be fine with reviewing and merging
> pull requests. However with ksh it's incredibly hard to verify if your
> changes break any existing use cases. There are test cases already but lot
> of them already fail. (Also note after this commit[1] number of test cases
> that fail are reported wrong, because test scripts use number of failed
> test cases as exit status code and in some cases more than 256 test cases
> fail).
>
> [1] c045785
> <https://github.com/att/ast/commit/c04578518d297d89d52fafe8d61409ed65df5ae0>
>

Yeah, I noticed the unit tests need some work. If we keep the idea that the
exit status reflects how many tests have failed it should probably be
capped at a maximum of 100. If more than 99 tests fail just return 100 to
indicate that too many failures have occurred because at that point you
don't really care if it is 101 or 257. You just need to know a lot of tests
failed.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by krader1961** [comment]
I'm going to close this in favor of opening issues that are actionable. For example, establish a style guide and ensure `clang-format` enforces it and make it easy to run the code through that command. Similarly for `oclint` and `cppcheck`. I predict that several bugs will be fixed solely as a side-effect of doing those things. Which is what happened when I did the same thing to the fish-shell project two years ago.
