### ISSUE TITLE
Shall `read` builtin recognize 'a' option ?

### ISSUE THREAD

**Issue by siteshwar** [att/ast#819]
From the output of `read --man`:

```
 -a              Unset var and then create an indexed array containing each field in the line starting at index 0.
```

Above entry was made by [2014-12-24-beta](https://github.com/att/ast/commit/0bc6abf9e) commit. But this option is actually not recognized by `read` builtin. `read` builtin already supports `-A` option which does this. Also, this option is mentioned with description of `-C`:

```
-C              Unset var and read var as a compound variable. Equivalent to -aksh
```

which seems wrong and should be changed to `-m ksh`. Is there any value of adding `-a` option with `read` builtin or shall we remove it's entry from `read --man` ?

**Comment by siteshwar** [comment]
> But this option is actually not recognized by read builtin.

To clarify my comment, `read` builtin recognizes this option but does nothing with it. This option is supported by `bash`, so it seems it was introduced to increase `bash` compatibility. Since we are not targeting compatibility with bash, I am not in favor of adding it in next release.

**Comment by krader1961** [comment]
As I've written before I am opposed to any attempt to implement a bash emulation mode. It is unlikely there will ever be enough people or corporate interest in maintaining this project to justify the cost of maintaining that emulation. Just dealing with all the ksh specific issues is going to keep us busy for the foreseeable future.

Having said that the behavior of `read -a` is already implemented as `read -A`. All that is needed is to make `-a` an alias for `-A`. And that level of compatibility is reasonable given that it is wholly confined to the `read` implementation and does not depend on any other options; e.g., `set -o bash`. So I have no objection to actually implementing this. But if we don't the internal documentation needs to be corrected.

**Comment by siteshwar** [comment]
I am fine with improving bash compatibility as long as it does not overly complicate codebase. I will open a pull request to add support for `read -a`.
