### ISSUE TITLE
printf "%#d" is broken on 32-bit systems

### ISSUE THREAD

**Issue by siteshwar** [att/ast#832]
**Description of problem:**
printf "%#d" is broken on 32-bit systems

**Ksh version:**
2017.0.0-devel-1600-g382686c8

**How reproducible:**
Always

**Steps to reproduce:**
```
printf "%#d" 1000
```

**Actual results:**
1(null)

**Expected results:**
1.0k

**Additional Info:**
This bug is not present in `2016-01-10-beta` branch.

**Comment by siteshwar** [comment]
This is a regression introduced by 0c1fad6434203f6bae8154b81bd63c60638bd66d

**Comment by krader1961** [comment]
What I find surprising is we haven't noticed before now that some build time symbols are incorrect for 32 bit platforms. I've been building/testing ksh on 32 bit Ubuntu for a very long time. Note that I removed *ast_common.h* with commit e42dab92:

```
    Remove header ast_common.h

    The previous commits I did whittled the content of ast_common.h to two
    things:

    1) some symbols that belong in the ast_config.h header and which should
    be turned into feature tests at build time rather than being hardcoded,
    and

    2) a few #include directives for standard system headers.

    For item #1 I've moved the symbols to ast_config.h.in. For item #2 I've
    added the needed #include directives to the modules which had been
    including ast_common.h (basically a IWYU cleanup).
```

These are the relevant *config_ast.h.in* lines:

```
// These symbols are from src/lib/libast/include/ast_common.h that was
// generated on a Linux platform by the legacay IFFE mechanism. They may not
// be correct for other platforms.
//
// TODO: Convert these to proper feature tests.
#define _ast_LL 1  // LL numeric suffix supported
#define _ast_int8_t long
#define _ast_intmax_t _ast_int8_t
#define _ast_intmax_long 1
#define _ast_intswap 7
#define _ast_fltmax_t long double
```
