### ISSUE TITLE
`ninja -v ...` shows 64 of 484 files are compiled twice --D

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#866]
**Description of problem:**
This is mostly a FYI.  It seems that 64 of the 484 files are compiled twice. Don't know if this can be changed or even if it should be changed.  I have almost nil knowledge of `meson` and `python3` so am not a good candidate for making any changes.

**Ksh version:**
The clone is from September 3.

**How reproducible:**
Every time.

**Steps to reproduce:**
1. `ninja -v ....`
2.
3.

**Actual results:**
64 of 484 files are compiled twice.

**Expected results:**
In a perfect world, only 420 files should be compiled. (:-})

**Additional info:**
I did a `cmp` of one pair of files and they compared equal.  Since the remainder are probably equal also, it would be nice if these could be put in a directory by themselves and used twice.

**Comment by siteshwar** [comment]
@aabatpurdue Can you tell us names of these files ?

**Comment by siteshwar** [comment]
fwiw on my linux machine `401` files are compiled (without api tests).

**Comment by aabatpurdue** [comment]
@siteshwar The files that I see are in [dblcomp.txt](https://github.com/att/ast/files/2376947/dblcomp.txt).  I ran `ninja -v ...` and extracted the `-c file-path`.  I then sorted it twice,  the second time with the `-u` option, and then `sdiff``ed the two results.  The attached file contains the differences.

Ummm.  Should have said that I see this on Cygwin and MSYS2.

Does your linux box OS supply a number of the required functions that results in fewer compiles??

**Comment by krader1961** [comment]
Those modules are built twice because they are built with a different value for a preprocessor symbol. That's how the legacy build system did it and no one has bothered to figure out if that's actually necessary. This is the relevant section from *src/cmd/ksh93/meson.build*. I added the comment nine months ago because I was wondering the same thing:

```
# TODO: Figure out why there is a different definition of these symbols for
# ksh93 versus shcomp and if there is a good reason add a comment why they are
# defined differently.
ksh93_c_args = shared_c_args + [
    '-DERROR_CATALOG=NULL',
]

shcomp_c_args = shared_c_args + [
    '-DERROR_CATALOG="libshell"',
]
```

**Comment by krader1961** [comment]
I looked more closely at this issue this evening. It's possible this difference in the `-DERROR_CATALOG` flag was significant in the past. But looking at the code today it is clear this value is only used in the `cmdinit()` function. And it is only used if `error_info.catalog` is the NULL pointer. And for `ksh` and `shcomp` it is always initialized to `"libshell"`. Specifically by this assignment

```
error_info.catalog = e_dict;
```

in *src/cmd/ksh93/sh/init.c*. Where `e_dict`  is defined thusly:

```
const char e_dict[] = "libshell";
```

So whatever the original reason for building the modules in question with two different preprocessor symbol definitions it is no longer relevant.

**Comment by aabatpurdue** [comment]
I compared the object files from all of the doubly compiled sources and found only one that did not get a zero return from `cmp`. I wrote a script, [cmpobj_sh.txt](https://github.com/att/ast/files/2378481/cmpobj_sh.txt), that can be used to demonstrate what I did.

**Comment by aabatpurdue** [comment]
The close was a mistake (:@{).

I wrote a script, [cmpobj_sh.txt](https://github.com/att/ast/files/2378662/cmpobj_sh.txt), to compare the object files from all of the doubly compiled sources.  All but one, `bltins_enum.c`, compared equal.  The doubly compiled file list remains the same (see above).  The object comparison is in the file [dblcmp.txt](https://github.com/att/ast/files/2378684/dblcmp.txt).

Note that the OPTIM lines in the script should wait until I can submit an already written patch that clears all but one "uninitialized" warning and suppresses the "maybe-overwritten" warning.  Else,  you will get a lot of trash on stdout.

**Comment by krader1961** [comment]
@aabatpurdue Before you go to the trouble of creating patches for build errors I would recommend opening an issue. We know there are many warnings when building on Cygwin. Many, if not all, of them are due to typedef `wchar_t` being 16 bits on MS Windows rather than 32 bits (see issue #704). Errors that are expected to be platform independent, such as use of uninitialized variables, we should already be noticing via tools like cppcheck, oclint, and the Coverity Scan service.

**Comment by aabatpurdue** [comment]
They really aren't uninitialized.  The warning is "maybe-uninitialized" because the compiler thinks it found a code path that would have them uninitialized at the point of the warning.  Actually, you can sometimes look at the preceding several lines of code and find the same variable used with no complaint.  Go figure.

FWIW - I make the assumption that the "powers that be" in the ksh world have already used the software that you mention.  If so, I hope they have the results somewhere so that I can view them.

And, yes, it will be a new issue.
