### ISSUE TITLE
Typo/oops in one of the meson.build files --

### ISSUE THREAD

**Issue by aabatpurdue** [att/ast#869]
**Description of problem:**
Six `#include file.h` instead of `#include <file.h>`.

**Ksh version:**
September 3rd clone.

**How reproducible:**
n/a

**Steps to reproduce:**
1. n/a
2.
3.

**Actual results:**
n/a

**Expected results:**
The "file.h"s to be "<file.h>`s

**Additional info:**
See patch [sub-meson-build-bug.txt](https://github.com/att/ast/files/2378800/sub-meson-build-bug.txt)

**Comment by krader1961** [comment]
Thanks for bringing this to our attention. Earlier cleanups have eliminated the need for all of the symbols defined by those feature tests. So rather than fixing those `#include` statements we can just remove that *meson.build* file.
