### ISSUE TITLE
Stop retrying `close()` on EINTR

### ISSUE THREAD

**Issue by krader1961** [att/ast#885]
While working on a Coverity Scan resource leak I noticed this line in *xec.c*:

```
while (close(fd) < 0 && errno == EINTR) errno = err;
```

That practice is pointless. See these links for why:
 
https://lwn.net/Articles/576478/
http://austingroupbugs.net/view.php?id=529
https://sourceware.org/bugzilla/show_bug.cgi?id=14627

**Comment by siteshwar** [comment]
This should be safe on Linux. However reading the discussion on opengroup:

```
If close() returns -1 with errno setto [EINTR], it is unspecified whether fildes can subsequently bepassed to any function except close( ) or posix_close( ) without error.
--
```

So not reissuing `close()` will cause undefined behavior. @krader1961 Am I missing something here ? Is removing this code guaranteed to be safe on other OSs ?
