### ISSUE TITLE
Coverity resource leak warning points to a more serious isssue

### ISSUE THREAD

**Issue by krader1961** [att/ast#886]
Coverity Scan reported resource leak [CID#253698](https://scan4.coverity.com/reports.htm#v37777/p13914/fileInstanceId=52075654&defectInstanceId=9648767&mergedDefectId=253698&fileStart=751&fileEnd=1000) in *src/cmd/ksh93/sh/path.c*. The warning appears to be a false positive. But it caused me to take a close look at the code:

```
    path = path_relative(shp, opath);
    if (*path != '/' && path != opath) {
        // The following code because execv(foo,) and execv(./foo,) may not yield the same results.
        char *sp = (char *)malloc(strlen(path) + 3);
        sp[0] = '.';
        sp[1] = '/';
        strcpy(sp + 2, path);
        path = sp;
    }
    if (spawn /* && !sh_isoption(shp,SH_PFSH) */) {
        pid = _spawnveg(shp, opath, &argv[0], envp, spawn >> 1);
    } else {
        pid = path_pfexecve(shp, opath, &argv[0], envp, spawn);
    }
    if (xp) *xp = xval;
    if (*path == '.' && path != opath) {
        free(path);
        path = path_relative(shp, opath);
    }
```

Note that the first and last `if (...)` blocks used to be protected by `#ifdef SHELLMAGIC`. Since that was always defined to be one we removed the preprocessor test. The block of code above exists in the ksh93u+ branch.

**What is interesting is that the munged path isn't actually used.** So while I have no idea what problem that path munging was intended to solve (presumably a workaround for a broken platform) it is clearly a no-op now. And removing that code will eliminate the Coverity resource leak warning.

Also, it's not at all obvious the last `if (...)` can't call `free(path)` even if the first `if (...)` block wasn't executed. Looking at the implementation of `path_relative()` it looks like it should be impossible but I can't help but wonder what would happen if someone deliberately specified a path with an embedded `/./` segment after a `PWD` prefix. Regardless, the code in question is not needed.

**Comment by kdudka** [comment]
> And removing that code will eliminate the Coverity resource leak warning.

Sure, you can eliminate all resource leak warnings by removing code that allocates resources.  But it would be also good to explain why you think that removal of the code is safe in this case.  I do not think it is...
