### ISSUE TITLE
`set -b`does not show message on job completion

### ISSUE THREAD

**Issue by siteshwar** [att/ast#911]
**Description of problem:**
According to man page entry of `set -b`:

```
-b      Prints job completion messages as soon as a background job changes state rather than waiting for the next prompt.
```

**Ksh version:**
2017.0.0-devel-1846-g0296704d

**How reproducible:**
Always

**Steps to reproduce:**
```
set -b
sleep 3&
```

and wait on the prompt for completion message to appear.

**Actual results:**
Completion message is printed only at next prompt.

**Expected results:**
Completion message should be printed as soon as the job exits.

**Additional info:**
This bug is present in `93u+ 2012-08-01` release.

**Comment by krader1961** [comment]
For the record this is broken in ksh93u+ and ksh93v- as well as the current development branch. So it's been broken at least six years.
