### ISSUE TITLE
`set -G' does not match subdirectories

### ISSUE THREAD

**Issue by siteshwar** [att/ast#912]
**Description of problem:**
`set -G` does not match subdirectories

**Ksh version:**
2017.0.0-devel-1846-g0296704d

**How reproducible:**
Always

**Steps to reproduce:**
1. Go to root directory of `ksh` sources:
```
set -G
ls **.sh
```

**Actual results:**
ls: cannot access '**.sh': No such file or directory

**Expected results:**
It should show all files ending with `.sh` extension.

**Additional info:**
This bug is present in `93u+ 2012-08-01` release.

**Comment by krader1961** [comment]
I don't see anything in the definition of the `globstar` option that implies it should behave as the problem statement implies. And in bash this doesn't work either. In both shells both `**` and `**/` seem to work as documented. Are you sure this is a bug?

**Comment by siteshwar** [comment]
This is the entry in man page:

```
-G      Causes the pattern ∗∗ by itself to match files and zero or more directories and sub-directories when used for file name generation.  If followed by a / only directories and sub-directories are matched.
```

or did I miss something here ?

**Comment by krader1961** [comment]
I think you're mentally eliding the "by itself" part of the sentence. From *src/lib/libast/include/glob.h*:

```
#define GLOB_STARSTAR 0x0080   /* enable [/]**[/] expansion     */
```

And I see nothing in the implementation to suggest it was intended to work as you expect. For example, from `glob_dir()`:

```
if (!complete && (gp->gl_flags & GLOB_STARSTAR))
    while (pat[0] == '*' && pat[1] == '*' && (pat[2] == '/' || pat[2] == 0)) {
```

**Comment by krader1961** [comment]
FWIW, I agree that it is unfortunate it doesn't work as you expect. Which, by the way, is how it works in fish. But it looks to me like this is an enhancement request, not a bug.

**Comment by krader1961** [comment]
@dannyweldon, Your solution isn't equivalent to what siteshwar expected. That's because `**/*.sh` does not match any files ending in `.sh` in the current directory. Whereas `**.sh` presumably would.

I do think the documentation is unclear on how `**` is handled. So if we don't implement `**.sh` as a shorthand for `*.sh **/*.sh` (which is how fish shell behaves) the documentation should be improved.

**Comment by krader1961** [comment]
@siteshwar Do you agree this isn't a bug? I think we should turn this into a request to improve the documentation and possibly open a new issue to request that patterns like `**.sh` be equivalent to `*.sh **/*.sh`. Whether the latter enhancement could be made short of a major release, and possibly not even then, is open for debate.

**Comment by siteshwar** [comment]
>  Do you agree this isn't a bug?

Yes, I misread the documentation. It's not a bug.
