### ISSUE TITLE
Enable all ksh builtins by default for unit tests

### ISSUE THREAD

**Issue by krader1961** [att/ast#944]
The `oclint` tool warned about code in *src/lib/libcmd/dirname.c* that could be simplified. Which caused me to notice that we have zero explicit tests of builtin `dirname` behavior. Also, there is only one use in all the ksh unit tests and it would only indirectly tell us if it was malfunctioning. This is probably true for some other builtins.

At a minimum we should a) add some basic tests of the `dirname` builtin and b) enable all builtins by default. The latter may or may not be trivial because a year ago when active maintenance resumed a lot of ksh builtin uses in unit tests were explicitly disabled.

**Comment by krader1961** [comment]
@siteshwar Do you have an opinion regarding enabling ksh builtins by default for unit tests? I have a change that does so which mostly works. That is, most unit tests succeed. The failing tests will need a few hours of work to make them compatible with enabling builtins by default. Before I do that work I want to know that you think this is a reasonable thing to do.

**Comment by siteshwar** [comment]
> The oclint tool warned about code in src/lib/libcmd/dirname.c that could be simplified. Which caused me to notice that we have zero explicit tests of builtin dirname behavior. 

`dirname` is not documented in the man page, so I am going to open a documentation bug for it.

> Do you have an opinion regarding enabling ksh builtins by default for unit tests?

I don't have a strong opinion about it. Enabling them by default will improve our test coverage, so if you are willing to spend time on fixing tests I am fine with it.
