### ISSUE TITLE
builtin `cat` broken

### ISSUE THREAD

**Issue by krader1961** [att/ast#951]
When I enabled all builtins by default for unit tests, see #944, it broke the *src/cmd/ksh93/test/basic.sh* and *subshell.sh* unit test scripts. Specifically statements like this that involve reading */dev/fd/3* causes the tests to timeout:

```
if cat /dev/fd/3 >/dev/null 2>&1
```

Those have to be modified to run the external `cat` command to succeed. Why that is the case is unknown at this time.

**Comment by siteshwar** [comment]
If `cat` is executed as an external command `if cat /dev/fd/3 >/dev/null 2>&1` is never true. So the tests under this condition are never executed. If I enable `cat` builtin and commet out [this call](https://github.com/att/ast/blob/f0ed7a93f75028c5237f7d5356dc6f4262b58241/src/cmd/ksh93/tests/basic.sh#L455) to `empty_fifos` all tests pass.

Also, the tests that fail rely on time differences:


```
s=SECONDS
set -o pipefail
for ((i=0; i < 30; i++))
do
    print hello
    sleep .1
done | $bin_sleep 1
(( (SECONDS-s) < 2 )) || log_error 'early termination not causing broken pipe'
```

```
set -o pipefail
float start=$SECONDS end
for ((i=0; i < 2; i++))
do
    print foo
    sleep 1.5
done | { read; $bin_true; end=$SECONDS ;}
(( (SECONDS-start) < 1 )) && log_error "pipefail not waiting for pipe to finish"
set +o pipefail
(( (SECONDS-end) > 2 )) &&  log_error "pipefail causing $bin_true to wait for other end of pipe"
```

They should be rewritten to test exit status instead.

**Comment by krader1961** [comment]
> If cat is executed as an external command if cat /dev/fd/3 >/dev/null 2>&1 is never true. 

Ah, yes. I was thinking the `exec` would create a file descriptor that would remain open across an exec of an external command. But I see from looking at the code these are marked close-on-exec.

> Also, failing tests rely on time differences

Sadly, not true. I took a closer look and the pipefail isn't happening. It's not just a timing race. The difference in behavior is due to the producer/consumer test beginning near line 433. Note that the test in question does not use the `cat` command and therefore has no business being predicated on whether the builtin `cat` is enabled.
