### ISSUE TITLE
`whence -a` is broken if builtin for a command is enabled

### ISSUE THREAD

**Issue by siteshwar** [att/ast#954]
**Description of problem:**
`whence -a` is broken if builtin for a command is enabled

**Ksh version:**
2017.0.0-devel-1945-gc7752ec6-dirty

**How reproducible:**
Always

**Steps to reproduce:**
```
whence -a cat
builtin cat
whence -a cat
```
**Actual results:**
```
cat is a shell builtin
cat is /usr/bin/cat
cat is a tracked alias for /home/situ/upstream/ast/build/cat
```

**Expected results:**
```
cat is a shell builtin
cat is /usr/bin/cat
cat is a tracked alias for /usr/bin/cat
```

**Additional info:**
This bug is present in `ksh-20120801`.

**Comment by DavidMorano** [comment]
I reported this very bug a bazillion years ago, to the AST team, and they never did clean it up. I think that they had some other problem with |whence| (some worse problem) and they somehow forgot about this present bug reported above. I have learned to live with this particular bug (just ignoring it) for almost 20 years now.

**Comment by krader1961** [comment]
Thank you, @siteshwar and @DavidMorano, for commenting on this. This is but one of many similar issues where the old AST team seemed to be more focused on implementing new behavior (which introduced new bugs) than fixing moderately serious bugs in the existing code.

Few projects are bug free. A lot of code I've written has bugs. But I've always prioritized fixing bugs likely to be seen over implementing new features. That the old AST team felt that ignoring significant bugs (as opposed to bugs unlikely to ever be noticed) was acceptable makes me a sad puppy.j

**Comment by DavidMorano** [comment]
> ...  than fixing moderately serious bugs in the existing code.

I do not know exactly why this fell through the cracks (it did), but I
think initially it was felt that it was not a high priority as there was
some other |whence| related bug that they felt that had to be fixed first.
I forget what that other bug was now (it was so long ago). Then somehow,
this bug above was never handled.

**Comment by brdjns** [comment]
> Thank you, @siteshwar and @DavidMorano, for commenting on this. This is but one of many similar issues where the old AST team seemed to be more focused on implementing new behavior (which introduced new bugs) than fixing moderately serious bugs in the existing code.
> 
> Few projects are bug free. A lot of code I've written has bugs. But I've always prioritized fixing bugs likely to be seen over implementing new features. That the old AST team felt that ignoring significant bugs (as opposed to bugs unlikely to ever be noticed) was acceptable makes me a sad puppy.j

This bug cropped up for me too recently, and I'm glad to know that it's been known for (20? odd years). And kudos for prioritising the fixing of existing bugs over feature bloat.

**Comment by siteshwar** [comment]
There is one more bug hidden here. Without loading `cat` builtin, `whence -a` should give this output:

```
cat is /usr/bin/cat
cat is a tracked alias for /usr/bin/cat
```

But it only shows:

```
cat is a tracked alias for /usr/bin/cat
```

Handling of tracked aliases seems a bit tricky.

**Comment by DavidMorano** [comment]
@siteshwar 

> Handling of tracked aliases seems a bit tricky.

:-) :-) !!!

Not really funny, but yes. Bugginess w/ either |whence| builtin code or the storage of PATH-related meta data (maybe some corruption) or code (do not know which one, to maybe both) has always been somewhat buggy.  I reported these sorts of bugs somewhere between about 15 to maybe 18 years ago.

At one point, I tried to look at the |whence| source code myself, but not having a few days to spend on that, I got confused rather quickly and gave up. I am sorry that my laziness has gone on for all of these years.

It is all the more reason why I appreciate that you all are devoting so much time and effort towards cleaning up many of these old (and steadfast) bugs. Thanks again.

**Comment by siteshwar** [comment]
I am pondering if current behavior is correct. Is it right to set tracked alias when a command name is searched (but not executed) ?

**Comment by siteshwar** [comment]
@DavidMorano I have put an experimental change through [this commit](https://github.com/siteshwar/ast/commit/2895f41084f6c3c93229d06e16549f82a6707326). I will have to split it into separate commits and discuss it with others before opening a pull request, but you are welcome to try it. I can't think of a situation where [this block](https://github.com/att/ast/blob/6f3bb499f2c8dde115dfe343e42500b9e61201e1/src/cmd/ksh93/bltins/whence.c#L285-L287) would make sense.

**Comment by krader1961** [comment]
> Is it right to set tracked alias when a command name is searched (but not executed) ?

Yes, IMHO. The only interesting wrinkle is how to handle the case where the command isn't found (i.e., negative caching). Similarly, just because the command was found in `$PATH` in the past should we trust that our cached "tracking" of the command is still valid? What should invalidate that cached information other than something blatant like a change to `PATH`?

**Comment by siteshwar** [comment]
I have fixed the original bug. But given the way how `whence` is implemented. no surprises there are other bugs hidden there. This code would have to be rewritten at some point in future.
