### ISSUE TITLE
Investigate use of memory allocated by `fmtbuf()` function

### ISSUE THREAD

**Issue by siteshwar** [att/ast#962]
`fmtbuf()` function is used to allocate small chunks of memory that are short lived. We have seen one bug report (#959) due to prolonged use of memory allocated by this function. This issue tracks if there are other places in code that abuse memory allocated by `fmtbuf()`.

**Comment by krader1961** [comment]
Note that almost all of the `fmtbuf()` uses are in the *src/lib/libast/string* code that contains that function. And AFAICT it really should be a private function to that code. The uses by *astconf.c*, *optget.c* or *dll_lib.c* are invalid as far as I'm concerned. For the * src/lib/libast/string* code those functions should deal with any requisite `strdup()` depending on their definition.

This is a difficult issue to characterize. It's not really a bug. It's more like a misfeature. So I'm going to flag it as a cleanup.

**Comment by krader1961** [comment]
I've decided that fmtbuf() is a dangerous optimization. The intent is to avoid having to introduce `malloc()` and `free()` calls for buffers whose lifetime should be short. At least one of those uses (in  `optget_secname()`) is completely pointless. And as already identified by issue #959 there is no way to ensure that the static buffer returned by `fmtbuf()` won't have a long lifetime.

**Comment by krader1961** [comment]
To be crystal clear: The `fmtbuf()` API is fundamentally broken. That it was introduced as a micro optimization, without any documentation to support its introduction, only serves to reinforce my judgement on its presence. I appreciate the cleverness of this API while simultaneously condemning it in the context of the C language which does not support garbage collection of objects.
